### ISSUE TITLE
Karma error

### ISSUE THREAD

**Issue by AnnaKL** [makersacademy/slack-overflow#10]
Hi guys.

I'm trying to run Karma but it giving me and error I haven't seen before. 

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
 ReferenceError: Can't find variable: require
 at /Users/annaklimas/Projects/Makers/todo_challenge/node_modules/karma-chrome-launcher/test/jsflags.spec.js:1
```

First line on that file looks like that:
``var launcher = require('../index');```

My set up in terms of index file is exactly the same as I had in the GithubSearch challenge. 
https://github.com/AnnaKL/todo_challenge
Any idea how to deal with that error?

Thanks a lot.

**Comment by spike01** [comment]
Line 23 of your karma.conf is missing `test` before the `**`, so Karma is trying to run every single file that ends in `spec`, in all of the submodules in node_modules. 

That was a bit of a subtle one to catch!

**Comment by AnnaKL** [comment]
Wow. Thanks a lot Spike.
