### ISSUE TITLE
Sinatra session not saving after redirect

### ISSUE THREAD

**Issue by chweeks** [makersacademy/slack-overflow#102]
We are trying to save :name to sessions on the '/name_input' page, where it then redirects to the '\game_setup' where the sessions[:name] can be accessed.
```
  enable :sessions

  get '/name_input' do
    erb :name_input
  end

  post '/name_input' do
    session[:name] = params[:name]
    p session[:name]
    redirect ('/game_setup')
  end

  get '/game_setup' do
    p session[:name]
    erb :game_setup
  end
```
name_input.erb 

```
<% if @name && !@name.empty? %>
  <%= @name %>'s Game
<% else %>
  <form action="/name_input" method="post">
    What's your name?
    <input type="text" name="name" required autofocus>
    <input type="submit" value="New Game">
  </form>
<% end %>
```
<img width="616" alt="screen shot 2015-09-16 at 13 53 44" src="https://cloud.githubusercontent.com/assets/13521236/9905278/0059b086-5c7c-11e5-8041-fcc856671a01.png">

The screenshot above shows in terminal that the session[:name] is "Chris" before the redirect ('/game_setup') but is nil within the '/game_setup'.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by tansaku** [comment]
thanks @chweeks - can you also post a link to your repo?

**Comment by tansaku** [comment]
superficially this looks like this should work - http://www.sinatrarb.com/faq.html#sessions - however I think there is likely something odd going on somewhere else in your code ...

**Comment by chweeks** [comment]
https://github.com/chweeks/BattleshipsWeb

**Comment by chweeks** [comment]
(From @sjmog): This is a sessions issue with Shotgun. We need to remind students that Shotgun occasionally - very rarely - fails to deal with the `session` properly.

**Comment by chweeks** [comment]
Cheers guys.

**Comment by tansaku** [comment]
right  - you need to set the secret - I felt sure you told me you were using rackup :-)  Try searching for "shotgun session problem" and see the first hit:

http://stackoverflow.com/questions/9827151/shotgun-everytime-got-new-sessions-cant-store-datain-sessions
