### ISSUE TITLE
codewars: isAnagram

### ISSUE THREAD

**Issue by squarebe** [makersacademy/slack-overflow#103]
so i pretty much got the code the initial test are passing, 7 pass/3 fails while i submit. my only issue is the code breaks when i try "||" or "or"

instructions for the kata:
"Any word or phrase that exactly reproduces the letters in another order is an anagram." (Wikipedia). Add numbers to this definition to be more interest.

Examples of anagrams:

William Shakespeare = I am a weakish speller
silent = listen
12345 = 54321
The challenge is to write the function isAnagram to return True if the word test is an anagram of the word original and False if not.

Note: Anagrams are case insensitive, ignore all non-alphanumeric characters, input will always be two strings. Also: two identical words may be considered to be an edge case of an anagram, but for this kata they are still correct anagrams.

my code is so far:
ruby
```
def isAnagram(test, original)
  if test.is_a? String #|| original.is_a? String
    test.downcase.split(%r{\s*}).sort == original.downcase.split(%r{\s*}).sort
  else
    false
  end
end
```
i do hashed out the valuation of the second string, the test runs with 7 pass/ 3 fails. when i unhash it the error message is:
-e:3: syntax error, unexpected tCONSTANT, expecting keyword_then or ';' or '\n'
-e:7: warning: else without rescue is useless
-e:8: syntax error, unexpected keyword_end, expecting end-of-input.
suggest some typo...

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by squarebe** [comment]
thx for nothing
