### ISSUE TITLE
RSpec test for array `include`

### ISSUE THREAD

**Issue by trwh** [makersacademy/slack-overflow#104]
Hi,

I'm writing a test to confirm that a randomisation routine for rock, paper, scissors returns one of three symbols: `:rock`, `:paper`, or `:scissors`. These are stored as a constant in a `Hand` class, `ALLOWED_SHAPES = [:rock, :paper, :scissors]`.

Looking at my favourite RSpec cheat sheet I've cooked up:

```
  it 'can be asked to take a random RPS shape.' do
    subject.randomise
    # Woah, coaches! Is the below OK?
    expect(Hand::ALLOWED_SHAPES).to include(subject.shape?)
  end
```

This works. Is this backwards approach OK? I mean, I've put the thing I'm actually testing outside the `expect` method call.

Thanks!

Tim

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sjmog** [comment]
It's absolutely fine: in fact, that's exactly how I do it. 'backwards' maybe, but totes acceptable in my book :)

**Comment by trwh** [comment]
Thanks, good to know! :)
