### ISSUE TITLE
Getting "Chrome is idle" when testing with Karma

### ISSUE THREAD

**Issue by winnieau** [makersacademy/slack-overflow#105]
Hello, I just tried to revisit my todo challenge since I didn't get to complete it and I'm trying to run npm test to test with Karma. In the package.json file, I already set up the scripts section to run the karma command for testing like I did previously in the angularjs walkthrough and when I submitted the challenge running npm test was working. Now it is telling me that Karma is connected but that PhantomJS and Chrome are idle. Halp!

<img width="1203" alt="screen shot 2015-09-18 at 11 49 00 am" src="https://cloud.githubusercontent.com/assets/12464809/9963989/e48dd8c4-5dfb-11e5-8b4b-7d14a6f27003.png">

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sjmog** [comment]
Idle is OK! It means 'not doing anything right now'. You need to figure out why they're not doing anything :)
