### ISSUE TITLE
Is there a way to write a long line of boolean expression over multiple lines?

### ISSUE THREAD

**Issue by chn-challenger** [makersacademy/slack-overflow#106]
For our weekend challenge RPS, I am trying to refactor this one line of code (boolean expression):
```ruby
player1_choice == :rock && player2_choice == :scissors || player1_choice == :paper && player2_choice == :rock || player1_choice == :scissors && player2_choice == :paper
```
it is 170 or so characters.  I know ways to rewrite the same functionality in multiple lines for example:
```ruby
    boolean = player1_choice == :rock && player2_choice == :scissors
    boolean = boolean || player1_choice == :paper && player2_choice == :rock
    boolean = boolean || player1_choice == :scissors && player2_choice == :paper
    boolean
```
However, the above is not as readable, and I was wondering is there something _equivalent/similar_ to the way we can break a long string using / for example:
```ruby
"This is a very very very very very very very very very very very very "/
"very very very very long string!"
```
Most importantly, I hope my question makes sense (practicing asking questions).

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by trwh** [comment]
Hi Joe,

I achieved this using round brackets,

```
    return :hand_1_win if (
      ( hand_1.shape? == :rock ) && ( hand_2.shape? == :scissors )  ||
      ( hand_1.shape? == :paper ) && ( hand_2.shape? == :rock )  ||
      ( hand_1.shape? == :scissors ) && ( hand_2.shape? == :paper )
      )
```

Hope this helps!

Tim

**Comment by sjmog** [comment]
Nice solution @trwh . I prefer to do use a `Hash` as a library, like this:

```ruby
def win_table
  {
    rock: { rock: :draw, paper: :lose, scissors: :win },
    paper: { rock: :win, :paper: :draw, scissors: :lose },
    scissors: { rock: :lose, paper: :win, scissors: :draw }
  }
end

def result(my_shape, their_shape)
  win_table[my_shape][their_shape]
end
```

Ta-da! No messy conditionals :)

**Comment by trwh** [comment]
Thanks @sjmog!

Ken, the senior who did my code review, had an even more concise way - he just stored the `:win`s in the hash and then tested for a draw before checking who won. Another idea! :)

Tim

**Comment by chn-challenger** [comment]
Thank you Tim!  I have since added lizard and spock and refactored the code in a different way.  It's good to know however this can be done.
