### ISSUE TITLE
Sinatra raising error because I have 'enabled the show_exceptions setting'

### ISSUE THREAD

**Issue by Adrian1707** [makersacademy/slack-overflow#107]
When I run 'rackup' and visit my localhost page, I receive this error message. 

![screen shot 2015-09-20 at 08 51 49](https://cloud.githubusercontent.com/assets/10603440/9979787/2d58478a-5f76-11e5-9acc-324d90ac49e1.png)

It says at the very bottom "You're seeing this error because you have enabled the show_exceptions setting." So far my code looks like this in my RPS Web file. 

![screen shot 2015-09-20 at 08 58 33](https://cloud.githubusercontent.com/assets/10603440/9979794/944dda7c-5f76-11e5-89d5-b3490db8dd53.png)

I'm lost as to why this error is happening, and what exactly I can do about it. Everything seems to be correctly placed, and I can't move forward until this is fixed.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.
