### ISSUE TITLE
nested form for with different models

### ISSUE THREAD

**Issue by gerard-morera** [makersacademy/slack-overflow#108]
Hi and thanks everybody who is reading this now. 

I am doing an small commerce app.
Full access to code on [my github](https://github.com/gerard-morera/colossus_shop/tree/24-create-path-views)
I have two models. Products and Categories. They have a many to many relation.

```
module Admin 
  class ProductsController < ApplicationController
    def new
      @category = Category.all
      @product  = Product.new
    end
  (...)
end
```
The new product controller method is:
```
<%= form_for [:admin, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, id: "name" %>
  <%= f.label :description %>
  <%= f.text_area  :description, size: "30x3", id: "description" %><br>
  <%= f.label :categories %>
  <%= f.collection_check_boxes :category_ids, @category, :id, :title %><br><br>
  <%= f.label :submit%>
  <%= f.submit "save", id: "submit" %>
<% end %>
```

There is as well a validation that does not let create a product without having any category.
The problem i face here is that i have to create its category before the product.

I want to be able to display a part from the check box of the categories already created, a field that let me create a new category while I create a new product.

Can you help me please?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sjmog** [comment]
Do you want the field that lets you create a category to update the available categories instantaneously (i.e. via JS)?

**Comment by sjmog** [comment]
But as a guide for multiple form models, I tend to use ryanb's [Nested Form](https://github.com/ryanb/nested_form)

**Comment by gerard-morera** [comment]
@sjmog 
"Do you want the field that lets you create a category to update the available categories instantaneously (i.e. via JS)?"
Not sure what you talking about. (i want to be able create a product and if it needs category (not provided by the checkboxes) it creates one). I will check as well the guide you sent me.
