### ISSUE TITLE
remote true on button_to

### ISSUE THREAD

**Issue by gerard-morera** [makersacademy/slack-overflow#109]
Hi! I am doing a small rails app.

I am trying to make an ajax call.
Despite I use `remote: true` the button_to is making a non ajax request. It redirects me to this url `http://localhost:3000/lines?product_id=1`

```
<% @products.each do |product| %>
    <%= link_to product.name, controller: "store", action: "show", id: product %><br>
    <%= button_to "Add to Cart", {controller: "lines", action: "create", product_id: product.id}, method: "POST", remote: true %>
  <% end %>
```
[github repo](https://github.com/gerard-morera/colossus_shop/blob/26-add-product-to-cart/app/views/store/index.html.erb)

Any idea? 

Thanks!

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by gerard-morera** [comment]
Answer:
http://stackoverflow.com/questions/32780589/remote-true-on-button-to-not-makes-ajax-call
