### ISSUE TITLE
No element found using Protractor `by.binding` locator 

### ISSUE THREAD

**Issue by chidumaga** [makersacademy/slack-overflow#11]
I have an angular binding element wrapped in an html span element with the class `.greet`. When I try to test the value of the angular element I get the following error:

```
NoSuchElementError: No element found using locator: by.binding("todo.task")
```

This was in my test:

`expect(element(by.binding('task')).getText()).toEqual('hello friend');`

It was working fine when my angular element was outside the `<span>` tags but that error appeared as soon as I added them. I read <a href="http://angular.github.io/protractor/#/api?view=ElementFinder.prototype.element">here</a> that Protractor tests can be chained and so I changed my test to this:

```
expect(element(by.css('.greet')).
    element(by.binding('todo.task'))).getText().toEqual('hello friend');
```

but still no joy. It is almost surely something to do with those pesky `<span>` tags but can't figure out what.

Thanks in advance for any help you give.

@rodcul

**Comment by spike01** [comment]
Without seeing any code, I suspect you need to use `by.repeater`, because it's unlikely you'll have a single todo task bound to your controller.

**Comment by chidumaga** [comment]
Thanks for the answer Spike but that unfortunately didn't fix the error. I've <a href="https://github.com/chidumaga/todo_challenge/blob/master/test/e2e/todoFeature.js">pushed the code to my repo</a>, failing test and all. I also tried `exactRepeater` and `exactBinding` with no success.

**Comment by spike01** [comment]
`element(by.repeater('todo in todo.taskList'))` is the syntax you're looking for. I have the test passing locally.

**Comment by spike01** [comment]
https://github.com/makersacademy/course/blob/master/further_javascript/protractor.md#step-4---lists-of-elements
