### ISSUE TITLE
Why do we need these anonymous functions for our tests to work? 

### ISSUE THREAD

**Issue by Adrian1707** [makersacademy/slack-overflow#110]
We currently have some Jasmine tests that require an anonymous function in order for our tests to run.

We have two spec files: Airport and Plane. We have two tests in Airport spec that expect a function(method) to throw an error under certain conditions (Airport is full & Weather is stormy). In the absence of these anonymous functions in the last line of our tests, not only do they not run, but prevent the rest of the tests in the Airport spec from running as well. I am unsure why these anonymous functions make all the difference, and why in their absence the rest of the tests do not run at all in Airport spec. I've posted both tests below. 

![screen shot 2015-09-29 at 15 36 27](https://cloud.githubusercontent.com/assets/10603440/10167332/004fdeb4-66c0-11e5-9f85-812a46baaa02.png)

![screen shot 2015-09-29 at 15 36 38](https://cloud.githubusercontent.com/assets/10603440/10167344/104ce820-66c0-11e5-94df-8c351bfef74b.png)

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by spike01** [comment]
I apologise if this seems cryptic, but let's look at the Ruby equivalent:

(syntax might be off, I'm translating this freehand)

```ruby
it "should not be able to land any aircraft if weather is stormy" do
  allow(Kernel).to receive(:rand).and_return(0.4)
  expect { airport.land(plane) }.to raise("Too stormy to land")
end
```

What happens if you change the `{}` to normal parens?

**Comment by spike01** [comment]
Also, you could write the same code sample above in a different way:

```ruby
it "should not be able to land any aircraft if weather is stormy" do
  allow(Kernel).to receive(:rand).and_return(0.4)
  expect do 
      airport.land(plane) 
    end.to raise_error("Too stormy to land")
end
```

Which may also give you some insight into anonymous functions

**Comment by Adrian1707** [comment]
Spike, in reference to your first question in Rspec if you change to normal parens it'll fail the test but in Jasmine it won't run it at all without the anonymous function. It'll also affect the rest of the tests in the spec file so they won't run either.

**Comment by spike01** [comment]
What do you think happens in Javascript when there's an uncaught error?

**Comment by sjmog** [comment]
Spike is asking the right questions

**Comment by sjmog** [comment]
And Mechacoach is awesome
