### ISSUE TITLE
Function to change CSS Ids with Javascript functions. 

### ISSUE THREAD

**Issue by Adrian1707** [makersacademy/slack-overflow#111]
I'm currently trying to change a CSS ID in one of my Javascript functions. I have a number on the screen that changes as the buttons are pressed, so 'Increase temperature will increase the number by 1'.

![screen shot 2015-09-30 at 20 17 39](https://cloud.githubusercontent.com/assets/10603440/10203832/5656180a-67b0-11e5-96b6-e19d6afee74e.png)

I've written this function for the Thermostat which checks if the thermostat temperature is below or above various numbers, and changes the colour of the font if the condition is met.

![screen shot 2015-09-30 at 20 18 56](https://cloud.githubusercontent.com/assets/10603440/10203874/85d6a298-67b0-11e5-9234-dd759b323b5f.png)

I then call this function in the other functions like so:

![screen shot 2015-09-30 at 20 20 32](https://cloud.githubusercontent.com/assets/10603440/10203914/bcf1a07a-67b0-11e5-8b8d-b8665f3e7126.png)

Everywhere I've searched online suggests using the getElementById would work and change the color of the Id it's getting. I've defined the Id 'temp' in the HTML document like so. 

![screen shot 2015-09-30 at 20 21 23](https://cloud.githubusercontent.com/assets/10603440/10203953/f0d9401e-67b0-11e5-8586-6eca79dd21ad.png)

When I run the HTML document in the browser the buttons for increasing and decreasing temperature no longer work, and will not change colour also.

Not only that, but as soon as I include the changeColor function in my JS file the buttons on the page stop working. I'm curious as to why this is.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by spike01** [comment]
Is there any info in your console? Sounds like a script error

**Comment by Adrian1707** [comment]
Oh hell there's something deeply wrong with this code. When I remove the changeColor function above and press 'Increase temperature' it's increasing the number on the page but not in the console. I need to fix this first as that's a serious issue.

**Comment by Adrian1707** [comment]
That issue is fixed now. The error message in the console says "Uncaught ReferenceError: changeColor is not defined". But I've defined it in my Javascript file. Right?

**Comment by spike01** [comment]
Right! But look at how you're calling it - **where** have you defined it?

**Comment by Adrian1707** [comment]
I've now defined the changeColor function at the top of my page like so

![screen shot 2015-10-01 at 00 11 07](https://cloud.githubusercontent.com/assets/10603440/10209218/0ce67b58-67d1-11e5-9ab9-05ab95e2f27b.png)

and call that function inside each of the other functions (upButton and downButton) like so 

![screen shot 2015-10-01 at 00 12 46](https://cloud.githubusercontent.com/assets/10603440/10209237/3ab909ec-67d1-11e5-9197-09da33773b02.png)

I don't understand why the console says the changeColor function is 'Undefined'.

**Comment by Adrian1707** [comment]
Feel like i'm getting closer though!

**Comment by spike01** [comment]
You are extremely close! Here's a clue: what's the difference in use between:

```javascript
MyObject.prototype.myFunction = function() {
 // code goes here
}
```
and
```javascript
function myFunction() {
  // code code code
}
```

**Comment by Adrian1707** [comment]
I managed to get it to work by writing 'this.changeColor();' in each of the functions, though I'm not sure why that is. I'm struggling to answer the above, but it's probably a sign I need to head to sleep. This will be for morning Adrian to research. Thanks Spike for your help so far.

**Comment by Adrian1707** [comment]
Ah, is it because the changeColor function is defined under Thermostat, so when I call it under another Thermostat function I need to reference it by using 'this'? I'm struggling to put it in words, but am I on the right track there?
