### ISSUE TITLE
Why do my Rspec tests work in isolation but fail when running the whole test suite?

### ISSUE THREAD

**Issue by jonathansayer** [makersacademy/slack-overflow#113]
I'm currently working on programming a chess game on Rails, and have run into some issues when testing with class doubles. In order to make use of chess positions such as 'A1' I have created a service, called ConvertCoordinates, which will convert these strings into an array of numbers and back again (i.e 'A1' will be converted to [1,1] etc.) Most of my models call a class method in ConvertCoordinates called "to_numerical_coords".  In my unit tests I have stubbed the class ConvertCoordinates with a class double and allowed it to receive to_numerical_coords. All test pass if they are run in isolation but those that use the class double fail when the whole rspec suite is run. I have purposely misspelt the class method name "to_numerical_coords", temporarily to make sure I'm stubbing them correctly, hence the tests are failing, otherwise the tests pass (but are dependant on the ConvertCoordinates class). If stubbed correctly they should pass despite the spelling error in the ConvertCoordinates class. 

Example of unit test in the King model which passes in isolation:

<img width="625" alt="screen shot 2015-10-05 at 16 02 27" src="https://cloud.githubusercontent.com/assets/12294600/10284167/8d1e5e60-6b7a-11e5-9c78-638f2ef3bc39.png">

the ConvertCoordinates service being used in the king model:

<img width="606" alt="screen shot 2015-10-05 at 15 13 31" src="https://cloud.githubusercontent.com/assets/12294600/10283319/013495de-6b77-11e5-8762-448f640db2bf.png">

and the error message when running rspec: 

<img width="557" alt="screen shot 2015-10-05 at 15 15 44" src="https://cloud.githubusercontent.com/assets/12294600/10282685/05801634-6b74-11e5-8e66-a5fefb384815.png">

and test passing when run in isolation:

<img width="331" alt="screen shot 2015-10-05 at 15 16 51" src="https://cloud.githubusercontent.com/assets/12294600/10283327/0b09b8b4-6b77-11e5-96e4-05f770b35305.png">

Side Note: Nothing is being created in the test database when running the tests (in any test), which I understand can cause tests to only pass in isolation. I'm just trying to stub the service.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sjmog** [comment]
@jonathansayer my guess is that something is failing in the referencing of `ConvertCoordinates` in your test. Are you sure that you have `require`d it in each test you are using it?

**Comment by jonathansayer** [comment]
@sjmog: Hi Sam. No, I'm not requiring it in the tests but I'm trying to class stub it instead. I presume thats the right thing to do in this case, I'm not too sure since I've never used class doubles before.

**Comment by mechacoach** [comment]
Does require fix it?

**Comment by jonathansayer** [comment]
Ermm....well I havn't looked at this code in over a month, but it appears to be working now (without the require) so I'm just trying to figure out if its something I've done since posting the problem.

**Comment by sjmog** [comment]
:+1:
