### ISSUE TITLE
Can't DateTime to display nicely when using dm-timestamps @channel

### ISSUE THREAD

**Issue by winnieau** [makersacademy/slack-overflow#115]
Hello everyone,

I'm revisiting the Chitter challenge and right now in the process of formatting my timestamp. I got the timestamp to display when someone makes a new post, but it looks really ugly. My code in the app/views/peeps/index.erb looks like this: 

<img width="478" alt="screen shot 2015-10-09 at 9 55 09 am" src="https://cloud.githubusercontent.com/assets/12464809/10395596/dee659a2-6e6b-11e5-9ee7-9ea74a11a3df.png">

And in my peep model looks like this

require 'dm-timestamps'

class Peep
  include DataMapper::Resource
  property :id, Serial
  property :content, String
  timestamps :at, DateTime
end

In the index.erb I tried to write it like this: 

    <h1>Peeps</h1>
    <ul id="peeps">
      <% @peeps.reverse.each do |peep| %>
        <div id="each_peep">
          <%= peep.content %> <div>posted on: </div>
          <%= "#{ peep.created_at.strftime("%H:%M on %d/%m/%y") }" %>
        </div>
      <% end %>
    </ul>
  </div>
</div>

and call the .strftime method, but for some reason I get a Sinatra error that says:

<img width="1102" alt="screen shot 2015-10-09 at 9 59 19 am" src="https://cloud.githubusercontent.com/assets/12464809/10395731/8278309a-6e6c-11e5-8676-d5b44223095e.png">

This method seems to work for other people just fine, so the only thing I could think of is that I can't call .strftime on "created_at". 

Can anyone help me with this?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by spike01** [comment]
Hi @winnieau - if you look at your error message, it's not that you can't do what you're trying to do, but that whatever peep you're trying to call `strfttime` on has a `created_at` value of `nil`. Maybe log out the peep you're trying to display and see why that is. Does that point you in the right direction?

**Comment by winnieau** [comment]
Hi @spike01 I just write "p peep" and it returned "#"...not entirely sure what that means
