### ISSUE TITLE
Saving a winning team to a database - method in a model

### ISSUE THREAD

**Issue by benhawker** [makersacademy/slack-overflow#116]
I have a Match model and a team model.

The match model has the following attributes: 

```   
 t.string   "team_one" (this holds a team_id - i.e an integer)
 t.string   "team_two"
 t.integer  "team_one_score"
 t.integer  "team_two_score"
 t.integer  "winning_team"
```

I have a method in my match model:
```  	
def winner?
  return team_one if team_one_score == 10
  return team_two if team_two_score == 10
  nil
end
```
This returns the id of the winning team if i were to call match.winner?.

I want to persist the team_id in the winning_team field for each match. Have tried various approaches such as using the shovel operator to pass it in and have googled but am coming up blank.

If anyone can help with this fairly basic noob issue I would be eternally grateful! :)

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by benhawker** [comment]
```		def assign_winner
			self.winning_team == winner?
		end
```
Another approach with simple assignment but cannot get this going either.

**Comment by tealpaintedduck** [comment]
You want something like self.update(winning_team: winner?.id), but I'm a bit loath to say it's the correct approach. You're not creating a proper association there, did you want one?

**Comment by benhawker** [comment]
Thanks @tealpaintedduck this helped sort this for me.
