### ISSUE TITLE
bundle issue with webmock

### ISSUE THREAD

**Issue by gerard-morera** [makersacademy/slack-overflow#117]
hello, I am doing a rails api and I want to mock an external service with `webmock/rspec`.
```
group :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'webmock/rspec'
end
```
Whenever I try to bundle I get this message `Could not find gem 'webmock/rspec (>= 0) ruby' in the gems available on this machine.`

I have tried to install the gem in my computer but the problem remains. Any idea?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.
