### ISSUE TITLE
Rails validation testing with Shoulda

### ISSUE THREAD

**Issue by benhawker** [makersacademy/slack-overflow#118]
I have the following validation in Rails in my Team class.

```
	validates :player_one, uniqueness: { scope: :player_two }

```

Team has attributes of player_one and player_two.

This is working but want to get my test to actually work.  I currently have the following:

```
  it 'the team combination must be unique' do
  	ben = User.create(user_name: "ben")
  	bob = User.create(user_name: "bob")
    Team.create(player_one: ben, player_two: bob)
    team = Team.new(player_one: ben, player_two: bob)
    expect(team).to have(1).error_on(:player_two)
    expect(team).not_to be_valid
  end
```
Users have a HABTM association with Teams and vice versa.
Teams have a HABTM association with Matches and vice versa.

Wondered if anyone can point out where I have gone wrong here?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by ptolemybarnes** [comment]
Hi @benhawker. What happens when you run the test?

**Comment by benhawker** [comment]
@ptolemybarnes I must have been dreaming - it is now passing - sorry. The followup I have is how to validate this two ways.

Say you have two players: Bill & Ben.

I still have a situation where I can have 
```team.player_one: "Bill" as well as team.player_two: "Ben" ```

and then problematically:

```team.player_one: "Ben" as well as team.player_two: "Bill" ```

Asides from designing my associations and relations in a better way any ideas as how to prevent this being allowed?
