### ISSUE TITLE
Travis CI build failing for todo_challenge (bower install fails)

### ISSUE THREAD

**Issue by trwh** [makersacademy/slack-overflow#123]
Can anyone help with a Travis issue? I’m getting this error,

```
$ bower install
/home/travis/build.sh: line 41: bower: command not found
The command "bower install" failed and exited with 127 during .
Your build has been stopped.
```

For this build: https://travis-ci.org/makersacademy/todo_challenge/builds/87024106

Here is my `.travis.yml`,

```
script:
  - npm test
  # - node_modules/.bin/protractor test/e2e/conf.js
language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - http-server
  - sleep 3
```

Everything works OK locally, including `bower install` and my `npm test`. Any ideas gratefully received! :)

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by spike01** [comment]
Check your `package.json` - remember that Travis CI build everything from total scratch, as if nothing had ever been installed on the system. Is `bower` a dependency for your project?

**Comment by trwh** [comment]
Thanks, Spike, this fixed it!

For anyone looking at this answer, I added, `"bower": "^1.6.3"` to the `"dependencies"` section of my `package.json` file.

I now have some other Travis issues but will open a separate ticket if necessary. :)

Thanks again,

Tim
