### ISSUE TITLE
Failing to set up Spotify login with Rails

### ISSUE THREAD

**Issue by Adrian1707** [makersacademy/slack-overflow#125]
My partner and I have been on this for about 2 hours now, and it's reached the point of utter blockage. 

We're using the rails gem 'rspotify' to allow our users to sign up with Spotify, it can be found here https://github.com/guilhermesad/rspotify. We've followed the instructions (2/3rds down the page) very carefully and made the necessary additions to our rails files. When we go to click 'Sign up with Spotify' on our home page, we get this screen. 

![screen shot 2015-11-02 at 16 58 09](https://cloud.githubusercontent.com/assets/10603440/10888250/f81532f2-8182-11e5-8fd4-f89a8fc4eb54.png)

Searching around online for people with similar issues has proven futile, and we've changed our files around a lot to try to get around this. Any help would be massively appreciated! Our files match exactly what they've said in their docs, apart from when we've had to replace "<your_client_id>", "<your_client_secret>" with the actual keys given to us.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by Adrian1707** [comment]
This has been resolved.
