### ISSUE TITLE
require 'dm-migrations' returns false

### ISSUE THREAD

**Issue by jrose111284** [makersacademy/slack-overflow#126]
here is our gemfile
```
source 'https://rubygems.org'

ruby '2.2.3'

gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'dm-migrations’
```

we have run bundle 

```
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-postgres-adapter (1.2.0)
```

but still getting false on require

```
Jamies-iMac:bookmarker jamierose$ irb
2.2.3 :001 > require 'data_mapper'
 => true 
2.2.3 :002 > require 'dm-postgres-adapter'
 => true 
2.2.3 :003 > require 'dm-migrations'
 => false
 ```

we are on this chapter
https://github.com/makersacademy/course/blob/master/bookmark_manager/06_using_data_mapper.md

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by tealpaintedduck** [comment]
It gets included with `'data_mapper'`.
So no need to require it by itself. If you run it before `require 'data_mapper'` it will return true.

**Comment by jrose111284** [comment]
thank you worked perfect

**Comment by forty9er** [comment]
if you get back “true” then it means the gem was run for the first time in that session. If you get ‘false’ then it means it is already running. If it wasn’t working, you’d get an error (ie. neither true or false).
