### ISSUE TITLE
DatabaseCleaner strategy types

### ISSUE THREAD

**Issue by k0zakinio** [makersacademy/slack-overflow#127]
Hi

We are currently working through the [Bookmark Manager] (https://github.com/makersacademy/course/tree/master/bookmark_manager) weekly challenge (October cohort) and have a question regarding the [Chapter 12] (https://github.com/makersacademy/course/blob/master/bookmark_manager/solutions/12.md) solution which sets up DatabaseCleaner to clean our database on the running of rspec tests, the solution shows the below.
```
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end
```
The documentation provided by the [official github repo] (https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example) provides the below which differs from the solution.
```
  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end
```
Both work, but my question is why in the solution is setting the strategy to :transactional but then using :truncation to clean instead?  Is the purpose of this line so that :transactional is being set as the default strategy when DatabaseCleaner.clean is called or is there another reason for this?

Thanks,

Andy

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sdorunga1** [comment]
Yes, that's basically it. If you look even in the docs on github, one line lower the set the strategy to the same as we do here. In essence when you do `clean_with(something)` it does a cleaning run with that strategy, when you do `DatabaseCleaner.strategy = :transaction` it sets the default strategy to be used when calling `clean`.

In this case we're running a `clean_with` once before the whole test suite to make sure the database is clean before doing anything and then around each test we clean using transactions.

**Comment by k0zakinio** [comment]
Great, thanks for your help!

**Comment by tansaku** [comment]
related links:

* https://github.com/DatabaseCleaner/database_cleaner#how-to-use
* http://stackoverflow.com/a/10906127/316729

so if we have a set up like this:

```ruby
  config.before(:suite) do # <-- before entire test run
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do # <-- create a "save point" before each test
    DatabaseCleaner.start
  end

  config.after(:each) do # <-- after each individual test roll back to "save point"
    DatabaseCleaner.clean
  end
```

then we are doing a thorough clean of the entire database before we startup (with a truncation, which does a quick remove of all rows), and then we are doing a slightly more complex transaction on each individual test where we roll back just the things that happened in that particular test ...

**Comment by mechacoach** [comment]
Love the analogy of the 'save point' :+1:
