### ISSUE TITLE
Using many to many or one to many relationship for tagging links in bookmark manager

### ISSUE THREAD

**Issue by youngmanr** [makersacademy/slack-overflow#128]
I'm working on this challenge 

https://github.com/makersacademy/course/blob/master/bookmark_manager/15_tagging_links.md

We're build a bookmark manager for links and need to tag a link so links can be filtered by tag.

The challenge suggests many-to-many relationship between the link table and tag table  but the solution appears to use one-to-many.

Given we have many links associated with many tags and many tags associated with many links, it would seem that many-many would be the appropriate approach?

Is there a correct approach in this instance?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by youngmanr** [comment]
I should have read the following pill, things become a lot clearer

https://github.com/makersacademy/course/blob/master/pills/relational_SQL_DBs.md
