### ISSUE TITLE
Tests pass but website not working (tags)

### ISSUE THREAD

**Issue by tansaku** [makersacademy/slack-overflow#129]
On challenge 15-17 of bookmark manager

https://github.com/makersacademy/course/blob/master/bookmark_manager/15_tagging_links.md

tests taken from the solution pass, 

```ruby
  scenario 'searching via tag names' do
    four_links_two_tags
    visit "/tags/bubbles"
    expect(page.status_code).to eq 200
    within 'ul#links' do
      expect(page).not_to have_content('Makers Academy')
      expect(page).not_to have_content('Code.org')
      expect(page).to have_content('This is Zombocom')
      expect(page).to have_content('Bubble Bobble')
    end
  end

def four_links_two_tags
  Link.create(url: 'http://www.makersacademy.com', title: 'Makers Academy', tags: [Tag.first_or_create(tag_name: 'education')])
  Link.create(url: 'http://www.google.com', title: 'Google', tags: [Tag.first_or_create(tag_name: 'search')])
  Link.create(url: 'http://www.zombo.com', title: 'This is Zombocom', tags: [Tag.first_or_create(tag_name: 'bubbles')])
  Link.create(url: 'http://www.bubble-bobble.com', title: 'Bubble Bobble', tags: [Tag.first_or_create(tag_name: 'bubbles')])
end
```

but when we run the website itself what we find is that searching by link will only result in one link returned even when there are two links with that particular keyword, e.g. for

http://localhost:9292/links

* Title: Codewars URL: http://codewars.com Tag: codewars
* Title: HackerRank URL: http://hackerrank.com Tag: codewars

the following only gives a single result:

http://localhost:9292/tags/codewars

* Title: Codewars URL: http://codewars.com Tag: codewars

however if we have the test create the tags via the web interface then it fails to detect the two separate links that are both associated with a single keyword, e.g. 

```
def four_links_two_tags_manual
  visit('/links/new')
  fill_in(:title, with: 'Makers Academy')
  fill_in(:url, with: 'https://www.makersacademy.com')
  fill_in(:tags, with: 'bubbles')
  click_button('Submit')
  visit('/links/new')
  fill_in(:title, with: 'Another Makers Academy')
  fill_in(:url, with: 'https://www.makersacademy2.com')
  fill_in(:tags, with: 'bubbles')
  click_button('Submit')
end
```

The database relation is so

```
 tag_id | link_id 
--------+---------
      1 |       1
      2 |       2
      3 |       3
      3 |       4
      3 |       5
```

```
 id |   tag_name 
----+----------
  1 | one    | 
  2 | two    | 
  3 | one    | 
  4 | cool    | 
  5 | now    | 
```

The above makes it look like we might have a problem in the way tags are created.

The code appears to work fine on tansaku's computer, but is not working for us

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by tansaku** [comment]
aha, we got to the bottom of it - it seems that a little bit of extra data in Dan and Andy's database was making them think it wasn't working when actually it was all good.

Moral of the story - is check the full stack (including DB) when things get tricky, and writing things up helps ...

**Comment by tansaku** [comment]
also cleaning the dev db helps :-)
