### ISSUE TITLE
undefined local variable or method `flash' 

### ISSUE THREAD

**Issue by d9nny** [makersacademy/slack-overflow#131]
Link to question:
https://github.com/makersacademy/course/blob/master/bookmark_manager/20_improving_sign_up_workflow.md

Link to my repo:
https://github.com/d9nny/bookmark_manager_andy

I have installed sinatra-flash and put the gem in the gemfile. Get this error on each test.

>>>>> Error message <<<<<<<

7) searching searching via tag names
     Failure/Error: four_links_two_tags_manual
     NameError:
       undefined local variable or method `flash' for #<BookmarkManager:0x007fc2e9652508>
     # ./app/views/layout.erb:11:in `block in singleton class'
     # ./app/views/layout.erb:-6:in `instance_eval'
     # ./app/views/layout.erb:-6:in `singleton class'
     # ./app/views/layout.erb:-8:in `__tilt_70237555008000'
     # continued down
///////////////////////////////////////////////////////////////////////////////////////////////////

>>>>>>>> from app.rb <<<<<<<<<<<

  post '/users' do
    @user = User.create(email: params[:email],
                    password: params[:password],
                    password_confirmation: params[:password_confirmation])
    if @user.save 
      session[:user_id] = @user.id
      redirect to('/links')
    else
      flash.now[:notice] = "Password and confirmation password do not match"
      erb :'users/new'
    end
  end

//////////////////////////////////////////////////////////////////////////////////////////

>>>>>>>> from layout.erb <<<<<<<<<<<

 <!DOCTYPE html>
<html>
  <head>
    <title>Bookmark Manager</title>
  </head>

  <body>
    <% if current_user %> 
      Welcome, <%= current_user.email %>
    <% end %>
    <% if flash[:notice] %>      
		  <div id='notice'><%= flash[:notice] %></div>
		<% end %>
    <%= yield %>
  </body>
</html>

//////////////////////////////////////////////////////////////////////////////////////////

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by d9nny** [comment]
Solved the above problem with:

insert >> register Sinatra::Flash << within the class in app.rb
change >> flash.now to flash.next
