### ISSUE TITLE
flash message is not coming up in the test, but is locally

### ISSUE THREAD

**Issue by d9nny** [makersacademy/slack-overflow#132]
When we run the capybara test, we get the below error message and when we run it locally it works fine.
I used launchy to open the page during the test and the page didn't have the flash message on it.

Link to question:
https://github.com/makersacademy/course/blob/master/bookmark_manager/20_improving_sign_up_workflow.md

Link to my repo:
https://github.com/d9nny/bookmark_manager_andy

>>>>>> error message >>>>>>>>

Failure/Error: expect(page).to have_content 'Password and confirmation password do not match'
       expected to find text "Password and confirmation password do not match" in "Please register Email Password Password confirm"
     # ./spec/features/password_confirmation_spec.rb:13:in `block (2 levels) in <top (required)>'

>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by jafrog** [comment]
https://github.com/SFEley/sinatra-flash#now-vs-next

https://github.com/d9nny/bookmark_manager_andy/blob/master/app/app.rb#L55

The problem here is that you call `flash.next` rather than `flash.now`. `flash.next` will be displayed in the *next* request while you want to show the message immediately.

**Comment by DeathRay1977** [comment]
We had ```flash.now``` in our code and it didn't work. This is because we do a redirect on the very next line.
```ruby

  post '/users' do
    user = User.create(email: params[:email], password: params[:password], password_confirmation: params[:password_confirm])
    if user.save
      session[:user_id] = user.id
      redirect '/links'
    else
      error_str = ""
      user.errors.each_value {|error| error_str << error[0] }
      flash.next[:notice] = error_str
      redirect '/users/new'
    end
  end
```
We decided to redirect the user back to the registration page.

But, if you are doing something similar to the solution e.g:

```ruby
post '/users' do
  @user = User.new(email: params[:email],
                  password: params[:password],
                  password_confirmation: params[:password_confirmation])
  if @user.save
    session[:user_id] = @user.id
    redirect to('/')
  else
    flash.now[:notice] = "Password and confirmation password do not match"
    erb :'users/new'
  end
end
```
Then you need ```flash.now```
