### ISSUE TITLE
RSpec using data that's not in the bookmark_manager_test db

### ISSUE THREAD

**Issue by youngmanr** [makersacademy/slack-overflow#133]
Rspec test is failing.

```  1) User sign up I can sign up as a new user
     Failure/Error: expect(page).to have_content('Welcome, alice@example.com')
       expected to find text "Welcome, alice@example.com" in "Welcome me@me.com"
     # ./spec/features/sign_up_spec.rb:9:in `block (2 levels) in <top (required)>'```

Don't understand where RSpec is getting the user "me.com".

Using Psql 

SELECT * FROM Users 

is returning 0 rows from the bookmark_manager_test database and bookmark_manager database.

Is this old data being cached?

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by youngmanr** [comment]
Data was being cached, the data was being put in the database by a web_helper method.

Problem solved.
