### ISSUE TITLE
Mocking JSON objects in Jasmine Unit Test

### ISSUE THREAD

**Issue by matt-paul** [makersacademy/slack-overflow#134]
Hi,

We are trying to mock currentUserId.uid.  The id is taken from a Firebase database JSON object.

In the unit test, we would like to test the function only, not the database.

To do this, we are trying to use a jasmine spy,

However the test is failing with the message...

TypeError: 'undefined' is not an object (evaluating 'ctrl.currentEvent')

Any thoughts would be appreciated!
```
describe('CreateEventController', function() {

  beforeEach (module('alarming'));

  var ctrl, $scope;

  jasmine.spyOn(ctrl.currentEvent, 'owner')
  .and
  .returnValue('Bat')

    currentEvent = {
      id : new Date().valueOf(),
      // owner: currentUserId.uid,
      eventTitle : "Bat's Wedding",
      description : "Bat's big day",
      dateTime : eventDateTime.toJSON()
    };

  it ('should be able to create an event', function() {
    eventDateTime = new Date(2015, 10, 6, 11, 5, 0, 000);
    eventTitle = "Bat's wedding";
    description = "Bat's big day";
    expect(ctrl.createEventHash(eventTitle, description, eventDateTime)).toEqual(currentEvent)
  });

});
```
Below is our controller.
```
ionicApp.controller('CreateEventController', function($scope, $cordovaLocalNotification, $state, $firebase) {

  var self = this;

  var eventsRef = new Firebase('https://event-alarm.firebaseio.com/events');

  var currentUserId = eventsRef.getAuth();

  self.createEventHash = function(eventTitle, description, eventDateTime) {
    currentEvent = {
      id : new Date().valueOf(),
      owner: currentUserId.uid,
      eventTitle : eventTitle,
      description : description,
      dateTime : eventDateTime.toJSON()
    };
    return currentEvent;
  };

});
```

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by tansaku** [comment]
@matt-paul so looks like `ctrl.currentEvent` is undefined.  At that point in your code you've just done `var ctrl`; so by default it's going to be undefined.

You need to instantiate your CreateEventController - something like this I imagine:

```javascript
var ctrl = $controller('CreateEventController', { ... } );
```

but I'm just guessing having searched google for "jasmine ionic tests" and I found this:

http://gonehybrid.com/how-to-write-automated-tests-for-your-ionic-app-part-2/

I'm sure you could have got this answered far faster if you posted to StackOverflow, and I'm not even sure if I've given you the right answer, but it's my best guess at the moment :-)
