### ISSUE TITLE
How do I code CSS and HTML to dynamically add a new row on a page? 

### ISSUE THREAD

**Issue by youngmanr** [makersacademy/slack-overflow#135]
I am coding the bowling challenge and want to display the history of each bowl bowled showing the frame number, the pins knocked down with that bowl and the score. I have have a javascript data structure that keeps the history of each bowl bowled and I have written the HTML and CSS that displays one row but I don't know how to write the CSS, javascript and html to add more rows i.e mimicking a table. I haven't used an HTML table because Mozzila says 

```Prior to the creation of CSS, HTML <table> elements were often used as a method for page layout. This usage has been discouraged since HTML 4, and the <table> element should not be used for layout purposes. However, HTML emails are an exception, where tables are still commonly used for layout purposes.```

My HTML page is structured so that I have a container containing two elements, the table title and a row which contains the score. What I want is to add more row, each row showing the score after each bowl.

The link to my repo is https://github.com/youngmanr/bowling-challenge.

Attached is a screen shot of my current layout which clearly shows the page contents.
<img width="1376" alt="screen shot 2015-11-20 at 09 53 59" src="https://cloud.githubusercontent.com/assets/14070334/11297465/84ad7ce2-8f70-11e5-85b2-afaff481a83e.png">

Ands here's the HTML
``` 
<div id="wrapper">
      <div id="header"> Bowling </div>
      <div id="content">
        <div id="content-title">
          <div id="content-title-frame">Frame</div>
          <div id="content-title-roll">Roll</div>
          <div id="content-title-pins">Pins Down</div>
          <div id="content-title-score">Score</div>
        </div>
        <div id="content-row">
          <div id="content-row-frame">Frame</div>
          <div id="content-row-roll">Roll</div>
          <div id="content-row-pins">Pins Down</div>
          <div id="content-row-score">Score</div>
        </div>
      </div>
      <div id="bottom">
        <button id="bowl-ball">Bowl</button>
        <button id="new-game">New Game</button>
      </div>
      <div style="clear: both;"></div>
    </div>
```

The tests all pass and can be run by opening SpecRunner.html in the brower.

The game runs and can be played by opening index.html in the browser.

The html and CSS are in the root named index.html and style.css.

I'm just stuck not knowing what I need to write in HTML, javascript and CSS to dynamically add a new row after each bowl is bowled?

**Comment by nikeshashar** [comment]
Do you have this panel anywhere on your screen? 

https://www.dropbox.com/s/1gnqqkpcszaqzxk/Screenshot%202015-11-20%2011.23.57.png?dl=0

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/11298771/40bd2cae-8f79-11e5-874c-53e8e0148a55.png)

**Comment by youngmanr** [comment]
Yes but no gear wheel so I can't choose any labels to add.

**Comment by nikeshashar** [comment]
Added labels for now. Will flag this with engineering

**Comment by silvabox** [comment]
@youngmanr You _can_ use an HTML table in this case if you want to.  The advice from Mozilla relates to using tables to layout an entire page (which is not good practice!).  However, using a `<table>` as a table is perfectly acceptable - that's what `<table>` is for!

**Comment by silvabox** [comment]
To add content to your page, you can use jQuery `append` methods.  That's probably the cleanest way.  Soon, you'll see another way using Angular, which is even cleaner.

**Comment by silvabox** [comment]
I notice in your HTML that you are misusing `id` attributes:
```
    <div id="content">
        <div id="content-title">
          <div id="content-title-frame">Frame</div>
          <div id="content-title-roll">Roll</div>
          <div id="content-title-pins">Pins Down</div>
          <div id="content-title-score">Score</div>
        </div>
        <div id="content-row">
          <div id="content-row-frame">Frame</div>
          <div id="content-row-roll">Roll</div>
          <div id="content-row-pins">Pins Down</div>
          <div id="content-row-score">Score</div>
        </div>
      </div>
```
When you add another `content-row`, all of these ids will be duplicated.  `id` should only be used when you need to *uniquely* identify *one* element.  In all other cases, use `class`

**Comment by youngmanr** [comment]
Thanks for the feedback, I was confused about the mozilla table comment. I'll investigate both the jquery append method and reverting to using tables. Many thanks.

**Comment by mechacoach** [comment]
In fact, `table` would be best as it's easier to understand than loads of
nested `div`s.

When you use `append`, you can then just add another 'tr' containing your
content.
