### ISSUE TITLE
How do I add a label to a slack-overflow issue

### ISSUE THREAD

**Issue by youngmanr** [makersacademy/slack-overflow#136]
Guidelines for slack-over suggest adding a label to the issue but I can't find a way to add a label to the issue I raised?

**Comment by tansaku** [comment]
@youngmanr you need to be added to the repo - I need to automate this, but let me see ...

**Comment by tansaku** [comment]
I've just added your ronin team and October and November cohort teams to have write access to this repo on the basis that that should give you access to create labels - if it does not, let me know and I will work on this more.

Apologies for the delay

**Comment by youngmanr** [comment]
Seems I can now add labels :) thank you tansaku
