### ISSUE TITLE
Rails Week: Unit testing database behaviour

### ISSUE THREAD

**Issue by samover** [makersacademy/slack-overflow#138]
We set up a has_many relationship between user and restaurants. The next functionality we want to implement is adding a user_id to a newly created restaurant. Before implementing this step, we would like to write a test for this. See [walkthrough](https://github.com/makersacademy/course/blob/master/rails/yelpv2.md#setting-limits-on-users)

We think this should be a unit test on the restaurant model, testing whether a created restaurant has an associated user id. We want to proceed as follows:
* stub a current_user
* create a restaurant : `restaurant = Restaurant.create( name: 'Five Guys' )`
* `expect(restaurant.user).to eq current_user` 

The question is: 
1) is this something to be tested, and if yes, is our procedure correct
2) how to stub a user

**Comment by tansaku** [comment]
@samover you should check out https://github.com/thoughtbot/shoulda-matchers rather than testing the active record functionality per se, you should be setting that you have set up the relations correctly
