### ISSUE TITLE
November-2015 Breakout time limits

### ISSUE THREAD

**Issue by tansaku** [makersacademy/slack-overflow#141]
This topic arose in the week 1 retro.  Concerns were raised that some breakouts went on longer than others and this caused some people to need to hang around waiting for their pair partners to be free.

The design of the standups/breakouts, is that one should have a quick 15 minute standup where everyone mentions a struggle and a success, and then there is a variable length breakout.

In my personal opinion that breakout should not exceed 45 minutes at the maximum and should probably be a lot shorter.  The idea is that those participating in the breakout should all be involved in working out how much of a breakout is needed.  If everyone agrees that they all want to get back to coding, then there is a 15 minute standup and that's it.  Some people could go straight back to coding and others could stay for discussion.  It's flexible.

In order to manage expectations we could introduce something such as saying that all morning breakouts should finish by 10:30am at the very latest.

Or we could arrange it so that during the week people only paired with those people in their own byte so that there would be no waiting for another breakout to finish.

Or we could say that there are no rules, and that you get on with work of your own (e.g. codewars, additional work on weekend challenges etc.) while you wait for your pair to free up.

It's up to you as a team to work out if we should experiment with introducing any of these approaches - please discuss before Monday in the comments below and report back to the coaches to let them know how you'd like things to go.

**Comment by michaellennox** [comment]
Imo it might be useful to set pairs only within bytes. This would give the advantage of minimising time spent in stand up to cover all the issues faced by the byte while at the same time ensuring pairs cover with each other any issues one member may face.

At the same time it could have a detrimental effect due to the much smaller pool of potential pairs but I think this would be outweighed by the benefits.
