### ISSUE TITLE
I made an array that holds planes, I'm trying to get rid of this error; I want PLANE not [PLANE] . much appreciated.

### ISSUE THREAD

**Issue by genzade** [makersacademy/slack-overflow#142]
`Failures:

  1) Airport Land at airport and confirm it has landed
     Failure/Error: expect(airport.land(plane)).to eq plane

       expected: #<Plane:0x007fefe7863308>
            got: [#<Plane:0x007fefe7863308>]

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Plane:0x007fefe7863308>
       +[#<Plane:0x007fefe7863308>]

     # ./spec/airport_spec.rb:12:in `block (2 levels) in <top (required)>'`

**Comment by chweeks** [comment]
It seems your getting what you actually want, a landed plane within the array. So maybe it's the test that needs to change or you could look up a method called flatten that you could use.

**Comment by genzade** [comment]
thanks @chweeks; it seems i was overcomplicating things.
