### ISSUE TITLE
Overriding Bootstrap styling

### ISSUE THREAD

**Issue by k0zakinio** [makersacademy/slack-overflow#144]
In the final stages of my [Instagram Challenge](https://github.com/k0zakinio/instagram-challenge)([stylesheet here](https://github.com/k0zakinio/instagram-challenge/blob/master/app/assets/stylesheets/application.css)), I was adding styling to my page through Bootstrap.

I wanted to override some of the bootstrap defaults so that I could add my own formatting to some of the classes, I attempted something similar to:
```
app/assets/stylesheets/application.css

.panel  {
   color: red;
}
```
However that did not seem to work, the styling did not change. From searching Google I found a way to override the Bootstrap formatting, however it seemed a bit cumbersome.. it involved adding `!important` to every formatting change I made which doesn't feel right, is a bit time consuming and not particularly elegant.

Is there a better way to go about using Bootstrap and making your own custom amendments to the formatting?

Thanks,

Andy

**Comment by silvabox** [comment]
Hi Andy,

CSS operates on a hierarchy of 'specificity'.  It will apply the CSS rule whose selector (e.g. `.panel`) is _most specific to the element_.  While class selectors (such as `.panel` have high specificity, if Bootstrap is already targeting the element more specifically (which it probably is) then it will override your rule.  Adding `!important` is a way to massively increase a rule's specificity but it is a sledgehammer approach.

The best way to override Bootstrap is to get to it before it's compiled from Less (or Sass if you use the port) to CSS.

There's a challenge for you!  There's some advice [here](http://blog.silvabox.com/materialize-on-rails-4-with-bower-and-heroku/) on achieving the same with Materialize (a Bootstrap alternative).  You should be able to adapt the approach.  Let me know if you want some help...
