### ISSUE TITLE
cucumber + capybara setup problem

### ISSUE THREAD

**Issue by christopheralcock** [makersacademy/slack-overflow#145]
Hello,

I'm trying to set up the following repo with cucumber tests:

https://github.com/christopheralcock/lyric-writer

But when I run the cucumber tests as they are, I get 

`undefined method 'visit' for #<Object:0x007ff113af81e0> (NoMethodError)`

Which I take to be a capybara error.  But I can't work out why capybara isn't set up?  I've tried adding `include Capybara::DSL` in a few places but to no avail.

Maybe I'm misusing gems? or there is an init command I need to do?

It's probably something pretty obvious that I'm coming at from the wrong angle though.

You'd think this was the answer
https://github.com/jnicklas/capybara#using-capybara-with-cucumber

But I'm not sure how he means "manually load the capybara/cucumber module"? What file needs editing.  It's not a rails project btw.

Thanks,

Chris

**Comment by spike01** [comment]
Looks like you're missing a `/support/env.rb` file. I added one and now everything works:

```ruby
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/lyric-writer.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app, _ = Rack::Builder.parse_file(File.expand_path('../../../config.ru', __FILE__))


class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  LyricWriter.new
end
```

Also had to remove sinatra/flash but that's incidental :)

I can highly recommend https://github.com/bernd/cucumber-sinatra for starting projects like this
