### ISSUE TITLE
Can anyone here Drupal?

### ISSUE THREAD

**Issue by winnieau** [makersacademy/slack-overflow#146]
I just downloaded Acquia Drupal and Acquia Dev Desktop 2. I'm trying to make a site and so far I have a very basic one going but it looks terrible. I was wondering if anyone has any tips for me because the documentation is really disorganized and Drupal is super counterintuitive seeming. I want to write my own HTML and CSS but I don't know where to write it. It seems to allow you to write some very basic HTML by using tags like <em> and <strong> which I've done but not much past that and applying a new theme.

**Comment by ptolemybarnes** [comment]
@winnieau Doesn't look like it :-(

**Comment by winnieau** [comment]
:/

**Comment by winnieau** [comment]
@ptolemybarnes Thanks for letting me know.
