### ISSUE TITLE
Test fails when mocking Tesco API, using Angularjs ngresource

### ISSUE THREAD

**Issue by youngmanr** [makersacademy/slack-overflow#147]
Repo : https://github.com/youngmanr/tescoin/tree/factory_test_issue

Instructions: 
git clone https://github.com/youngmanr/tescoin/tree/factory_test_issue
bower install
npm install
karma start test/karma.conf.js

Tests are failing when we mock the Tesco api service.
We use angular ngresource to build our url to interface to the Tesco REST api.
We are uncertain about the cause of the error message.
The factory code is
<img width="1245" alt="screen shot 2015-12-08 at 16 58 00" src="https://cloud.githubusercontent.com/assets/14070334/11662071/e30d5b80-9dcc-11e5-8dc6-e5516d05d510.png">

The error message is
<img width="1191" alt="screen shot 2015-12-08 at 17 02 29" src="https://cloud.githubusercontent.com/assets/14070334/11662245/8707fd4e-9dcd-11e5-9869-80e9ae611b6e.png">

**Comment by ptolemybarnes** [comment]
Hey @youngmanr, I've had a quick look at the failure in `searchfactory.spec.js`. As far as I can tell, the immediate problem is that in your test here:
```js
it('returns search results', function() {
    search.query('123456789', 'products')
      .then(function(response) {
        expect(response.data.items).toEqual(items)
      })
    httpBackend.flush();
  });
```
Your expecting the `search.query()` function to return an object that implements the promises interface (then, when, always, etc) but that's not how $resource works.

**Comment by ptolemybarnes** [comment]
@youngmanr shall I close this?

**Comment by youngmanr** [comment]
yes please.

Regards

Robert Youngman
M: 07527 994 300




On 9 Dec 2015, at 09:20, Ptolemy <notifications@github.com> wrote:

@youngmanr <https://github.com/youngmanr> shall I close this?

**Comment by tansaku** [comment]
@youngmanr want to add a note on how we solved it?

**Comment by youngmanr** [comment]
There were two issues at the root of my problem.

First I wasn't using $resource correctly. I was expecting $resource to behave the same as $http.

Secondly, I encountered cross site scripting issues.

To work around the cross site scripting security issue we  used jsonp request. 

self.doSearch = function() {
        $http.jsonp(self.createUrlString())
              .success(function(data){
                self.searchResult = data;
                      self.getInfo();
              });
 };
