### ISSUE TITLE
Cannot stub out rand in Battle challenge

### ISSUE THREAD

**Issue by Wynndow** [makersacademy/slack-overflow#148]
Hello,

Trying to use ```allow(Kernel).to receive(:rand).and_return(10)``` to let a method return a known result instead of a random number.

It's working on my unit tests, however not on my feature tests.

This works:

```
  describe '#reduce_hug_points' do
    it 'reduces the players hug points' do
      allow(Kernel).to receive(:rand).and_return(10)
      expect{bob.reduce_hug_points}.to change {bob.hug_points}.by(-10)
    end
  end
```

This does not:

```
describe 'feature test' do

  before :all do
    allow(Kernel).to receive(:rand).and_return(20)
  end

#Other features tests omitted for brevity

feature 'random damage' do
    it 'should deal a random amount of damage' do
      sign_in_and_play
      allow(Kernel).to receive(:rand).and_return(5)
      click_button('DO A HUG!')
      expect(page).to have_content 'Bob: 145HP'
    end
  end

```

Any help would be amazing.

Cheers

**Comment by jafrog** [comment]
In this example you stub `rand` twice but in the code you only call it once. So only `allow(Kernel).to receive(:rand).and_return(20)` will be run.

**Comment by Wynndow** [comment]
We finally got the test to pass! The problem was that in our web_helper.rb our method for sign_in_and_play was:
```
def sign_in_and_play
  visit('localhost:9292')
  fill_in 'player1', with: 'Vic'
  fill_in 'player2', with: 'Bob'
  click_button('HUG TO THE DEATH!')
end
```
We changed it to this:
```
def sign_in_and_play
  visit('/')
  fill_in 'player1', with: 'Vic'
  fill_in 'player2', with: 'Bob'
  click_button('HUG TO THE DEATH!')
end
```

NO idea why this works but the original doesn't. Any ideas?

Thanks

**Comment by jafrog** [comment]
The later works because with Capybara you're expected to pass relative routes to `visit` rather than whole urls

**Comment by Wynndow** [comment]
Thanks!

**Comment by tam-borine** [comment]
maybe we should rename this issue ? got my hopes up...
