### ISSUE TITLE
Stubbing methods for any instance of a class

### ISSUE THREAD

**Issue by saratateno** [makersacademy/slack-overflow#149]
Hello,

I want to create multiple doubles of a single class, with each responding to the same set of methods.

e.g.

```
let(:player_1) (double :player, method1: true, method2: false)
let(:player_2) (double :player, method1: true, method2: false)
let(:player_3) (double :player, method1: true, method2: false)
```

Is there a way of doing all of this in a single line?

I can only find Rspec documentation that allows you to do this within an `it` block, but not as a let statement.

https://www.relishapp.com/rspec/rspec-mocks/v/2-6/docs/method-stubs/stub-on-any-instance-of-a-class

Thanks!

**Comment by ptolemybarnes** [comment]
This can be done iteratively:

```ruby
3.times do |number|
  let("player_#{number + 1}".to_sym) (double :player, method1: true, method2: false)
end
```
Something like ^^^ should work. ;-)

**Comment by saratateno** [comment]
Thanks @ptolemybarnes!
