### ISSUE TITLE
Rails - Where should validation be implemented?

### ISSUE THREAD

**Issue by timoxman** [makersacademy/slack-overflow#15]
We are trying to add validation to our Yelp-clone in Rails.

In the View we will add a condition so that the link is not available if it is not valid to be selected?
Is this all that should be added? or should there be more?

https://github.com/makersacademy/course/blob/master/bookmark_manager/bookmark_manager_stage_5.md
The link above suggests we should also add validation at the Model level.
Should we do this?
If we should we do validation at this level we do not have access to the data to allow us to do the validation within the model, if we need to do validation at this level how do we get access to other parts of the current state to allow us to do this validation?

**Comment by tansaku** [comment]
hi @timoxman can you clarify what you are trying to validate, i.e. which model for which field etc.

Are you trying to validate that an edit of a restaurant is being done by a particular user?  I think we will need more information to assess ...

maybe paste some code snippets to indicate precisely what you mean

**Comment by timoxman** [comment]
The question is quite generic. I am trying to determine what is good design:
My rails app is made up of a View, controller and model:
View - add validation (or stop the user being able to carry out the process) - definitely, we agree something is required here.
Controller - should not contain business logic - so no validation should go here.
Model - Validation here? (our further understanding makes us think validation should be here), but as I  say above things like "current_user" supplied by devise is not available at the model level. And we don't explicitly define the method which does the updating so do not understand how we can add validation at this level.

**Comment by tansaku** [comment]
Even if your question is very generic @timoxman it's absolutely critical that you provide specific code examples when requested.  I can't stress this enough.  I'll be happy to discuss in more detail when you post a link to your repo

**Comment by silvabox** [comment]
Although this is a conceptual issue, i'll elucidate:

There are many levels of validation, checks and many types.

## Business logic validation
> e.g. 
- _name_ is required.
-  user cannot delete a restaurant they didn't create

- This *must* happen on the persistence level (i.e. database) if it is a data integrity rule.
- It *should* also happen in the model (e.g. with validations)
- It *can* also happen on the client (e.g. with javascript)
- it can also be integrated with the UI (e.g. not displaying a Delete button)

## Access control/ security
> e.g. user login

- This is typically the responsibility of the controller

**Comment by spike01** [comment]
Using a conditional to determine whether something is displayed or not on the page is all well and good from a UI/UX perspective, but does not count as validation - anyone with knowledge of the underlying route could still send a request with the correct params. So you'd need something more, as Ben has explained above

**Comment by ptolemybarnes** [comment]
Ben and I have just been discussing this and came up with the following implementation: 

We have users who have many restaurants, and we want to ensure that only the user who created a restaurant can destroy it. 

```ruby
# /app/controllers/restaurants_controller.rb

def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.destroy_as current_user
      flash[:notice] = 'Restaurant deleted successfully'
    else
      flash.notice = "Error: you are not the author of the entry for #{@restaurant.name}"
    end
    redirect_to restaurants_path
  end
end
```

```ruby
# /app/models/restaurant.rb

def destroy_as(user)
    return false unless self.user == user
    destroy
    true
  end

```

**Comment by spike01** [comment]
And a little light refactor (destroy will return a non-falsey value if it succeeds, and false if it doesn't):

```ruby
def destroy_as(user)
  return if self.user != user
  destroy
end
```

**Comment by sjmog** [comment]
Funky question @silvabox @ptolemybarnes , but is it sensible to couple validation and action so closely together here?

E.g. what if the user _is_ the associated User record, but there is some other error when destroying?

Then the error displayed will not represent the error that occurs.

I feel like a filter function makes more sense e.g.

```
def destroy
  restaurant = Restaurant.find(params[:id])
  redirect_to restaurants_path, :flash => { :error => "You must be the owner of the restaurant to do that!" } unless restaurant.destroy_as user
  if restaurant.destroy
    flash[:notice] = "Restaurant deleted successfully"
  else
    flash[:notice] = restaurant.errors
  end
  redirect_to restaurants_path
end

# In Restaurant

def check_destroy_as
```

**Comment by ptolemybarnes** [comment]
Ya looks like :+1:

**Comment by sjmog** [comment]
Or maybe neater (pushing logic to the model):

```ruby
def destroy_as(user)
  if self.user == user
    destroy
  else
    self.errors.add(:user, "must be associated record")
    return
  end
end
```

**Comment by sjmog** [comment]
Then in the controller, much as you did:

```ruby
# /app/controllers/restaurants_controller.rb

def destroy
  restaurant = Restaurant.find(params[:id])
  if restaurant.destroy_as current_user
    flash[:notice] = 'Restaurant deleted successfully'
  else
    flash[:error] = restaurant.errors # You'll need to handle getting this gracefully into the hash e.g. as a <ul>
  end
  redirect_to restaurants_path
end
```

**Comment by ptolemybarnes** [comment]
@timoxman What do you think?

**Comment by silvabox** [comment]
Nearly.
```
def created_by?(user)
  self.user == user
end

def destroy_as(user)
  unless created_by? user
    errors.add(:user, 'cannot delete this restaurant')
    return false
  end

  destroy
end
```

**Comment by ptolemybarnes** [comment]
You were so close @silvabox, but Spike doesn't like explicit return of booleans:
```ruby
def created_by?(user)
  self.user == user
end

def destroy_as(user)
  unless created_by? user
    errors.add(:user, 'cannot delete this restaurant')
    return
  end

  destroy
end
```

**Comment by spike01** [comment]
No, that's ok because you're not returning the result of an equality comparison - I'm against `return true if foo == bar`, or `destroy; true` because you lose the benefit that Rails will return false or an error if there is a problem with `destroy`

**Comment by ptolemybarnes** [comment]
I'm closing this issue. :imp:

**Comment by timoxman** [comment]
Thanks for the feedback and discussion on this subject, some interesting points raised. If a little late for me and yelp.. but hope this repository of answer becomes searchable for others in future.. Thanks
