### ISSUE TITLE
Unable to run karma for angular in a rails app

### ISSUE THREAD

**Issue by d9nny** [makersacademy/slack-overflow#150]
Hi we are using Angular with rails for our final project and we are having trouble getting karma to find our tests. We have a test in spec/javascripts/angular/controllers/indexController.spec.js with the controller in app/assets/javascripts/angular/controllers/indexController.js. The error we get is:

TypeError: 'undefined' is not an object (evaluating 'parentWindow.io.sockets[hostname]')

Below is a link to our repo:

https://github.com/jrose111284/Auto-pair/tree/%2324-creating-view

Any help would be much appreciated.

Cheers

**Comment by tansaku** [comment]
hi d9nny is this still an issue?  What command are you running to get that error?

**Comment by d9nny** [comment]
We first tried to run it through rails using a rake command: bundle exec rake karma:start

and then we tried: karma start spec/karma/config/karma.conf.js.

We did some research last night and were going to talk about it at 9:30, so maybe if we haven't solved it after that we could give you a shout?

**Comment by tansaku** [comment]
@d9nny have you run this successfully using the github example? 

https://github.com/mikamai/angular-rails-example

I would check that that works first before trying with your own code and tests.  If it doesn't work file an issue on that repo.  If it does work then file an issue on that repo with your current problem

**Comment by DeathRay1977** [comment]
The problem was in the karma.conf.js and where it was looking for files. This can now be closed.
