### ISSUE TITLE
Capybara::ElementNotFound error in Ruby sinatra project

### ISSUE THREAD

**Issue by christopheralcock** [makersacademy/slack-overflow#153]
Merry Christmas, one and all.

Having Capybara problems again.  Have googled but all of the solutions seem to be rails specific.  Basically Capybara is not finding the field I want it to fill in, despite me giving it a "name" attribute which I would think would work.

Here is a repo link: 
https://github.com/christopheralcock/lyric-writer

Error message:
```
Scenario: submitting a phrase                          # features/submitting-phrases.feature:10
    Given I have entered the phrase "banked on memories" # features/step_definitions/web_steps.rb:145
      Unable to find field "phrase" (Capybara::ElementNotFound)
      ./features/step_definitions/web_steps.rb:146:in `/^I have entered the phrase "([^"]*)"$/'
      features/submitting-phrases.feature:11:in `Given I have entered the phrase "banked on memories"'
```

Googling suggests that the issue might be to do with the field in question, "phrase", being inside a view?  Some suggestions included interpolating the name of the view into the capybara command.

Currently it's `fill_in "phrase", with: arg1`
and looking in `<input type="text" name="phrase" placeholder="eg. I was born under a wandering star">` inside `app/views/index.erb`

Have tried changing "phrase" to "index_phrase", "phase_index", "index[phrase]", "[index]phrase" per some suggestions.

Thanks for reading and happy break to you all
Chris

**Comment by spike01** [comment]
You haven't navigated to the page!

**Comment by christopheralcock** [comment]
hhahahahahaha
thanks and merry christmas!

**Comment by ptolemybarnes** [comment]
As an aside, when Capybara seems to be misbehaving it always helps to do a `save_and_open_page` to check that what you think it's looking at is really what it's looking at.

**Comment by christopheralcock** [comment]
@ptolemybarnes ta, will do
