### ISSUE TITLE
Bookmark Manager: Reset password token generation

### ISSUE THREAD

**Issue by emmabeynon** [makersacademy/slack-overflow#154]
Hi guys,
I've having trouble generating a password token when a user tries to recover their password.  I've had a look at the code with byebug, and the user seems to be found and the token generated:
![image](https://cloud.githubusercontent.com/assets/13434452/12079070/0b5c4d48-b223-11e5-8d05-3a15533cf9e3.png)

However when I run my tests, or look in the database, the token has not been generated:
![image](https://cloud.githubusercontent.com/assets/13434452/12079049/e5448210-b222-11e5-8d51-f5307d0f6ba1.png)

![image](https://cloud.githubusercontent.com/assets/13434452/12079048/d16904f0-b222-11e5-91be-735033f26ac9.png)

I'm pretty stumped.  Any ideas or pointers in the right direction gratefully received!
Controller: https://github.com/emmabeynon/bookmark-manager/blob/master/app/controllers/users.rb
Model: https://github.com/emmabeynon/bookmark-manager/blob/master/app%2Fmodels%2Fuser.rb

Cheers,
Emma

**Comment by ptolemybarnes** [comment]
Hi @emmabeynon, had a long look at this and also went round in circles for awhile. I eventually noticed that, inspecting the user instance within the controller, I could see:

```
#<DataMapper::Validations::ValidationErrors:0x007f8c160b8bd8 @resource=#<User @id=1 @name="Blah Blah" @email="blah@blah.com" @password_digest="$2a$10$BYlqLdWfKyVTUL5UoNzKrOPcerjwVIeZPNw/lnLoxJcbWAu46KXle" @password_token="388f77301048cb2cff3b84cbdcb174c9" @password_token_time=2016-01-03 20:01:45 +0000>, @errors={:password=>[nil]}>
```
That on the errors it shows `{:password=>[nil]}`. 

I had a look at your User class and deleted the following line: `validates_with_method :password` and the test passwed :-) 

I'm not familiar with that bit of DM syntax so not sure what it's being used for. I guess that in your `generate_token` method it's attempting to save the user but failing on that validation.

Thanks for outlining your problem so clearly.

**Comment by emmabeynon** [comment]
That works - thanks @ptolemybarnes !
