### ISSUE TITLE
MongoDB: aborting after invariant failure

### ISSUE THREAD

**Issue by edwardkerry** [makersacademy/slack-overflow#155]
I have attempted to install Mongo using brew and manually. On launch using `$mongod`, MongoDB exits with  
`Invariant failure: ret resulted in status UnknownError 2: No such file or directory at src/mongo/db/storage/wiredtiger/wiredtiger_size_storer.cpp 67`

Prior to this stage I had received other issues regarding folder permissions, but was able to resolve these. The issue persists after removing and re-installing mongo.

**Comment by ptolemybarnes** [comment]
Had a look at this with @edwardkerry but no joy. Not sure where `src/mongo/db/storage/wiredtiger` is referring to.

**Comment by edwardkerry** [comment]
Problem solved (or avoided) by `brew uninstall mongoDB`, removing /data/db, and then rerunning brew install, and creating new /data/db folders with appropriate ownership/permissions.
