### ISSUE TITLE
OmniAuth authenticating but not functioning when redirected back.

### ISSUE THREAD

**Issue by jamiebrown201** [makersacademy/slack-overflow#157]
We have set up the OmniAuth Facebook log in and when we sign in through Facebook it redirects back to the sign up page (rather than the root) with the sign in and sign up buttons still there (when it should be just be sign out). 

There are a couple of us with this issue and a couple of us(who from what we can see) have done exactly the same thing and it is working. 

I have tried printing the params after facebook sign in and they are:

```Parameters: {"authenticity_token"=>"EtMWy55BtbuLeQhS+UeauPqx1iNA6redUZf4mbEpL43xPPjv0OE/E/Z9AqlgFOrSAj7pK30qyELUIS8mq69avg=="}```

When we sign in manually without facebook(which works as it should):
 ``` Parameters: {"utf8"=>"✓", "authenticity_token"=>"0elNi4wOSbvoDWCnR5890LXGhbjaEYYWm1m7M6P5rVDisC6UT9uuaf8gq1I9Tunr2Uxuu97QFbzpF9zL4KU9WA==", "user"=>{"email"=>"a@a.com", "password"=>"[FILTERED]", " ```

In terms of posting the code here we aren't getting any errors and the code created whit OmniAuth is extensive. Let me know if you would like to see anything specific.

**Comment by silvabox** [comment]
Can you please post a link to your repo, or some code examples?  Also, can we see the Facebook application settings?

**Comment by sdorunga1** [comment]
You might want to check what fields your session creation code is actually looking for.

**Comment by jamiebrown201** [comment]
Here is one of the repos:

https://github.com/gareth4192/Rails/tree/master/yelp_clone

![alt text](http://i.imgur.com/k1XUZKs.png "issue")

**Comment by timhyson** [comment]
Have you seen the troubleshooting section of the devise Omniauth docs?  https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#facebook-returning-nulled-email
You might need to add ```info_fields``` to your ```config.omiauth``` to return the necessary fields

**Comment by jamiebrown201** [comment]
I tried going through the trouble shooting on my repo and so has @Htunny 

(Cant post as our repos as we have not yet hidden our facebooks keys)

**Comment by silvabox** [comment]
Check your redirect uri in Facebook.  It's currently redirecting to the root path...

**Comment by jamiebrown201** [comment]
Thankyou guys Leo helped us find out that it all depends on your privacy settings on facebook. Mine were set not to return a email so was not authenticating.
