### ISSUE TITLE
random weather stubs

### ISSUE THREAD

**Issue by heather-camcam** [makersacademy/slack-overflow#158]
Hello all, 

Have been going round in circles with the below. Trying to use stubs in my rspec to test that I'm getting the correct behaviour when weather is good/bad however, my rspec tests are randomly passing/failing which makes me think that the stubs are working correctly. Any ideas?

```
require_relative 'plane'

class Airport

  attr_reader :landed_planes

  def initialize
    @landed_planes = []
  end

  def land(plane)
    raise 'Cannot land due to stormy weather' if weather_conditions < 3
    landed_planes << plane
  end

  def take_off(plane)
    raise 'Cannot take off due to stormy weather' if weather_conditions < 3
    departing_flights = []
    departing_flights << plane
    landed_planes.delete plane
  end

  def weather_conditions
    rand(10)
  end

end
```

```
require 'airport'
require 'weather'

describe Airport do

  subject(:airport) { described_class.new }
  let(:plane) { double :plane }
  let(:weather) { double :weather }

  describe '#landing' do

    it 'instruct plane to land' do
      expect(airport).to respond_to(:land).with(1).argument
    end

    it 'confirm that plane has landed' do
      allow(plane).to receive(:land)
      allow(weather).to receive(:weather_conditions).and_return(8) #<--randomly passing/failing
      airport.land(plane)
      expect(airport.landed_planes).to include plane
    end

  end

  describe '#take off' do

    it 'instruct plane to takeoff' do
      expect(airport).to respond_to(:take_off).with(1).argument
    end

    it 'confirm plane is no longer in the airport' do
      allow(plane).to receive(:land)
      allow(plane).to receive(:take_off)
      allow(weather).to receive(:weather_conditions).and_return(8)#<--randomly passing/failing
      expect(airport.landed_planes).not_to include plane
    end

  end

  context 'bad weather' do

    it 'prevents take off when weather is stormy' do
      allow(weather).to receive(:weather_conditions).and_return(1)#<--randomly passing/failing
      expect{airport.take_off(plane)}.to raise_error 'Cannot take off due to stormy weather'
    end

    it 'prevents landing when weather is stormy' do
      allow(weather).to receive(:weather_conditions).and_return(1)#<--randomly passing/failing
      expect{airport.land(plane)}.to raise_error 'Cannot land due to stormy weather'
    end

  end

end
```

**Comment by mic-css** [comment]
Hey Heather :)

Looks to me like your `Airport` class is fine, but in your spec you're treating `weather` like a class of it's own: you have a `:weather` double and are calling `#weather_conditions` on it, but there is actually no weather object.

Instead you want to `allow(airport).to receive(:weather_conditions).and_return(1)` (or whatever other number) because `#weather_conditions` is an Airport method.

PS. `subject(:airport) { described_class.new }` is redundant, you can just write `subject { described_class.new }` and then refer to your airport as subject throughout the tests ;)

**Comment by silvabox** [comment]
@mic-css we encourage aliasing `subject` (i.e. `subject(:airport)`) as it makes the test more readable.

**Comment by heather-camcam** [comment]
:+1: this is excellent - thank you!

guess my whole weather class is actually pretty redundant in which case.

**Comment by silvabox** [comment]
...or perhaps not...

**Comment by mic-css** [comment]
@silvabox great to know, thanks! @heather-camcam with regards to the slack discussion sounds like you had the right idea with the Weather class, so reconsider how you're implementing `Airport#weather_conditions` and make sure your Airport object is aware of the Weather object
