### ISSUE TITLE
Can't Define Singleton Rspec Error Message

### ISSUE THREAD

**Issue by Triffanys101** [makersacademy/slack-overflow#16]
When creating our battleship we encounter this failing rspec error:

```
Player fire at ships allows the player to fire at the board
     Failure/Error: allow(:board).to receive :shoot_at
     TypeError:
       can't define singleton
     # ./spec/player_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 0.01335 seconds (files took 0.08911 seconds to load)
13 examples, 1 failure
```

This is the test:

```ruby
describe 'fire at ships' do
   it 'allows the player to fire at the board' do
      subject.place ship
      expect(board).to receive :shoot_at
      subject.fire 'B2'
   end
end
```

What is a singleton? And why is it struggling to be defined?

**Comment by tansaku** [comment]
Hi @Triffanys101 great work posting this - notice how I have edited your post to make the code format correctly.

Some other tips on question posting - always always always post a link to your repo, and also when you are closing the issue ensure to add a description of how you fixed it.  I'll be happy to do a break out on effective online question asking at some point - it's an absolutely crucial skill for a developer :-)
