### ISSUE TITLE
Airport_Challenge. rspec test fails when trying to raise an error, is it correctly implemented?

### ISSUE THREAD

**Issue by reissjohnson** [makersacademy/slack-overflow#160]
Hi guys, I wrote an rspec test that checks if an airport has no longer has an available slot for a plane....

![screen shot 2016-01-24 at 17 35 47](https://cloud.githubusercontent.com/assets/13954936/12537813/f008d8be-c2c0-11e5-9db0-06fa07535371.png)

I refactored my code expecting it to get the test to pass... this is within my land method.

![screen shot 2016-01-24 at 17 37 32](https://cloud.githubusercontent.com/assets/13954936/12537844/b8ad8102-c2c1-11e5-85fb-512788242f19.png)

except I still get the following error? 

![screen shot 2016-01-24 at 17 38 25](https://cloud.githubusercontent.com/assets/13954936/12537825/52eb1ef6-c2c1-11e5-8c9a-10ffb7b68db1.png)

I was quite happy up to this point and I was looking forward to solving this test and then simplifying my code :/ 

The feature passes in IRB so im a bit confused, then again I was doing this untill 4am this morning and then from 11 today... 😂😂😂😂

can anybody shed any light? Maybe i'm missing something obvious...

**Comment by reissjohnson** [comment]
also, i'm going to get round to implementing weather as a class. I'd just like to get everything working before I do...

**Comment by chweeks** [comment]
I think it may be becuase your stubbing airport.capacity to equal 0 but in your method you use @capactity. Also to get rid of those depreciation warnings use this allow syntax rather than stub. allow(obj).to receive(:message).and_return(:value)

**Comment by reissjohnson** [comment]
@chweeks cheers buddy, this helped!
