### ISSUE TITLE
"ArgumentError: rack-test requires a rack application, but none was given"

### ISSUE THREAD

**Issue by russellvaughan** [makersacademy/slack-overflow#163]
Hello All,

We are currently working through the Battles challenge in the Intro-to-the-web repo and have hit a roadblock when trying to rspec our first feature test : 

We get the following error:

"ArgumentError: rack-test requires a rack application, but none was given"

All the details have been posted to stackoverflow and can be found here: 

http://stackoverflow.com/questions/35174682/sinatra-rspec-capybara-rack-test-requires-a-rack-application

Any help would be massively appreciated. 

Thanks,

Russ

**Comment by thisdotrob** [comment]
Have you got a .rspec file with `--require spec_helper` in it?

Everything else looks okay to me.

You could try a `bundle clean --force` followed by a `bundle install`

**Comment by russellvaughan** [comment]
The bundle clean --force worked! thank you!

**Comment by Chloeem** [comment]
Just to clarify, a couple of us on the August 2021 cohort followed these steps after getting the same error message on week 3. Only for it to remove a load of our Gemfiles and consequentially have to reinstall them all.
