### ISSUE TITLE
name instance variable not coming through to view

### ISSUE THREAD

**Issue by heather-camcam** [makersacademy/slack-overflow#166]
Hello, hoping someone can help point out what's going wrong with the following:

My rspec feature test is failing as appears my 'player_name' instance variable is not coming through to the associated view page. 

I'm getting the following error:

`Failure/Error: expect(page).to have_content 'Heather vs. THE COMPUTER'
       expected to find text "Heather vs. THE COMPUTER" in "# vs. THE COMPUTER"`

#app.rb 
``````
require 'sinatra/base'
require './lib/player'

class RPS < Sinatra::Base
  enable :sessions

  get '/' do
    erb :index
  end

  post '/player-name' do
    $player_name = Player.new(params[:player_name])
    erb :play_confirmation
  end

  get '/play' do
    @player_name = $player_name.name
    erb :play_game
  end

  get '/fight' do
    erb :fight
  end

  # start the server if ruby file executed directly
  run! if app_file == $0
end
``````

#play_confirmation.erb
```
<h1 align="center"> <%=@player_name%> vs. THE COMPUTER </h1>

<form action="/play">
    <input type='submit' value='Play now'>
</form>
```

**Comment by esbaddeley** [comment]
Hi Heather - i think it's because in your play_confirmation.erb view you're calling the instance variable, but in the post '/player_name' route where this view is rendered, you haven't set up this instance variable @player_name, this isn't declared until the get '/play' route. You could either also declare this instance variable in your post '/player_name' route, or refer directly to the $player_name global variable in the view.

**Comment by ggwc82** [comment]
`post '/player-name' do
    $player_name = Player.new(params[:player_name])
    erb :play_confirmation
  end
`
Shouldn't that be an instance variable there instead of a global one? Change that and I think it should work

**Comment by heather-camcam** [comment]
Thanks both. My main issue was actually that I had duplicate versions of my view files as a result of reorganising my file structure. 

Additionally, I added a redirect to a new get route in order to define my instance variable. 

FYI if you're interested: 

```
post '/player-name' do
    $player_name = Player.new(params[:player_name])
    redirect '/play_confirmation'
  end

  get '/play_confirmation' do
    @player_name = $player_name.name
    erb :play_confirmation
  end

  get '/play' do
    @player_name = $player_name.name
    erb :play_game
  end

```
