### ISSUE TITLE
chall 10 Bookmark_manager STUCK!

### ISSUE THREAD

**Issue by hedudelgado** [makersacademy/slack-overflow#169]
I completed challenge 9, starting the 10 everything is normal, the right error at that point, and then once I finished the challenge 10, it all should be working, in addition I did follow the solution step by step, still, not working.. any clue? 

## This is my app.rb
```
require 'sinatra/base'
require_relative 'models/link'
#require 'tilt/erb'
```
```
class BookmarkManager < Sinatra::Base
  get '/links' do
    @links = Link.all
    erb :'links/index'
  end
  #run! if app_file == $0
end
```

## this is my link class 
```
require 'data_mapper'
require 'dm-postgres-adapter'
```
```
class Link
  include DataMapper::Resource
  property :id,     Serial 
  property :title,  String
  property :url,    String
end
```
```
DataMapper.setup(:default, "postgres://localhost/bookmark_manager_test")
DataMapper.finalize
DataMapper.auto_upgrade!
```

## this is my spec_helper:
```
Require 'capybara/rspec'
require './app/app'
require './app/models/link'
Capybara.app = BookmarkManager
```
```

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```
## this is my error..

Failures:

  1) Viewing links I can see existing links on the links page
     Failure/Error: expect(page.status_code).to eq 200
     
       expected: 200
            got: 404
     
       (compared using ==)
     # ./spec/viewing_links_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.18148 seconds (files took 1.04 seconds to load)
1 example, 1 failure

**Comment by arnoldmanzano** [comment]
File directory structure?
Where is your app.rb located?
How about your views directory?

**Comment by hedudelgado** [comment]
app      models    link.rb
            app.rb
-----------------------------
views    links    index.rb

**Comment by silvabox** [comment]
Can you post a link to your repo please?

**Comment by hedudelgado** [comment]
Thanks for your help, hopefully you will the splinter :).. its killing me.
https://github.com/hedudelgado/bookmark_manager

**Comment by arnoldmanzano** [comment]
Put your views inside app directory. That should work i think.

**Comment by hedudelgado** [comment]
It does not arnold, I think it would actually break the structure, wouldn't it? I mean, I have to keep an standard structure isnt it?

**Comment by hedudelgado** [comment]
Thanks for you help, problem solved.
