### ISSUE TITLE
Rspec doubles issue with takeaway challenge

### ISSUE THREAD

**Issue by lroliphant** [makersacademy/slack-overflow#17]
I am having trouble describing the exact issue, although it is possible that there are multiple issues - I have attached a screenshot of the rspec message I am getting that relates to doubles, and the link to the bugs branch of my takeaway challenge repo can be found here:
https://github.com/lroliphant/takeaway-challenge/tree/bugs

Although the primary issue I have been having seems to be that I cannot access the takeaway_menu as a hash, instead I am getting an object and I cannot seem to access the hash within that object, or I cannot figure out how to at least. So I cannot use hash methods such as include? on it. I am assuming this as when I test in irb I get the following message:

order.takeaway_menu.include?('vege roll')
NoMethodError: undefined method `include?' for #<Menu:0x007fec04023210>

And I think this or possibly setting up the doubles incorrectly may be the root of all my issues.

![screen shot 2015-06-21 at 15 25 27](https://cloud.githubusercontent.com/assets/10765164/8272015/dd6d636e-182a-11e5-8cda-f44294534679.png)

Apologies in advance if I have not explained the issue very well.

**Comment by FaisalChoura** [comment]
Hi Lucy,
The error in the message states that you defined a double but did not add an include? method for it.
to fix this error message try
```let(:menu) {double :menu, include?: what ever you want it to return}```
and add other methods to that as well.

what is the takeaway_menu ? method or a variable ?

**Comment by lroliphant** [comment]
Currently takeaway_menu is quite a few things - an attr_reader and an instance variable and a variable set on the initialize method, I think it's all a bit of a mess, so I am going to try another route and start again. Thanks for your help
