### ISSUE TITLE
PostgreSQL installation issues

### ISSUE THREAD

**Issue by Finble** [makersacademy/slack-overflow#170]
Ran brew install postgresql (to check I had it) - returned following error:

Warning: postgresql-9.4.5_2 already installed, it's just not linked'  

Found this: http://stackoverflow.com/questions/25075888/brew-install-postgresql-upgrade-error-could-not-link-dead-links-to-old-non

However, when I run brew update, it returns: You should probably change the ownership and permissions of /usr/local back to your user account.

I think it's a deadlinks issue?  A bit nervous to play around with this as seen warnings re messing system if you're a novice (...!).  Any help appreciated.

**Comment by sjmog** [comment]
Did you manage to solve this @Finble ? Postgres installation can be the devil

**Comment by sjmog** [comment]
`brew doctor` is my first goto for any Brew problems.

**Comment by Finble** [comment]
No - no solution...  Trying to run Brew, but it is saying my permissions have changed - trying to change that now, but feel a bit out of my depth.  Same with bash profile (albeit Leo said he would help with that later), although I still haven't sorted makers init, so wondering if this is a combo opportunity for you/one of the coaches, to walk me through?  Particularly as all have warning messages re potential to screw up environment....  Would really appreciate it...

**Comment by ptolemybarnes** [comment]
Do you just need to link postgres? `brew link postgres`

**Comment by Finble** [comment]
Elaines-MacBook-Pro:Week_4 elainefinn$ brew link postgres
Linking /usr/local/Cellar/postgresql/9.4.5_2... 
Error: Could not symlink share/man/man3/SPI_connect.3
/usr/local/share/man/man3 is not writable.

**Comment by Finble** [comment]
Huge thanks to Leo...!!  1.  Brew couldn't write any directories, so had to change permissions to enable this.  2.  Followed this (but had to adjust for sudo command as Brew somehow doesn't need it!):  http://stackoverflow.com/questions/27700596/homebrew-postgres-broken
