### ISSUE TITLE
Many tests vs. One giant regex test

### ISSUE THREAD

**Issue by djtango** [makersacademy/slack-overflow#171]
Hello :)

I am writing feature tests to check that content has been successfully retrieved from the data base. 

There are two options I can think of (code below, _tl;dr which do you prefer?_):

1. Have two sets of test blocks, each containing a series of assertions. These match for the relevant prices and menu item names. This is instantly readable, but is highly repetitive and cannot easily test for things like prices corresponding to the right menu item, nor can it account for the edge cases like the same price featuring in a given menu.

2. I can write a giant regex that follows the structure: "_menu_item_name1_..._menu_item_price1_..._menu_item_name2_..._menu_item_price2_..." etc. This is less readable, but comes under one assertion, and has better test coverage.

`(:body @response)` evaluates to the raw HTML string served when loading the page.
Code:

```
;;;Option 1
(it "Full menu content is displayed correctly"
  (should-contain "Chicken & Bacon Ranch Melt"  (:body @response))
  (should-contain "SUBWAY MELT"                 (:body @response))
  (should-contain "Steak & Cheese"              (:body @response))
  (should-contain "Veggie Patty"                (:body @response))
  (should-contain "Meatball Marinara"           (:body @response))
  (should-contain "Italian B.M.T."              (:body @response)))
(it "Prices are displayed correctly"
  (should-contain "2.99"                        (:body @response))
  (should-contain "3.15"                        (:body @response))
  (should-contain "3.55"                        (:body @response))
  (should-contain "3.99"                        (:body @response))
  (should-contain "3.99"                        (:body @response))
  (should-contain "4.20"                        (:body @response)))

;;;Option 2
(it "Menu contents correctly retrieved and prices correctly assigned"
  (should= 1 (match-count
    #"Chicken\s&\sBacon\sRanch\sMelt.*2\.99.*SUBWAY\sMELT.*3\.15.*Steak\s&\sCheese.*3\.55.*Veggie\sPatty.*3\.99.*Meatball\sMarinara.*3\.99.*Italian\sB\.M\.T\..*4\.20"
    (:body @response))))))
```

Alternatively could some kind of iterative/recursive function that loops through all possible menu item/price pairings be constructed? (e.g. I envisage some mega assertion `(should= true F)` wrapping a function, `F`, that is a map-reduce of individual assertions.

**Comment by thisdotrob** [comment]
Could you create a collection of menu items incl. prices (being a regex for each), then iterate over it and make the assertion 'should= 1 match count' for each one? Maybe move the collection of menu items to a seperate helper / fixtures file? 

Otherwise I prefer the second one personally!

**Comment by ptolemybarnes** [comment]
Any test you write of this kind is likely to be brittle. Consider instead thoroughly unit testing the class/whatever that is responsible for retrieving the data from the db and having a light feature test.

http://martinfowler.com/bliki/TestPyramid.html

**Comment by djtango** [comment]
Completely true Ptolemy, this is what happens when you write tests after building the project and even more so when you start with feature tests instead of unit tests... >.> 

From a conceptual point, is there an argument for still writing this sort of test if the product should always display the full contents of the menu (i.e. names and prices)?

Also, is there a significance between feature testing by testing against the raw HTML and using a headless browser like Selenium to "interact" with the page?

**Comment by djtango** [comment]
re Rob, that's a good shout - will make it more readable too

**Comment by djtango** [comment]
Also how is London Style and Chicago Style interpreted in functional programming? If a function always returns the same value, are stubbing and mocking / modular testing as distinct from integration test?

**Comment by spike01** [comment]
Functional programming lends itself really well to London style - all of a functions dependencies are usually explicit as parameters, and since functions can be used as values, you can pass in a value or use a mock function at test point

**Comment by ptolemybarnes** [comment]
"From a conceptual point, is there an argument for still writing this sort of test if the product should always display the full contents of the menu (i.e. names and prices)?"
Maybe but even if it always displays the full contents of the menu it could still be v brittle.
