### ISSUE TITLE
WebAudio API - can't playback multiple times

### ISSUE THREAD

**Issue by saratateno** [makersacademy/slack-overflow#173]
Hi,

We've found a couple of drumkit sounds created using the WebAudio API. Has anyone got experience with it? For some reason, it won't let us play the same sound multiple times, even though we have a setup that generates a new oscillator each time the 'playKick' function is called. There's no error message and the console shows it is getting to the new oscillator each time. There's just no sound.

We found a (very bad) fudge way of making it do it a few more times by creating new AudioContext instances but obviously that's not right.. and the browser won't let you create more than 6 contexts anyway!

Thanks.

**Comment by JonnyPickard** [comment]
(From a music tech point of view) Not sure about the coding side of this but can't you just retrigger than same oscillator to oscillate instead of creating new ones? Also It could be maybe to do with where the output is going to.

**Comment by saratateno** [comment]
Apparently not - it does require a new oscillator every time.  But I think I've found a partial answer.. http://stackoverflow.com/questions/31033311/audiocontext-oscillator-wont-play-more-than-once

This seems to suggest that a new time argument needs to be passed in every time the 'kick' button is pressed.. Think we need to work out how to use Tone JS Transport to fix it!
