### ISSUE TITLE
 Heroku app error I was not expecting!

### ISSUE THREAD

**Issue by reissjohnson** [makersacademy/slack-overflow#174]
Me and Fareed are working on using our app up on Heroku challenge 14, checking the error logs we should be getting the error...

`2015-10-06T08:59:48.323229+00:00 app[web.1]:    TCP/IP connections on port 5432?`

But instead we are getting...

`2016-02-11T16:36:14.095347+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=book-manager-rj.herokuapp.com request_id=8c6e3515-06c1-43f1-9bd7-68ca3747ffbe fwd="81.108.19.26" dyno= connect= service= status=503 bytes=`

`2016-02-11T16:36:15.493847+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=book-manager-rj.herokuapp.com request_id=d7560330-5469-4a40-8517-249d38d6ee42 fwd="81.108.19.26" dyno= connect= service= status=503 bytes=`

This happened both before and after setting up the database & implementing it into the Link class. Bit of a head scratcher as I did this yesterday myself and it seemed to work fine ... :/

Any ideas?

**Comment by sjmog** [comment]
Nice question! Couple more questions:

- What's a `503` error?
- In a local environment you get a nice stack trace when the server has an error, because you've got development logging. Is there any way to view the Heroku logs?
- Once you've found them, what does your error say in the Heroku logs?

**Comment by reissjohnson** [comment]
@sjmog The above errors are straight out of the heroku logs? As in running heroku logs on the cli you mean? I've also ran heroku logs -t and it's registering the same error each time. Hmmm, we'll get there just a bit weird as I didn't get it yesterdizzle...

**Comment by sjmog** [comment]
And you've got some `puts` statements in there to track what's going on?

**Comment by reissjohnson** [comment]
@sjmog it was a combo of a few things, a dodgy require_relative & a ENV["RACK_ENV"]. I then added the database and it worked. I guess I was looking at the wrong park of the stack.... It just threw me because It was working locally but no on Heroku.  Maybe i've been lucky so far on the error front, better sort my debugging skills out! :)
