### ISSUE TITLE
Sign-up feature test scenario appears to skip the layout.erb file.

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/slack-overflow#177]
This keeps happening:

```
Failures:

  1) A new user signs up to Chitter The user enters their email address, password and confirmation
     Failure/Error: expect(page).to have_content("Welcome, Jeremy!")
       expected to find text "Welcome, Jeremy!" in "Welcome to Chitter!"
     # ./spec/features/user_sign_up_spec.rb:6:in `block (2 levels) in <top (required)>'
```
When the layout.erb file is clearly there:
```
Jeremys-MacBook-Pro:chitter-challenge jeremybarrass$ ls app/views
home.erb	layout.erb	signup.erb
```
Looking like this:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
  </head>

  <body>
    <% if current_user %>
      <h2>Welcome, <%= current_user.name %>!</h2>
    <% end %>

    <% if flash[:errors] %>
      <div id='notice'><%= flash[:errors] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>
```
But for some reason, the test is only reading from the start of the home.erb file:
```
<h1>Welcome to Chitter!</h1>

<form action='/home/sign-up'>
  <input type='submit' value="Sign up">
</form>
<form action="/home/log-in">
  <input type='submit' value="Log in">
</form>
```
The controller is doing all the right things, as far as I can tell.  This still the first user story, so I haven't done posts yet:
```
  get '/home' do
    erb :home
  end
```

Can anyone spot where I'm going wrong?  I've been looking for the last two hours and can't see it.

**Comment by seanhawkridge** [comment]
How is your `current_user` set? To check it's actually an issue with layout.erb, you could hard-code your name in there instead of your conditional `if current_user` and see if the test passes. If it does, it's more likely to be an issue with sessions/the `@current_user` instance variable I think.

**Comment by Jeremy-Barrass** [comment]
Oh, and in case it's relevant, the `Post` from the sign-up page is doing this:
```
  post '/home/sign-up' do
    @user = User.create(name: params[:name],
                        username: params[:username],
                        email: params[:email],
                        password: params[:password],
                        password_confirmation: params[:confirm_password])
    if @user.save
      session[:user_id] = @user.id
      redirect '/home'
    else
      flash.now[:errors] = "Password and confirmation password don't match"
      erb :signup
    end
  end
```
Thanks Sean, hard coded my name into the layout page (`<h2>Welcome, Jeremy<!-- <%= current_user.name %> -->!</h2>`) and it still failed, which I guess is interesting in terms of narrowing down the problem.  

Current_user is doing this from inside a helper block, in case that might be relevant:
```
    def current_user
      @current_user ||= User.get(session[:user_id])
    end
```

**Comment by eilw** [comment]
Jeremey, try writing something outside of your ```<% if current_user %>``` block.

**Comment by djtango** [comment]
Without seeing all the code, it's hard to tell so can only give more general advice: if the trace in your test is reading from `home.erb` but you want to be reading `layout.erb` then it seems the test never arrived where you expected it to. 

Sean was right to suggest hard coding the data as a means of eliminating one cause of the problem - the findings there further suggest that something isn't going as you expected in your tests. 

If you can't work out your problem, I could suggest either starting this suite of tests again (not as scary or time consuming as it sounds) or trying to rewrite your tests as smaller individual chunks (think how you started with `expect.to respond_to(:method)` when you got started with Boris bikes). Get the tests passing then you can always redactor later.

**Comment by Jeremy-Barrass** [comment]
Moved the `<h2>` tag, still written as above, outside the `if` block, and it broke everything, complaining:
```
NoMethodError:
       undefined method `name' for nil:NilClass
```
Which I guess means the '@current_user' isn't persisting between views...?  Or the method is not being picked up by the layout view...  Trying to call the instance variable directly doesn't fix anything either, but getting rid of `current_user.name` outside the `if` block does.  So it's definitely something to do with current_user not being read by the layout.

Thanks for all the help so far everyone, I'll try rolling back the test a bit to see if I can isolate the error further.

**Comment by silvabox** [comment]
@Jeremy-Barrass post a link to your repo - I'll take a look

**Comment by Jeremy-Barrass** [comment]
Thanks Ben.

Here is the link to my repo, updated with the failing test: https://github.com/Jeremy-Barrass/chitter-challenge

**Comment by silvabox** [comment]
There's no layout file?

**Comment by Jeremy-Barrass** [comment]
...But...it was staged at the last commit...or so I thought.  Anyway, added now.

**Comment by silvabox** [comment]
It's working for me locally!

**Comment by silvabox** [comment]
No, wait, it's not - I didn't realize you'd hard coded Jeremy into the view.  Bad boy.

**Comment by Jeremy-Barrass** [comment]
I've given up.  Although my authenticate tests are directly contradicting themselves, so...

**Comment by Jeremy-Barrass** [comment]
Still, at least the user xp test is showing the NoMethodError as well.

**Comment by Jeremy-Barrass** [comment]
Sorry about the hard coding, btw. :S  It was mostly to test if the expect was picking up anything - it is from outside of the if block, when I remove the name call to current_user.

**Comment by Jeremy-Barrass** [comment]
Well despite all the feature and code test failures, ux appears flawless.

**Comment by Jeremy-Barrass** [comment]
Turned out I hadn't auto-migrated...
