### ISSUE TITLE
Issues with sessions

### ISSUE THREAD

**Issue by drjparry** [makersacademy/slack-overflow#178]
I thought I understood sessions but apparently I don't. Been stuck on this for hours and just don't get it. Can someone tell me what's going wrong here pls??? The issue is that i do this when someone signs up..
"session[:name] = @user.name"
... so that i can welcome the user personally. great. but then when the user logs in, because i send him to the home page as well, i again do 
"session[:name] = @user.name"
...and it works at the time (when i puts out) but when i redirect home, session[:name] is suddenly nil. how is that possible? How can it just forget? It's sessions!
It also happens when i set the ID and try to use it later. How does redirect make sessions forget it's values?? There is no prob with the directions etc. either. it's really a sessions issue. 
I had installed shotgun and thought that may have been a problem so i deleted it and uninstalled (which has now given me heroku probs but that's another story...) 
If anyone can answer it would be great. Thanks. Here is the code 

```
ENV["RACK_ENV"] ||= "development"

require 'sinatra/base'
require 'sinatra/flash'
require_relative 'models/user'
require_relative 'models/post'
require_relative 'data_mapper_setup'


class Chitter < Sinatra::Base
  enable :sessions
  register Sinatra::Flash
  use Rack::MethodOverride

  get '/' do
    redirect '/home'
  end

  get '/home' do
    @current_user = session[:name]
    @posts = Post.all
    erb :home_page

  end

  get '/sign_up' do
    erb :sign_up
  end

  post '/sign_up' do
    @user = User.new(name: params[:name], username: params[:username], email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation])
    if @user.save
        session[:name] = @user.name
        redirect '/home'
    else
      flash.now[:errors] = @user.errors.full_messages
      erb :sign_up
    end
  end

  get '/log_in' do
    erb :log_in
  end

  post '/log_in' do
    @user = User.authenticate(params[:username], params[:password])
    if @user
      session[:name] = @user.name
      session[:user_session] = @user
      redirect to('/home')
    else
      flash.now[:errors] = ["The username and password do not match"]
      erb :log_in
    end
  end

  get '/make_cheet' do
    erb :make_cheet
  end

  post '/make_cheet' do
    cheet = Post.create(title: params[:title], body: params[:body])
    @user = session[:user_session]
    @user.posts << cheet
    redirect '/home'
  end

   delete '/log_out' do
      session[:user_id] = nil
      session[:name] = nil
      redirect to('/home')
    end




  # start the server if ruby file executed directly
  run! if app_file == $0
end
```

and the link to my repo

https://github.com/drjparry/chitter-challenge.git

**Comment by sjmog** [comment]
Are you starting the server with `rackup` or `shotgun`?

**Comment by sjmog** [comment]
Comment [here](https://github.com/drjparry/chitter-challenge/commit/a13479060f783efe29dbd545be720539b819e9f9)

**Comment by drjparry** [comment]
rack, i think. just ruby app/app.rb...

**Comment by sjmog** [comment]
You should avoid serializing the entire user to the `session`.

**Comment by drjparry** [comment]
I don't really understand, sorry. What's the other option?

**Comment by drjparry** [comment]
I'll be happy enough just to understand why sessions doesn't work here... what essential functionality am i misunderstanding?

**Comment by ggwc82** [comment]
I think what Sam means is that you only really need to store the user.id in session:

session[:user_id] = user.id.

In your code you have 3 different key value pairs in your sessions hash, when think can be done with just the one. Having 3 its very hard to keep track of whats doing what.

**Comment by drjparry** [comment]
that's a refactoring step though, not my problem. I have changed that anyway. i think it may have something to do with shotgun.

**Comment by ptolemybarnes** [comment]
Yarr if you're using shotgun be aware of the following:

1. [Shotgun](https://github.com/rtomayko/shotgun) works by reloading your entire application from source files with every request. This is fine except for one thing...

2. [Session secrets](http://www.sinatrarb.com/intro.html). "To improve security, the session data in the cookie is signed with a session secret. A random secret is generated for you by Sinatra." So what happens is, every time a client makes a request containing session data, sinatra checks that it was signed with the correct secret. However... "this secret will change with every start of your application," <--- ... yeah you can probably see what the problem is here. To go on "you might want to set the secret yourself, so all your application instances share it:
`set :session_secret, 'super secret'` <-- doing this means that every instance of your application will sign session data with the same secret, meaning that shotgun will work fine.

Or you could just use rackup ;-).

**Comment by drjparry** [comment]
Thanks for the answer Ptolemy. Yeah, i thought i had deleted shotgun when i uninstalled the gem and deleted it from the gemfile and force cleaned. Unfortunately, i didn't think to delete the gemfile.lock before doing all that. So somehow it was still intercepting the sessions and i couldn't work out why. Problem solved now though, 4 hours later... :(
