### ISSUE TITLE
Bootstrap Sinatra - correctly formats my link into a button but doesn't work for ul/li - same .erb

### ISSUE THREAD

**Issue by ggwc82** [makersacademy/slack-overflow#179]
I correctly installed twitter bootstrap into my app/public directory, and adding the lines 
```
5     <link href="/css/bootstrap.css" rel="stylesheet">
6     <link href="/css/bootstrap-responsive.css" rel="stylesheet">
49   <script src="/js/bootstrap.min.js"></script> `
```
into my layout.erb in the head and at the end of the body respectively. This all works fine, and all my forms and links get changed to the bootstrap versions.

Now, in my index.erb, I managed to get my Sign Up and Sign In links to format to buttons (lines 4 and 5 below). However, on this same view, lines 16-27 I can't get bootstrap to format my lists accordingly - its supposed to format to a basic list group. Instead, it appears as if its unformatted, with ugly html bullet points. I've tried with and without a div container, but nothing seems to work. Has anyone got any suggestions? 
```
  1 <h1>Chitter - Speak your mind!</h1>
   2
   3 <% unless @current_user %>
   4   <a class="btn btn-primary" href='/users/new'>Sign Up</a>
   5   <a class="btn btn-primary" href='/sessions/new'>Sign In</a>
   6 <% end %>
   7
   8 <% if @current_user%>
   9
  10 <form action='/update_peeps' method='post'>
  11   <input type='text' name='message'>
  12   <input class="btn btn-primary" type='submit' value='Peep'>
  13 </form>
  14
  15 <% end %>
  16 <div class="container">
  17   <h3>Peeps</h3>
  18 <% if @posts %>
  19   <% @posts.reverse!.each do |post| %>
  20     <ul class="list-group">
  21       <li class="list-group-item"><%= post.message %></li>
  22       <li class="list-group-item"><%= post.time %></li>
  23       <li class="list-group-item"><%= post.user.email.split('@').first%></li>
  24     </ul>
  25   <% end %>
  26 <% end %>
  27 </div>
```

**Comment by ptolemybarnes** [comment]
Hi can you provide a link to your code please?

**Comment by ggwc82** [comment]
HI Ptolemy, my code is here: [https://github.com/ggwc82/chitter-challenge/blob/master/app/views/index.erb](url)
