### ISSUE TITLE
rspec- sinatra initialization

### ISSUE THREAD

**Issue by MassimilianoMura** [makersacademy/slack-overflow#18]
Hi, I wrote my ruby app so now I would like to start with sinatra to create a front end side

I would like to initilialize everything, just using this:
``` rspec-sinatra init --app rps-challenge lib/rps.rb ```

 where ```rps-challenge``` is the name of my folder and ``` lib/rps.rb ``` the folder and the file I would like to have

but this is the result

```-bash: rspec-sinatra: command not found ```

that’s why I’m trying to scaffold by myself, but I prefer use the automatic initialization

repo link: https://github.com/MassimilianoMura/rps-challenge

**Comment by MassimilianoMura** [comment]
I update mi gem file adding

```gem 'rspec-sinatra'``` and then launching ```bundle ```

rpsec works with all my test... 

then if I do something like this ```rspec-sinatra init --app rps_challenge lib/rps.rb ``` I overwrite some files and I  break rspec...

**Comment by tansaku** [comment]
hi @MassimilianoMura so is this all fixed up?

**Comment by ptolemybarnes** [comment]
Looks like the original issue was solved so I'll close this.
