### ISSUE TITLE
Chitter - Capybara::ElementNotFound unable to find :username

### ISSUE THREAD

**Issue by Finble** [makersacademy/slack-overflow#181]
Hit this error yesterday...  Restarted project this morning (to flush out possibility of user error).  Have now had both Godfrey & Alain take a look and sadly no joy (code appears exactly same in their files as mine).

 - Stack error points to not being able to find element ('username') in webhelper method.  Method moved back to spec file --> same error, now located in spec file.
 - Have putsed throughout files - spec page reads app.rb and reads new.erb but cannot read 'any' field within new.erb.
 - Have run app, and program still reaches page (status 200) but does not display anything from new.erb.
 - Have uninstalled and reinstalled rspec and capybara --> no change
 - Have checked all requires --> no change
 - Created temp.erb and cannot render this page either (in terminal or running app in browser).

We're all stumped.  Any/all assistance appreciated.  

Error below:

#############################################

▶ rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

User sign up for Chitter:
Rendering THIS page...
  I can sign up as a new user (FAILED - 1)

Failures:

  1) User sign up for Chitter:  I can sign up as a new user
     Failure/Error: fill_in(:username, with: 'elaine')
     Capybara::ElementNotFound:
       Unable to find field :username
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/node/finders.rb:43:in `block in find'
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/node/finders.rb:32:in `find'
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/node/actions.rb:58:in `fill_in'
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
     # /Users/elainefinn/.rvm/gems/ruby-2.2.3/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/feature/user_management_spec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.02554 seconds (files took 0.87477 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/feature/user_management_spec.rb:14 # User sign up for Chitter:  I can sign up as a new user
[Coveralls] Outside the CI environment, not sending data.

################################################

**Comment by ptolemybarnes** [comment]
hi @Finble can you provide a link to the code? Thanks.

**Comment by Finble** [comment]
Have just pushed latest version.  Thanks!
https://github.com/Finble/chitter

**Comment by ptolemybarnes** [comment]
@Finble 
That's a tricky one. The problem is your layout file: it's empty. If sinatra detects a layout file it will first render that. It expects there to be a `yield` statement in your layout file which indicates where it should start rendering the particular view you want to show. Your layout file doesn't have a yield statement as the particular view (`users/new`) never gets rendered.

The solution is to either delete the layout file or add `<%= yield %>` to it. ;-)

On a side note, I can see that you checked that the file was getting loaded with a puts statement, which was a nice idea. I can only guess that the erb rendering engine takes a couple of passes, first dealing with the ruby code and then piecing the layout and view together, along with any partials. So although the `puts` statement still gets evaluated, the view piece of the puzzle doesn't get slotted in.

**Comment by Finble** [comment]
Thanks @ptolemybarnes 
I have copied over the contents of my index.erb to the layout.erb (which includes a yield statement) and still same error...  At this stage, I can't even remember why I have a separate layout.erb file...  The code I have added: 

<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
  </head>

  <body>
    <% if current_user %>
      Welcome, <%= current_user.email %>
    <% end %>
    <%= yield %>  
  </body>
</html>

**Comment by Finble** [comment]
Sorry code added - my copy and paste went weird!

<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
  </head>

  <body>
    <% if current_user %>
      Welcome, <%= current_user.email %>
    <% end %>
    <%= yield %>  
  </body>
</html>

**Comment by ptolemybarnes** [comment]
I think that's because current_user is not defined... what should happen at this point is that an UndefinedMethod exception should bubble up in the test and inform you that that's the problem.

However, this only happens when you have sinatra running in 'test' mode. Sinatra will run in test mode if the RACK_ENV environment variable is set to 'test'. I can see that in the spec_helper it's being set to 'development'. If you change that to 'test' then when you run your specs you should get proper error messages when something goes wrong.

**Comment by Finble** [comment]
Ok - have amended and passed!!  Wow, lots to take in there...  Random, but is there any 'map' of the order in which app files are read/run that might be useful to refer to (and indeed content of files, if such a thing exists...!)?  Just thinking how I could even identify this as an issue in the future...

And just to clarify, when running Sinatra (which is a test env), ALL references to Database (i.e. in chitter.rb and dm_setup.rb), including Rack Env reference in spec_helper, should reference 'test' (vs Development)?  You only change to Development (or even Production) once you deploy (e.g. to Heroku)?

Thanks Ptolemy, appreciate your time and wisdom!

**Comment by ptolemybarnes** [comment]
No worries ;-)

Unfortunately such a map doesn't exist.. I tempted to quote the Borges story, "On Exactitude in Science" here:

> . . . In that Empire, the Art of Cartography attained such Perfection that the map of a single Province occupied the entirety of a City, and the map of the Empire, the entirety of a Province. In time, those Unconscionable Maps no longer satisfied, and the Cartographers Guilds struck a Map of the Empire whose size was that of the Empire, and which coincided point for point with it. The following Generations, who were not so fond of the Study of Cartography as their Forebears had been, saw that that vast map was Useless, and not without some Pitilessness was it, that they delivered it up to the Inclemencies of Sun and Winters. In the Deserts of the West, still today, there are Tattered Ruins of that Map, inhabited by Animals and Beggars; in all the Land there is no other Relic of the Disciplines of Geography.

—Suarez Miranda, Viajes de varones prudentes, Libro IV, Cap. XLV, Lerida, 1658

But in all seriousness, it's worth trying to map out the sequence of things that happen when you type "rspec" into the terminal, or alternatively "rackup". What's the first file that gets run?

**Comment by Finble** [comment]
I knew it was a long shot... :joy: 
Thanks once again!
