### ISSUE TITLE
Ruby method for password=(password) in challenge 18 walkthrough for Bookmark Manager

### ISSUE THREAD

**Issue by ggwc82** [makersacademy/slack-overflow#182]
Probably something very basic, but can someone please explain what the method is doing with the input parameter here with the = sign:

`
 def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end
`

**Comment by ptolemybarnes** [comment]
I never got round to doing a proper version but this might help: https://www.youtube.com/watch?v=H_MI-adcSwI

**Comment by nikeshashar** [comment]
http://stackoverflow.com/questions/5398919/what-does-the-equal-symbol-do-when-put-after-the-method-name-in-a-method-d

**Comment by ggwc82** [comment]
thanks for the links ptolemy and nikesh.
