### ISSUE TITLE
Twilio API use

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/slack-overflow#184]
Ok, so the account sid and auth token don't appear to be being loaded into the local environment from the .env file when the text_messaging class instantiates...  Am I loading them correctly?

```
require 'twilio-ruby'
require 'dotenv'

Dotenv.load

class TextMessaging
  attr_reader :number, :from, :account_sid, :auth_token, :client
  def initialize(number)
    @number = number
    @account_sid = ENV['TWI_API']
    @auth_token = ENV['TWI_AUTH']
    @from = ENV['TWI_NUM']
    @client = Twilio::REST::Client.new account_sid, auth_token
  end
end
```

However, every unit test fails with:
```
ArgumentError:
       Account SID and auth token are required
```
I currently have the variables preceded by `export` in the .env file, but even removing this does not solve the problem.  Where am I going wrong?

**Comment by Jeremy-Barrass** [comment]
It may bare noting that the .env file is called 'texting.env' since just naming it a file extension with no prefix felt wrong.  Is that incorrect?

**Comment by arnoldmanzano** [comment]
the filename should be `.env`

**Comment by Jeremy-Barrass** [comment]
Ah, cheers Arnold.

**Comment by arnoldmanzano** [comment]
also, it loads the values inside the .env file, i believe no need to use export. You can try without if it works. Inside .env file:

ACCOUNT_SID=Axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
