### ISSUE TITLE
Rails g rspec:install not generating spec files

### ISSUE THREAD

**Issue by Finble** [makersacademy/slack-overflow#187]
Morning, I have run rails g rspec:install - it has returned the following message and NOT created a spec file for me (or any helpers) etc.  I have not installed a Spring preloader (unless it comes with Rails) and not seen this issue before (having worked with Rails all week).  

Running via Spring preloader in process 82871
  identical  .rspec
      exist  spec
  identical  spec/spec_helper.rb
  identical  spec/rails_helper.rb

**Comment by Adrian1707** [comment]
Run `bin/spring stop` and then try again. Is there any change?

**Comment by Finble** [comment]
Sorted!  Thank you :)
