### ISSUE TITLE
Bower package manager - write access issues?

### ISSUE THREAD

**Issue by Finble** [makersacademy/slack-overflow#188]
Hi - can anyone assist?  

 - I was trying to install the helper tools for the phonecat tutorial, when I received this message (if I am installing package, unsure why error message says no write permissions, assume already had package, so unsure why it is reinstalling package - so I tried to uninstall and reinstall but same error message - again, why does my write access have anything to do with installation or removal of package?).  
 - and if you see below this, I have gone into file to print out permissions, and I do appear to have some write permissions for each file?
 - problem is that even though you don't need tools to do tutorial, it now won't load npm dependencies (as it appears to stop at bower - 1 of the many needed).

Any support appreciated, thanks.

########################################################

npm WARN checkPermissions Missing write access to /usr/local/Cellar/node/5.2.0/libexec/npm/lib/node_modules/bower
/usr/local/Cellar/node/5.2.0/libexec/npm/lib
└── bower@1.7.7

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! path /usr/local/Cellar/node/5.2.0/libexec/npm/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/Cellar/node/5.2.0/libexec/npm/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/Cellar/node/5.2.0/libexec/npm/lib/node_modules/bower']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/Cellar/node/5.2.0/libexec/npm/lib/node_modules/bower' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/elainefinn/Makers/Week_8/angular-phonecat/npm-debug.log

#####################################################################

angular-phonecat/node_modules/bower  34ad33f ✗                                                                               506d ◒
▶ ls -l
total 112
-rw-r--r--   1 elainefinn  staff  38554 27 Jan 17:01 CHANGELOG.md
-rw-r--r--   1 elainefinn  staff   1074 27 Jan 17:01 LICENSE
-rw-r--r--   1 elainefinn  staff   5125 27 Jan 17:01 README.md
drwxr-xr-x   3 elainefinn  staff    102 27 Jan 17:01 bin
drwxr-xr-x  13 elainefinn  staff    442  7 Mar 15:27 lib
-rw-r--r--   1 elainefinn  staff   2220  7 Mar 15:27 package.json

**Comment by Adzz** [comment]
looks like it might be a problem with how npm or node has been installed. 
It's asking you to install using `sudo` which definitely dont do, and you shouldnt have to meaning something's gone wrong somehwere.

I would start with this: https://github.com/brock/node-reinstall

**Comment by Finble** [comment]
Thanks for link - sadly I immediately get this message:

angular-phonecat/node_modules/bower  34ad33f ✗                                                                                506d ◒
▶ git clone git@github.com:brock/node-reinstall.git
Cloning into 'node-reinstall'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Adzz** [comment]
okay so your ssh keys arent set up. Try cloning using https instead, i.e. use this command:

`git clone https://github.com/brock/node-reinstall.git`

**Comment by Finble** [comment]
ok, have done, but it won't load node or bower

angular-phonecat/node_modules/bower  34ad33f ✗                                                                                506d ◒
▶ cd node-reinstall

node_modules/bower/node-reinstall  master ✔                                                                                      98d
▶ bower install
zsh: command not found: bower

node_modules/bower/node-reinstall  master ✔                                                                                     98d  ⍉
▶ npm install
npm WARN EPACKAGEJSON node-reinstall@0.0.13 No repository field.
npm WARN EPACKAGEJSON node-reinstall@0.0.13 No license field.

A while back I set up zsh (over bash), wondering if my shell settings are all upset as a result (sadly I don't really understand my shell too well...) - just a thought.

**Comment by Adzz** [comment]
When you cd into the node-reinstall directory type

```
node-reinstall.sh
```
then press enter

**Comment by Adzz** [comment]
are you using homebrew?

**Comment by Finble** [comment]
yes, using brew

node_modules/bower/node-reinstall  master ✔                                                                                      98d
▶ ls
Makefile          README.md         node-reinstall.sh node_modules      package.json

node_modules/bower/node-reinstall  master ✔                                                                                      98d
▶ cd node-reinstall.sh
cd: not a directory: node-reinstall.sh

node_modules/bower/node-reinstall  master ✔

**Comment by Adzz** [comment]
You're close! Don't type the cd, just:

`node-reinstall.sh`

**Comment by Finble** [comment]
ode_modules/bower/node-reinstall  master ✔                                                                                      98d
▶ ls
Makefile          README.md         node-reinstall.sh node_modules      package.json

node_modules/bower/node-reinstall  master ✔                                                                                      98d
▶ cd node-reinstall.sh
cd: not a directory: node-reinstall.sh

node_modules/bower/node-reinstall  master ✔                                                                                     98d  ⍉
▶ node-reinstall.sh
zsh: command not found: node-reinstall.sh

**Comment by Finble** [comment]
would it be easier to jump into a hangout?  2 hours and counting on this issue...

**Comment by Adzz** [comment]
yea great idea

**Comment by Finble** [comment]
Thanks @Adzz
