### ISSUE TITLE
Omniauth not loading - rake db:migrate not running properly

### ISSUE THREAD

**Issue by Finble** [makersacademy/slack-overflow#189]
For weekend instagram challenge, I set up omniauth as per link: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

1.  Getting following error:

cannot load such file -- omniauth

Extracted source (around line #6):      
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]  +++++ HIGHLIGHTED LINE FOR ERROR

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|

########################################

2.  I've tried running rake db:migrate (and stopping spring), but it's not running properly:

Makers/Weekend/instagram-challenge  master ✗                                                                                  1d ⚑ ◒
▶ bin/rake db:migrate RAILS_ENV=development
WARNING: Nokogiri was built against LibXML version 2.9.3, but has dynamically loaded 2.9.2

Makers/Weekend/instagram-challenge  master ✗                                                                                  1d ⚑ ◒
▶ bin/rake db:migrate
WARNING: Nokogiri was built against LibXML version 2.9.3, but has dynamically loaded 2.9.2

Makers/Weekend/instagram-challenge  master ✗                                                                                  1d ⚑ ◒
▶ bin/spring stop

Makers/Weekend/instagram-challenge  master ✗                                                                                  1d ⚑ ◒
▶ bin/rake db:migrate
WARNING: Nokogiri was built against LibXML version 2.9.3, but has dynamically loaded 2.9.2

####################################
3.  Here is user.rb file contents:

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]  +++++  ASSUME OFFENDING LINE?

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    #user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
  	end
	end

	  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

######################################
4.  1 and 3 are copy pasted content from link instructions (and I got it running previously) - unsure what's happened.

Any help appreciated.
Thanks

**Comment by sjmog** [comment]
Are you definitely all bundled up? If so, could you try installing omniauth globally (`gem install omniauth`) to fix this issue?
