### ISSUE TITLE
Error at running  "npm run protractor"

### ISSUE THREAD

**Issue by hedudelgado** [makersacademy/slack-overflow#190]
I have researched, I have tried several things, but still getting the error. Reinstalled npm and node, the problem persists.

Any clue?

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by Adzz** [comment]
shall we do a hangout?

**Comment by Adzz** [comment]
one thing could be if a http-server process is already running
try this in your terminal:

`ps aux | grep http`

and see if there are any processes running.

**Comment by hedudelgado** [comment]
Adzz I have not managed to make this work, if you want to do hangouts I am happy to =)

**Comment by MahmudH** [comment]
What's in your protractor config

**Comment by Jeremy-Barrass** [comment]
Have you got java installed on your system?  https://makersstudents.slack.com/archives/january2016/p1457365229001218

If that doesn't work, close all your running servers, then run `npm start`, then in separate terminal tab in the angular-phonecat folder run 'npm run protractor'.

Also, which test are you trying to run?  Is it returning you any error messages related to that further up the log?  If so, you may need to debug the test.

**Comment by hedudelgado** [comment]
solved by running
./node_modules/.bin/protractor test/protractor-conf.js

Thank you
