### ISSUE TITLE
Paperclip Test Capybara - Errno::EACCES: Permission denied @ dir_s_mkdir - /spaces

### ISSUE THREAD

**Issue by reissjohnson** [makersacademy/slack-overflow#193]
Hi guys, after some guidance... 

I have written a test to check that when I upload a space with an image to my makers bnb app, the image appears on the page...
 
It uses the following syntax...

```
....
....
attach_file "Image", "spec/asset_specs/photo/Elephant.jpg"
...
...
click_button 'Create Space'
```

With "Image" being the label for the file field...

This plus the other params are then all created using `Space.create(spaces_params)`

It all works when running the server, but my test keeps failing on the following error...

```
Failure/Error: @space = Space.create(spaces_params)
Errno::EACCES:
    Permission denied @ dir_s_mkdir - /spaces
```

Does anyone have a clue? The image property is being permitted in my space_params method so it's not that...

I've been reading for about 2 hours now and other people tend to have the issue that the permissions haven't been set properly in their directory. I've tried this, but to no avail...

Any advice greatly appreciated!

**Comment by arnoldmanzano** [comment]
Did you configure path for the file paperclip anywhere? (on models or on another rb file?) Can you post the code and filenames here?

**Comment by reissjohnson** [comment]
Done! Was an issue with using an initialiser, I instead put my S3 credentials into my config files & all was good!
