### ISSUE TITLE
Using the gem rspec-sinatra on c9

### ISSUE THREAD

**Issue by omajul85** [makersacademy/slack-overflow#196]
Hello, 

I am following the instructions of this [walkthrough](https://github.com/makersacademy/course/blob/master/intro_to_the_web/walkthroughs/17_getting_started_with_battle.md) in order to set my project to work with Sinatra and RSpec. 

I am using cloud 9 and I am having problems when trying to run the server locally. So far, I have been using Sinatra on cloud 9 for ALL the previous steps (before using rspec-sinatra), and everything was working fine.  Below you have an example of how I run the Sinatra application:
 
![image](https://cloud.githubusercontent.com/assets/11027148/14828125/d70bfde6-0be5-11e6-96f6-ec3d77732e19.png)

After running that line, cloud 9 allows me to click on that link in green, and that opens my Chrome browser with the localhost:8080 socket. I can then use my app.
 
![image](https://cloud.githubusercontent.com/assets/11027148/14828136/e248932c-0be5-11e6-8d6a-22753c9479ac.png)

**# The problem occurs when I want to use the gem rspec-sinatra.  **

These are the instructions given in the walkthrough that I have followed on my cloud 9 workspace: 

1.	Create a project Battle and bundle init to specify the gems sinatra, capybara and rspec-sinatra.
2.	Initialize the app with the command: 

`$ rspec-sinatra init --app Battle app.rb`

At this point my tree looks like this:

 
![image](https://cloud.githubusercontent.com/assets/11027148/14828157/067a84bc-0be6-11e6-9b60-2231bd4c448d.png)

And my files contains the information created by default after initialization:

_#app.rb_
 
![image](https://cloud.githubusercontent.com/assets/11027148/14828168/11cea8ca-0be6-11e6-820e-ed06d8e535a0.png)

_#config.ru_

 
![image](https://cloud.githubusercontent.com/assets/11027148/14828175/1d6d05d2-0be6-11e6-84c4-c0c60eb575f6.png)

 3.	When trying to run the app.rb on the command line, everything seems fine. There is no error or warning... 

 
![image](https://cloud.githubusercontent.com/assets/11027148/14828186/2a85bdf4-0be6-11e6-8c25-fe4a6d2dbb40.png)

However, when I click on that link, nothing appears in Chrome this time:
 
![image](https://cloud.githubusercontent.com/assets/11027148/14828190/33ac3296-0be6-11e6-87d8-5437b2dc697c.png)

At this point, I was expecting the ‘Hello Battle!’ message printed on the browser. 

Is there any configuration missing?  I have tried the same instructions with 2 pair partners and they do not have any problems when running `ruby app.rb` and visiting localhost:4567. I guess this is related to the port used by cloud 9. Perhaps it expects the port to be 4567.  Any ideas ?.

Thank you in advance.

**Comment by tigretoncio** [comment]
Hola Omar,

Nice well presented issue.

As you know much better than me, Cloud9 only accepts very few ports available, from  [(the docs on c9)](https://docs.c9.io/docs/run-an-application)

> "Please note that 8080, 8081, and 8082 are the only available ports on a hosted Cloud9 workspace."

I would bet that the gem set up a port number which is not allowed by Cloud9, hence the issue.  

The gem has been written by @tansaku, you may want to check with him to understand how it is done, or with a Makers coach.
