### ISSUE TITLE
DataMapper - new record not saving but with no validation errors

### ISSUE THREAD

**Issue by ollieh-m** [makersacademy/slack-overflow#198]
I've (tried to) set up a simple has-many and belongs-to association using DataMapper. My User model has many peeps, and my Peep model belongs to user. See below for the classes....

I am able to successfully create a new peep which belongs to a particular user, by passing the user_id directly into the peep on initialization, like this:

**Method 1**
```
new_peep = Peep.create(content: params[:content], user_id: current_user.id)
```
_This adds 1 to Peep to Peep.count._

However, my understanding is that I should be able to create the association by assigning the current_user to new_peep.user. But that isn't working and it's left me bamboozled. I've tried this:

**Method 2**
```
new_peep = Peep.create(content: params[:content], user: current_user)
```

Current user here is `User.get(session[:current_user_id])`

The resulting new_peep has an id of nil, but does have user_id set to the current_user's id. New_peep looks exactly like the new_peep that successfully gets created, except it has no id itself, because it hasn't successfully saved. I've tried calling new_peep.save separately, but I still get the below for the peep object:

```
<Peep @id=nil @content="This is a test peep" @created_at=#<DateTime: 2016-05-08T12:42:52+01:00 ((2457517j,42172s,0n),+3600s,2299161j)> @user_id=1>, @errors={}
```

I assumed this was something to do with the belongs_to association not working, but I can (after creating new_peep using method 1 above) still call new_peep.user and access the correct user. So it seems to me the belongs_to is working as a reader but not a setter. 

This problem also means I cannot create a peep by adding one into the user.peeps collection then saving user, which means there's virtually no point in peep belonging to user.

I'd really like to know what's going on - this has baffled me for too long!

Here are my classes:

```
class Peep

	include DataMapper::Resource

	property :id, Serial
	property :content, Text
	property :created_at, DateTime

	belongs_to :user, required: false

	def created_at_formatted
		created_at.strftime("%H:%M, %A %-d %b %Y")
	end

end
```
```
class User

	include DataMapper::Resource
	include BCrypt

	attr_accessor :password_confirmation
	attr_reader :password

	property :id, Serial
	property :email, String, unique: true, required: true
	property :username, String, unique: true, required: true
	property :name, String
	property :password_hash, Text

	def self.authenticate(params)
		user = first(email: params[:email])
		if user && Password.new(user.password_hash) == params[:password]
			user
		else
			false
		end
	end

	def password=(actual_password)
		@password = actual_password
		self.password_hash = Password.create(actual_password)
	end

	validates_confirmation_of :password
	validates_presence_of :password

	has n, :peeps

end
```

**Comment by missamynicholson** [comment]
I don't necessarily think this is the problem (and in my 5 days of DataMapper experience, I am hardly in a position to advise!), but I don't think that adding peeps to the User class is necessary. 

Being able to call `user.peeps` is nice, but if one imagines how may tweets an avid tweeter could amass on Twitter, that will become quite a lot of associations to hold as the number of peeps rises. I''m not entirely sure how the database works, but if the peeps are stored in a mutable array/hash of some description, then there is probably a limit to how big that can grow, which would limit the total number of peeps/tweets one can make.

If one calls the DataMapper equivalent of `SELECT * FROM peeps WHERE user_id=current_user.id;` then all the peeps from the current_user can be found quite easily without needing the association on the User side. 

*DISCLAIMER: I may well be talking complete and utter nonsense.*

**Comment by ollieh-m** [comment]
Thanks,

Yes, the `has n, :peeps` definitely isn't necessary here (and I get what you mean about it potentially being inefficient in general) but I was mainly just trying to implement what I thought was the standard kind of association. The has n, belongs_to marriage is all over the datamapper documentation, and it just seems easier if you want to filter peeps by user to go with user.peeps

I did try without `has n, :peeps` and the problem with the belongs_to did not go away...

**Comment by JonnyPickard** [comment]
In peep I think you need to set property user_id to actually make the column in your database. Have you checked your database to see if the column is there? Postico is a really nice way to visualise a postgresql db if you're trying to understand whats going on better: https://eggerapps.at/postico/

**Comment by ollieh-m** [comment]
Thanks Jonny. Yep, peeps has a user_id column and the user_id attribute gets assigned using Method 1 and Method 2 (above) when I try to create the peep - the difference is just that with Method 2 the peep id stays as nil and the thing doesn't save...

**Comment by missamynicholson** [comment]
Perhaps the current_user isn't saved when you try to add it to a peep. As current_user.id is just an integer, that can simply passed to Peep, much like the message string, and stored. But when you pass in current_user as a whole, the instance may somehow be lost before it gets saved into the Peep database....

**Comment by JonnyPickard** [comment]
You should use the first way, it makes sense. DB associations are just a shared id number normally. So all peeps with a user id of 1 belong to user 1. You can just use a find method on user using the peep.user_id to find that specific user if needs be.

**Comment by ollieh-m** [comment]
I am pressing on using the first way, but the downside is that to make the peep belong to a user and to put the peep in a user's peep collection are now two separate steps for me. It should be one move: create the association. But that isn't working. 
`new_peep=current_user.peeps.create(content: params[:content])`
doesn't work. Nor actually does
`new_peep=current_user.peeps.create(content: params[:content], user_id: current_user.id)`
Neither creates the new_peep, though it exists with the correct user_id assigned to it, just with nil id itself.

**Comment by ollieh-m** [comment]
Amy, I tried doing current_user.save before creating the peep. No luck.

**Comment by JonnyPickard** [comment]
Just create the new peep like you have: `new_peep = Peep.create(content: params[:content], user_id: current_user.id) ` then to reference a users peeps:  `peep.all(:user_id => current_user.id)`. Sorry I haven't used datamapper in months but think that should work.

**Comment by ollieh-m** [comment]
Thanks. I feel like that works around how DataMapper wants me to do it - judging by their docs - but yeah, needs must.

**Comment by nmrichards** [comment]
Hey Ollie, I'm a little late to the game but instead of user_id: current_user.id, I did this 'user: User.get(session[:user_id])'. I know it's set the same as your current_user but I know when I tried current_user like you I had issues so I changed it back. Maybe it's just how it's being ran through the program or something but it definitely didn't like the current_user for me. Not sure if that will help you or not or if that's even the issue but throwing it out there.

**Comment by ollieh-m** [comment]
Thanks Nick. Yeah I did try that. I've tried pretty much every different way I can think of to specify the correct user as an attribute. What's really weird is that it works if I create a new user within the route and assign that to the peep.user - but if I create a new user in the route, retrieve that user using get and then assign that user to peep.user, the peep doesn't save.

**Comment by ollieh-m** [comment]
I've pushed a branch to my github repo which demonstrates the problem: https://github.com/ollieh-m/chitter-challenge/tree/fixing-belongs-to
