### ISSUE TITLE
reusing JavaScript objects that have a few elements changing with each use

### ISSUE THREAD

**Issue by DanielJohnston** [makersacademy/slack-overflow#2]
First off: This isn't officially part of the Makers Academy course, but it's proving useful for figuring out how to work with HTML and JavaScript.

I've been working on JavaScript and JSON that calls Google Charts and displays graphs on a webpage. The link below now has some code that displays correctly in both desktop and mobile browsers, and changes the height according to the number of rows. There are four main 'bits' to displaying each chart in the root folder:

1) var data is in function drawStuff() and contains the data to be rendered in the chart.
2) var options is in function drawStuff() and contains the layout options for rendering the data.
3) var chart pulls in the Google script and has the code to apply it to the div titled 'equalitywelcome'.
4) chart.draw(data, options) then draws the chart.

I'm publishing a webpage that has maybe 15 charts in, all using the same layout and code, but with different chart data in each. The things that can change each time are the data rows, number of data rows (which affects chartHeight and paddingHeight), tick titles, and name of the div. I'd like to be able to call the same function or script for each chart and just pass in the data rows, tick titles and name of div. Does anyone have any idea how to do this? Current thinking is to move all of the JS out of HTML into a named script that takes data passed to it by the webpage.

For reference, I've put individual examples of charts into a GiHub repo at https://github.com/nineworldsgeekfest/NW-2014-feedback-charts.

**Comment by DanielJohnston** [comment]
Off-topic, but is this seriously issue #2? I guess we're all steaming along without a care in the world this week. Tbf I know a bunch of the things we ran into with the lab week project were being raised as issues in their own repo. Hm.

**Comment by DanielJohnston** [comment]
For further reference, I'm putting the chart code in this webpage: https://nineworlds.co.uk/2014/feedback-report

**Comment by DanielJohnston** [comment]
OK, I 'solved' this by just repeating all of the code about 20-30 times. Gah.

**Comment by spike01** [comment]
Is there a repo I could look at? You should definitely not have to do that

**Comment by DanielJohnston** [comment]
Spike - Here's the final page in its present form: https://github.com/nineworldsgeekfest/NW-2014-feedback-charts/blob/master/theEntireReport.html

I'm pretty sure there's a way to abstract out the code and data and pass in the data and options that change as arguments, but I'm still really vague on JavaScript generally.

**Comment by spike01** [comment]
Ok, so... this is really hard to read and see exactly what options are changing, but from what I gather, you only change the rows being passed in and the elementId? If those are the two, let's make them changeable by passing them as arguments:

```
	function drawStuff(rows, elementId) {
		var data = new google.visualization.DataTable()
		data.addColumn('string', 'Area'); // Implicit domain label col.
		data.addColumn('number', 'Inclusion'); // Implicit series 1 data col.
		data.addColumn({
			type: 'number',
			role: 'interval'
		}); // interval role col.
		data.addColumn({
			type: 'number',
			role: 'interval'
		}); // interval role col.
		data.addColumn({
			type: 'string',
			role: 'style'
		});
		data.addRows(rows);
		// set a padding value to cover the height of title and axis values
		var paddingHeight = 40;
		// set the height to be covered by the rows
		var rowHeight = data.getNumberOfRows() * 30;
		// set the total chart height
		var chartHeight = rowHeight + paddingHeight;
		var options = {
			chartArea: {
				top: 0,
				height: chartHeight - paddingHeight,
				left: '25%',
				width: '70%'
			},
			width: "100%",
			height: chartHeight,
			legend: {
				position: 'none'
			},
			hAxis: {
				ticks: [{
					v: 0,
					f: 'Very excluded'
				}, {
					v: 33.33,
					f: 'Somewhat excluded'
				}, {
					v: 66.66,
					f: 'Somewhat included'
				}, {
					v: 100,
					f: 'Very included'
				}],
				format: 'percent'
			}
		};
		var chart = new google.visualization.BarChart(document.getElementById(elementId));
		chart.draw(data, options);
	};
```

Then, for neatness, assign the array to a variable so you can pass it in more cleanly:

```javascript
var rows = [
			["Your welcome", 88, 81, 95, '#76B0DE'],
			["Section average", 92, 85, 99, '']
		 ]
```

And then call the function:

```javascript
drawStuff(rows, 'equalitywelcome')
```

Does that get you started?

**Comment by ptolemybarnes** [comment]
@DanielJohnston hey did you make progress on this issue?

**Comment by DanielJohnston** [comment]
Haven't had chance yet. Got totally off track trying to sort out convention
stuff the last few days. I'll be working on it over the next week for
publication Saturday, so will try to improve the structure as part of that.
Need to try and make headway on the bowling challenge in the meantime.
Thanks for the suggestion on restructuring, Spike!

On Sun, 7 Jun 2015 20:41 Ptolemy <notifications@github.com> wrote:

> @DanielJohnston <https://github.com/DanielJohnston> hey did you make
> progress on this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/issues/issues/2#issuecomment-109792281>.
>
-- 

Regards,
Daniel
Nine Worlds

**Comment by tansaku** [comment]
@DanielJohnston @ptolemybarnes what's the status on this now?

**Comment by DanielJohnston** [comment]
Still pending. The actual convention behind this piece of work has turned into a bit of a beast for various reasons. I'm prioritising finishing off the content and will work on code structure after that. Are we ok to leave this open or would you prefer to close it for now? I can copy the suggestions across if so.

**Comment by tansaku** [comment]
open is good as long as we know the status :-)

**Comment by DanielJohnston** [comment]
I'm figuring mid-August by this point. Finishing the content of the report is taking forever, let alone refactoring the display code.
