### ISSUE TITLE
average ratings test failure

### ISSUE THREAD

**Issue by tigretoncio** [makersacademy/slack-overflow#200]
Trying to complete yelp bonus stage 1 available [here](https://github.com/makersacademy/course/blob/master/rails/yelp_further_challenges/1_average_ratings.md)

The walkthrough proposes the following test:
````
context 'multiple reviews' do
  it 'returns the average' do
    restaurant = Restaurant.create(name: 'The Ivy')
    restaurant.reviews.create(rating: 1)
    restaurant.reviews.create(rating: 5)
    expect(restaurant.average_rating).to eq 3
  end
end
````
And the following code to make the test pass:
````
reviews.average(:rating)
````

However this solution does not make the test pass, I get the following error:

````
1) #average_rating multiple reviews returns the average
     Failure/Error: expect(restaurant.average_rating).to eq 3
     
       expected: 3
            got: 1.0 (#<BigDecimal:87553e8,'0.1E1',9(36)>)
     
       (compared using ==)

````

After investigation it seems that the average does not take into account the second review, it would even seem that the second review is effectively not being created, which may be reasonable as we have added a constraint to ensure that only one review is made per restaurant and user.  As we are making the unit test and "hitting" directly the database, that should not be an issue, however the average method from rails only takes the first review.

A print of the review after the test is run is as follows:
````
#<ActiveRecord::Associations::CollectionProxy [#<Review id: 387, thoughts: nil,
 rating: 1, created_at: "2016-05-26 20:46:50", updated_at: "2016-05-26 20:46:50",
 restaurant_id: 1439, user_id: nil>, #<Review id: nil, thoughts: nil, rating: 5, 
created_at: nil, updated_at: nil, restaurant_id: 1439, user_id: nil>]>
````

I note that the Review id from the first record is 387, however for the second record is nil, so somehow the review has not been properly created, (again suspect that validation constraint of only allowing one review per user and restaurant).

If I create my own average method such as:

````
  def average_rating
    return "N/A" if reviews.none?
    sum = 0
    i = 0
    reviews.each do |review|
      sum += review.rating
      i += 1
    end
    sum/i.to_f
  end
````

Then I pass the test.  Also, if I use the average test and try the application at feature level, the average works, (so clearly it is a problem at the unit test itself).

So imo the test is not correctly setup.  I have tried to amend the     restaurant.reviews.create(rating: 5) line using the build_with_user method and adding a user, but I was not successful in making it work.

So my questions would be:
- Why is this test failing, and average only taking 1 record and not all?
- How can I define a test that uses average in the proper way, and how this relates to the review records?

**Comment by Itsindigo** [comment]
Is this code pushed up anywhere?

**Comment by tigretoncio** [comment]
the code is available [here](https://github.com/tigretoncio/yelp_clone/tree/810aeebd29af0c20b17ecbb9a87bb66df63a6f9e)

**Comment by missamynicholson** [comment]
Could you use the 'create_with_user' method to create the reviews? (The one in the module)

**Comment by tigretoncio** [comment]
hi  Amy, thanks for stopping by.

Unfortunately I am unable to make it work with create_with_user, or build_with_user (and then save), the same error applies, it just takes the first record to calculate average.

**Comment by MaxProvin** [comment]
ive made an almost groundless assumption that the rails/ActiveRecord calculator method average is intended to be used directly on a model with a column as an arg taking an average of the values in that column, in this case we are calling it on multiple reviews via association so maybe its getting confused?
Also reviews.inject(0) {|memo, review| memo + review.rating} / reviews.count doesn't work but reviews.inject(0) {|memo, review| memo + review.rating} / reviews.length does... at least for me

**Comment by tigretoncio** [comment]
hi Max
I think I forgot to comment that the average method does work in the application itself, (when you are adding reviews from different users it makes the average properly). The only bit that works oddly is the "N/A", I am unable to make that work, I get 0 in that case.  But regardless, the fact that the method works on the development env would mean that the problem is linked to the test itself, and the fact that to create a review in the unit test we don't use a different user, (as in the real app when we use different users the average works).

**Comment by missamynicholson** [comment]
Hi Sergio,
I tried the following for the unit test which seems to get around the "Big Decimal" error and allows the use of `reviews.average(:rating)`. 

```
context "multiple reviews" do
   it "returns the average" do
     restaurant` = Restaurant.create(name: "The Ivy")
     user = User.create(email: "hello@gmail.com", password:"password")
     restaurant.reviews.create_with_user({rating: 1}, user)
     user2 = User.create(email: "goodbye@gmail.com", password:"password")
     restaurant.reviews.create_with_user({rating: 5}, user2)
     expect(restaurant.average_rating).to eq 3
   end
end
```

The special case for N/A is still needed in order to pass the specific unit test which requires it. But the code now looks like this:

```
def average_rating
  return 'N/A' if reviews.none?
  reviews.average(:rating)
end
```

I used `create_with_user!` (note the '!') initially which was helpful in diagnosing the problem as it throws an exception if unsuccessful. It seems that a User cannot have a nil password, and that the password must be at least 6 characters!

**Comment by tigretoncio** [comment]
What can I say Amy... you are a mega :star2:
