### ISSUE TITLE
Issue during the NoteJS challenge: 

### ISSUE THREAD

**Issue by LawrenceHunt** [makersacademy/slack-overflow#216]
Hi all - I'm suddenly getting this error with my code, having created the note controller model...

```
note-list-view.js:12 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at NoteListView.printList (http://127.0.0.1:8080/note-list-view.js:12:43)
    at new NoteController (http://127.0.0.1:8080/note-controller.js:4:36)
    at http://127.0.0.1:8080/index.js:6:22NoteListView.printList @ note-list-view.js:12NoteController @ note-controller.js:4(anonymous function) @ index.js:6
```

Here's the code for the NoteListView model it's pointing to: 

```
(function(exports) {

  function NoteListView(noteList) {
    this.noteList = noteList;
  }

  NoteListView.prototype.printList = function(){
    var list = document.createElement('ul');
    list.id = "noteList";

    for (i = 0; i <= this.noteList.returnList().length; i++) {
      note = document.createElement('li').appendChild('div');
      note.textContent = this.noteList.returnList()[i].returnNote();
      list = document.getElementById('noteList');
      list.appendChild(note);
    }
    return list;
  };

  exports.NoteListView = NoteListView;

  // module.exports = Note;
})(this);
```

And here's the Note Controller model: 

```
(function(exports){

  function NoteController(noteViewModel){
    this.showNotes = noteViewModel.printList();
  }

NoteController.prototype.showList = function() {
  list = document.getElementById('app').appendChild(this.showNotes);
};

exports.NoteController = NoteController;

})(this);
```

**Comment by silvabox** [comment]
@LawrenceHunt have you considered what the error message means?  What steps have you taken so far to decipher it?

`this.noteList.returnList()[i].returnNote();` looks like a Demeter violation to me 😉

**Comment by LawrenceHunt** [comment]
Does it mean you simply can't use appendChild that way to add a 'div' tag?

I appreciate your point about the law of Demeter, but I'm not quite sure how else to access the note's text in this context. Other people seem to be doing it the same way but calling .text directly - and I don't even understand how this is possible because mine doesn't seem to be accessible!

**Comment by LawrenceHunt** [comment]
I'm trying this now, and getting a different error - it thinks note is 'null' on line 19 (where I try and append note to list: 

```
(function(exports) {

  function NoteListView(noteList) {
    this.noteList = noteList;
  }



  NoteListView.prototype.printList = function(){
    var list = document.createElement('ul');
    list.id = "noteList";

    for (i = 0; i <= this.noteList.returnList().length; i++) {
      note = document.createElement('li');
      div = document.createElement('div');
      div.textContent = this.noteList.returnList()[i].returnNote();
      note.appendChild(div);
      list = document.getElementById('noteList');
      list.appendChild(note);
    }
    return list;
  };

  exports.NoteListView = NoteListView;

  // module.exports = Note;
})(this);
```

**Comment by silvabox** [comment]
can `note` be null if you're calling `appendChild` on it two lines before?

**Comment by LawrenceHunt** [comment]
Well, this is the error I'm getting: 

note-list-view.js:19 Uncaught TypeError: Cannot read property 'appendChild' of null
    at NoteListView.printList (http://127.0.0.1:8080/note-list-view.js:19:11)
    at new NoteController (http://127.0.0.1:8080/note-controller.js:4:36)
    at http://127.0.0.1:8080/index.js:6:22

**Comment by silvabox** [comment]
Have you checked here? https://developer.mozilla.org/en/docs/Web/API/Node/appendChild

**Comment by silvabox** [comment]
Right, so it's `list` that's null; not `note`.

**Comment by LawrenceHunt** [comment]
Thanks for trying Ben. I'm going to have to give up and use Stevie's. :/

**Comment by silvabox** [comment]
The answer is very simple but you are not asking the right question.
