### ISSUE TITLE
The page won't change content without being manually refreshed.

### ISSUE THREAD

**Issue by James-SteelX** [makersacademy/slack-overflow#217]
So we are on step(9) of the weekly project and we're trying get the page to change it's content without a refresh by using 'hashchange'. Currently we can get the page to display the correct content but only after a manual refresh. 

Here is the code we are trying to use (inside note-controller.js):

`NoteController.prototype.changeNote = function() {`
  `window.addEventListener("hashchange", this.showNoteOnPage());`
` };`

` NoteController.prototype.showNoteOnPage = function() {`
    `var s = this.getNoteFromUrl(window.location);`
    `this.showNote(s);`
` };`

Theres a few methods that they point to but they seem to be working as intended.

We think it's because the function is only being called when the page is loaded but unsure of why this is happening since 'hashchange' should do something when it sees a change in the url after the '#'

Repo: https://github.com/James-SteelX/JS-note/tree/day-three-test

**Comment by silvabox** [comment]
@James-SteelX examine your statement about the function only being called on page load.  That's both a symptom and a clue.

**Comment by silvabox** [comment]
Are there any errors in the console?

**Comment by James-SteelX** [comment]
No errors, it just doesn't do what we expect it to do

**Comment by silvabox** [comment]
Right, so now examine what it _does_ do.  Can you post your usage of `changeNote`

**Comment by James-SteelX** [comment]
inside index.js we have this line -
`noteController.changeNote();`
Thats the only time it is called.

**Comment by silvabox** [comment]
@James-SteelX and what does that function do?

**Comment by James-SteelX** [comment]
It _should_ listen for a hashchange in the url and then run another function as a result. I believe anyway. 
I've got it to work by having everything inside the index.js file but i know thats not the way it should be done, even removing the function .changeNote(); and doing the event listener directly from index.js has proven fruitless. We know it's because it's only getting called on refresh but I can't work out why.

**Comment by silvabox** [comment]
does your `changeNote` function listen for a hashchange?  Your description is imprecise, which will not help you debug.  What precisely should `changeNote` do?

**Comment by James-SteelX** [comment]
changeNote should listen for a 'hashchange' and run function .showNoteOnPage(); if it senses a 'hashchange'

**Comment by silvabox** [comment]
Nope - `changeNote` does not listen for anything: that's all done by the browser.  https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by silvabox** [comment]
`window.addEventListener("hashchange", this.showNoteOnPage());`
What are you passing to `addEventListener`?

**Comment by James-SteelX** [comment]
@silvabox We are passing the hashchange listener and a function to change the note at the top of the page.

**Comment by silvabox** [comment]
No - you're not.
