### ISSUE TITLE
Unable to access constructor function variables in its prototype methods

### ISSUE THREAD

**Issue by wirsindpapst** [makersacademy/slack-overflow#218]
Please excuse any incorrect terminology used in the below and/or poorly designed code - it is a work in progress.

We have created an constructor function that receives the output of an API call upon instantiation, which is then used to populate the page in our app (see index.js l.15 and headline-list-view.js l.11 in console screenshot below).

This object is logged to the console without problem when the functions to produce and render the browser are called, but calls on other prototype methods executed upon hash change events return 'undefined' (see headline-list-view-js l.26
![screen shot 2016-11-10 at 17 58 06](https://cloud.githubusercontent.com/assets/15246929/20188210/8c193ab2-a76f-11e6-854c-34988978e72f.png)
).

We are struggling to understand why this is the case. We have tried triggering these subsequent functions via an event listener located within the constructor function and from a separate index.js file. We have also tried making these 'generic' functions not following the prototype pattern to no avail.

Many thanks for any help proffered.

![screen shot 2016-11-10 at 18 01 59](https://cloud.githubusercontent.com/assets/15246929/20188264/d73cc6c6-a76f-11e6-871c-f708cf87ecd1.png)

**Comment by silvabox** [comment]
@wirsindpapst I can't see the code that creates the object on which Rhee function is called

**Comment by wirsindpapst** [comment]
See below. We've managed to get it working by moving things out of the HeadlineList view to the index.js file below. I'm pretty sure both options are bad encapsulation .... 
![screen shot 2016-11-10 at 18 46 44](https://cloud.githubusercontent.com/assets/15246929/20189650/11f9027e-a776-11e6-96b4-733994aaa375.png)

**Comment by silvabox** [comment]
Right but how can I address the original issue now that you've changed the code?

**Comment by wirsindpapst** [comment]
This is a very good point....perhaps it's something that we can discuss in more a conceptual manner in the surgery tomorrow (if there is one) ...?

Closed!
