### ISSUE TITLE
An issue with 'this' and variable scope

### ISSUE THREAD

**Issue by LawrenceHunt** [makersacademy/slack-overflow#219]
Hi guys - wonder if anyone can tell me what's going wrong here with my extraction of Guardian API data...

the console is printing the newStoryArray variable fine down on line 19 - but I'm getting an 'undefined' error when I try and bring it out one level up and assign it to the variable this.stories.

I'm confused as I'm calling 'this' in the immediate context of the StoryList prototype, which is where it's originally defined. How do I get this data out?

```
(function(exports) {

  function StoryList() {
      this.stories = [];
  }

  StoryList.prototype.getStories = function(){
    var request = new XMLHttpRequest();
    var storyArray;
    var newStoryArray;
    request.open("GET", "http://news-summary-api.herokuapp.com/guardian?apiRequestUrl=http://content.guardianapis.com/search?section=uk-news&page-size=5", true);
    request.send();
    request.onload = function(){
      var data = JSON.parse(request.responseText);
      storyArray = data.response.results;
      newStoryArray = storyArray.map(function(storyObject){
        return new Story(storyObject);
      });
      console.log(newStoryArray);
    };
    this.stories = newStoryArray;
  };

  StoryList.prototype.returnStories = function() {
      return this.stories;
  };

  exports.StoryList = StoryList;
})(this);


```

**Comment by silvabox** [comment]
@LawrenceHunt to test if it's a scope issue, change `var newStoryArray;` to ` var newStoryArray = 'this is a test';`
The `console.log(newStoryArray)` before you try to assign `this.stories = newStoryArray;`

That should give you a clue.

**Comment by LawrenceHunt** [comment]
So within the scope of 'this.stories', newStoryArray is STILL set to 'this is a test' and hasn't been overwritten! 

How do I get around that? I thought the function would overwrite the value of newStoryArray!

**Comment by LawrenceHunt** [comment]
(my only guess is to use .call, but would I then need to assign the whole function to a variable to do that?)

**Comment by silvabox** [comment]
You are asking the wrong question.  Instead of "How do I get around that?" you should be asking "**Why** is that happening"

**Comment by silvabox** [comment]
Don't jump to arbitrary solutions until you understand the cause of the problem; debugging is a scientific process.

**Comment by LawrenceHunt** [comment]
Sorry, yeah I have been trying to figure out why it's happening. But the only conclusion I can draw is that you can't reassign a variable in this way.

**Comment by LawrenceHunt** [comment]
Oh thank god. Finally figured it out - I needed to assign 'this' to a variable and take it down into the function with me.

```
(function(exports) {

  function StoryList() {
    this.stories = [];
  }

  StoryList.prototype.getStories = function(){
    var request = new XMLHttpRequest();
    var storyArray;
    var newStoryArray;
    var that = this;
    console.log(this.stories);
    request.open("GET", "http://news-summary-api.herokuapp.com/guardian?apiRequestUrl=http://content.guardianapis.com/search?section=uk-news&page-size=5&show-fields=thumbnail", true);
    request.send();
    request.onload = function(){
      var data = JSON.parse(request.responseText);
      storyArray = data.response.results;
      newStoryArray = storyArray.map(function(storyObject){
        return new Story(storyObject);
      });
      that.stories = newStoryArray;
    };
  };

  StoryList.prototype.returnStories = function() {
      return this.stories;
  };

  exports.StoryList = StoryList;
})(this);
```
