### ISSUE TITLE
Using .map() on a 'this.' property

### ISSUE THREAD

**Issue by LawrenceHunt** [makersacademy/slack-overflow#220]
So I'm trying to use .map on a 'this.' property - my research suggests you can preserve the initial context of 'this' by adding 'this' as a second parameter to the 'each'. 

But I'm getting nothing. I used a var that = this for this situation before, but there isn't an actual 'this' call within the block to do it for here.

Can anyone just explain to me the best approach to manipulating data that's held in a 'this' property? Thanks so much :D

```
(function(exports){

  function StoryListView(storyList) {
    this._storyList = storyList.returnStories();
  }

  StoryListView.prototype.renderHTML = function() {
    array = this._storyList;
    console.log(array) -- WORKS
    array.map(function(story){
      console.log(story); ---- DOESN'T WORK
     stories = '<li>' + story.returnTitle() + '</li>';
   }, this);
      return '<ul>' + stories + '</ul';
  };

  exports.StoryListView = StoryListView;
})(this);
```

**Comment by amaalali** [comment]
I was able to return get ```console.log(story)``` to return the element of the array, but I short circuited to accept an array of integers instead so it would be easier to for me quickly test. You may want to try ```console.log(story.returnTitle())``` and see what that returns?

The ```Array.prototype.map()``` method returns an array with each element being passed through the anonymous function ``` function(story) { '<li>' + story.returnTitle() + '</li>' } ``` . I think you might instead want :  ```stories = array.map( function(stories) { ...} ) ``` and then concatenate all the elements of the ```stories``` array?

**Comment by LawrenceHunt** [comment]
Thanks Amaal. I think (with a fair bit of helpful input from Tadas) that my app's flow was wrong - I wasn't passing the data to the new StoryList. That's what was throwing me off.
