### ISSUE TITLE
Creating relationships in Active Record

### ISSUE THREAD

**Issue by wirsindpapst** [makersacademy/slack-overflow#221]
afternoon campers (and @ben) - has anyone had any joy getting the user has_many restaurants association  to work? we've added the association in the model (as per the scant walkthrough) and  managed to cobble together a migration to get the relevant column in the db, but when trying to add a restaurant in the app, we get a 'user must exist' flash error. 

we've been trying to pass in the current_user.id as an additional parameter when the restaurant is created to solve this as the issue seems to be relate to it not being clear what to use to populate this new column with.
```
<restaurant_controller.rb>

  def restaurant_params
  @user = current_user
    params.require(:restaurant).permit(:name, :description, user_id: @user.id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end
```

**Comment by silvabox** [comment]
I'm not sure `params.require(:restaurant).permit(:name, :description, user_id: @user.id)` is valid syntax...

Also note, the controller is not responsible for understanding the database implementation of the association between `User` and `Restaurant` so you should be associating the objects; not just setting the `user_id`.

**Comment by wirsindpapst** [comment]
ok .... so we don't even have to specify where to get the user id from as this must be another inference made in rails...

many thanks!
