### ISSUE TITLE
Associations in ActiveRecord - help!

### ISSUE THREAD

**Issue by francesmx** [makersacademy/slack-overflow#222]
We are on Yelp Stage 3 which is about the many-to-many relationship between restaurants and reviews. In the walkthrough, it claims that our model says that restaurants 'belong to' users, and users 'have many' restaurants. But actually that was never specifically in our code (unless Rails did it magically in the background), so we're trying to sort this bit out BEFORE moving onto the many-to-many relationship part. 

So in our user model, we've got:

````
class User < ApplicationRecord
  has_many :restaurants
  has_many :reviews
````

and in our restaurant model, we've got:

````
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
````

We've also ran a migration to add user_id to the restaurants table as a foreign key.

Loads of our tests are failing because when you try to add a new restaurant, it says 'User must exist'. We are definitely signed in, but we don't know how to get it to automatically insert the user_id into the restaurants table. 

From our understanding, this should happen from the model, and we shouldn't have to insert 'user_id' via the controller. But... we don't know how to do this.

Please can you help? 🙀

**Comment by silvabox** [comment]
@francesmx how do you identify the user?

**Comment by francesmx** [comment]
I think Rails has something called current_user ? So I should be able to use current_user.id
But I don't know where 😞

**Comment by silvabox** [comment]
Not Rails; Devise provides `current_user`.  What does that method return?  And where does the concept of a current user fit in the MVC pattern?

**Comment by francesmx** [comment]
Oh of course, that makes sense that it's from Devise. 

I have to admit I don't know specifically what `current_user` returns (and unfortunately I don't know how to 'print/puts' it with Rails - I need to figure this out!) but I'd guess it contains data from the Users table in the database, i.e. ID, name, image (which we get from Facebook). I know that because we've been able to access `current_user.image` in one of our views, for example.

Where does the concept of a 'current user' fit in the MCV pattern? Hmm... well it's the current one for this session (rather than a conceptual one) so although that data is coming from the database, it feels like it might be more 'controller' related than model.... 😬 

What are your next questions? 😀

**Comment by silvabox** [comment]
erm, `puts current_user`? 😀

**Comment by francesmx** [comment]
Haha I suppose I can just whack that in a view, right? 😊

**Comment by silvabox** [comment]
Anywhere you like.  It will appear in the rails log.

**Comment by francesmx** [comment]
Okay so it looks like a User object #<User:0x007fe589b41998>

**Comment by francesmx** [comment]
Ahhh the log! I love that log.

**Comment by francesmx** [comment]
User object makes total sense. Dear god.

**Comment by francesmx** [comment]
Still don't know how to fix our issue though 🆘

**Comment by silvabox** [comment]
So how do you relate that user to the new restaurant?

**Comment by silvabox** [comment]
can you post the code where you create the restaurant?

**Comment by francesmx** [comment]
Well... we have a user_id in the restaurants table. But as to how it creates the association (beyond the `has_many`, `belongs_to` thing in the model), I just don't know!

**Comment by francesmx** [comment]
````
	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'
		end
	end
````

**Comment by francesmx** [comment]
````
	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :description)
	end
````

**Comment by francesmx** [comment]
Our first thought was to just whack the current_user.id in at the point of creating the new restaurant. But is that right?

**Comment by amaalali** [comment]
Is it not similar to how we associated the reviews to a restaurant?

**Comment by silvabox** [comment]
Have you read this http://guides.rubyonrails.org/association_basics.html#detailed-association-reference?

**Comment by silvabox** [comment]
Remember my post yesterday about avoiding setting the `user_id` directly?

**Comment by francesmx** [comment]
I don't remember that post, but I do remember you telling me not to do that in your feedback from one of my weekend challenges, but I wasn't sure of the alternative. Okay we'll read that documentation in more detail!

@amaalali probably! 🙀

**Comment by francesmx** [comment]
Ok so now we're using:

````
def create
		@user = current_user
		@restaurant = @user.restaurants.create(restaurant_params)
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'
		end
	end
````

and this is working nicely!

BUT... in our feature spec, we have things like:

````
let!(:trat){Restaurant.create(name: 'Tratoria Populare')}
````

But of course, now we need to create restaurants differently. Except I can't seem to access current_user from the spec (even though it should be signed in).

Sigh. Any suggestions? Maybe some wine will help.

**Comment by francesmx** [comment]
Shall I just mock the user ID?

**Comment by francesmx** [comment]
Or mock the whole user? But I don't get it, because it should actually be signed in... 🙀

**Comment by francesmx** [comment]
We're using a helper method:

````
def sign_up_and_sign_in
  visit '/'
  click_link 'Sign up'
  fill_in 'Email', with: 'test@example.com'
  fill_in 'Password', with: 'testtest'
  fill_in 'Password confirmation', with: 'testtest'
  click_button 'Sign up'
end
````

**Comment by silvabox** [comment]
OK, but what relationship does that have to you `let` statement?

**Comment by francesmx** [comment]
I'm trying to replace the let statement with a real creation of a restaurant using the user object, but I can't retrieve the user object in the spec.

**Comment by francesmx** [comment]
I'm just creating the restaurant using capybara (using the interface) which I suppose isn't the worst for a feature test 😹

**Comment by francesmx** [comment]
Ah no but what about the unit test? 😱 

````
  it 'is not valid with an existing name' do
    Restaurant.create(name: 'a restaurant')
    restaurant = Restaurant.create(name: 'a restaurant')
    expect(restaurant).to have(1).error_on :name
    expect(restaurant).not_to be_valid
  end
````

What do I do there? I want to use the @user.restaurants.create sytax.

HELPPPPP

**Comment by francesmx** [comment]
I guess I need to stub the user?

**Comment by silvabox** [comment]
You are over complicating things.  The concept of a current user is only relevant when you are talking about a signed-in user; which is only relevant in a feature test.

For a unit test, an associated user must exist if it's mandatory, but it's just an instance of `User`.

**Comment by francesmx** [comment]
"Over complicates things" is my middle name. Okay, I don't mind appearing stupid so I'm going to ask more questions 😀 

(1) I couldn't access current_user in my feature test but shouldn't I have been able to, since they were signed in using the interface?

(2) In the unit test, because I'm testing Restaurant, that makes me think I should stub the User model. But it won't work because I can't do :user.restaurants.create (like I did @user.restaurants.create in the controller) - it doesn't like the syntax.

**Comment by francesmx** [comment]
Ah just saw your comment "Stubbing models in Rails is impractical"

So should I just create a real User object then?

**Comment by silvabox** [comment]
1. No; think about scope.  `current_user` is only available inside the controller.

2. Yes, just create a real `User` object.

Also checkout the Devise test helpers.

**Comment by francesmx** [comment]
Ok thanks. Ahhhh I see re current_user. I've managed to work around that anyway now. And the real User object has worked in the unit test too. Argh getting there. I'm going to close this issue - thanks for your help.
