### ISSUE TITLE
An open question

### ISSUE THREAD

**Issue by dearshrewdwit** [makersacademy/slack-overflow#234]
**Describe the situation**
A clear and concise description of the situation.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**
Add any other context about the problem here

**Comment by Yiorgoss** [comment]
Take me off this mail list.

**Comment by dearshrewdwit** [comment]
@Yiorgoss there are instructions to unsubscribe in your email as you can see.

You might want to update your github notifications, or choose which repositories you follow.

LMK if you have questions

**Comment by Finble** [comment]
Me too please. I’ve tried to unsubscribe...

Sent from my iPhone

On 3 May 2020, at 08:43, Yiorgos Joseph Makridakis <notifications@github.com> wrote:

﻿

Take me off this mail list.

**Comment by dearshrewdwit** [comment]
@Finble et al. For everyone else who's following this repository: from the week after next, this repository will start having lots more issues being opened and closed. I appreciate how irritating this might be if you still are watching this repository!

You might want to manage your notifications before then. Here are some ways you can achieve this:

1. Stop watching this repository
2. Manage your notifications for this repository
3. Unsubscribe from notifications
4. Manage your account notification settings.
