### ISSUE TITLE
DataMapper::RepositoryNotSetupError at /links

### ISSUE THREAD

**Issue by natstar93** [makersacademy/slack-overflow#26]
Hi,

We are working on the bookmark project (repo: https://github.com/natstar93/bookmark-manager-fc)

When I navigate to my localhost server at URL http://localhost:9292/links I get an error page with the following error:
DataMapper::RepositoryNotSetupError at /links
Adapter not set: default. Did you forget to setup?

Here is my controller code for the /links page
```
  get '/links' do
    @links = Link.all
    erb :index
  end

  post '/links' do
    Link.create(url: params[:url], title: params[:title])
    redirect to('/links')
  end
```
Strangely, the /links/new page is working as expected. Here is the code for the /links/new page:
```
  get '/links/new' do
    erb :new
  end
```
Thanks in advance guys!
Nat

**Comment by natstar93** [comment]
Added ```require './app/data_mapper_setup.rb'``` to the app.rb file and everything is now working

**Comment by ptolemybarnes** [comment]
So what was the problem?
