### ISSUE TITLE
Faraday SSL Error with Google OAuth2

### ISSUE THREAD

**Issue by chidumaga** [makersacademy/slack-overflow#36]
@AlexHandy1 and I are running into some significant problems with Google OAuth and after ploughing through errors for 1hr+ have now hit a Faraday SSL error which seems to want us to edit low-level SSL cert files. 

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Feels like we are off track - would appreciate some help from coaches (or someone who has successfully set-up google authentication)

**Comment by chidumaga** [comment]
We have added this to our config/initializers/omniauth.rb:

```Rails.application.config.middleware.use OmniAuth::Builder do
 provider :google_oauth2, ENV['YT_CLIENT_ID'], ENV['YT_CLIENT_SECRET'],  :client_options => {:ssl => {:ca_file => '/etc/pki/tls/certs/ca-bundle.crt'}, :scope => 'userinfo.profile,youtube'}, provider_ignores_state: true
end``

It began with this issue: https://github.com/mkdynamic/omniauth-facebook/issues/73
Tried to resolve by adding `provider_ignores_state: true ` to config/initializers/omniauth.rb
We also looked into: http://stackoverflow.com/questions/22386149/why-am-i-getting-csrf-detected-with-omniauth-and-google and https://github.com/intridea/omniauth-oauth2/issues/58

**Comment by tansaku** [comment]
@chidumaga @AlexHandy1 can you put a link to your repo (relevant branch or commit ideally) in here as well - just trying to get you to follow best practise: https://github.com/makersacademy/course/blob/master/pills/asking_questions_online.md

**Comment by chidumaga** [comment]
Here's the link to our branch @tansaku https://github.com/snapchidu/stitchvid/tree/37-file-upload

**Comment by DanielJohnston** [comment]
As an update, Chidu and Alex resolved this after a couple more hours of work upon discovering that the main sticking point was running the code on localhost - uploading to Heroku resolved all problems.

**Comment by spike01** [comment]
Fixed on localhost:

From the Devise docs (https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview):

On OS/X, for development only, it may be easiest just to disable certificate verification because the certificates are stored in the keychain, not the file system:
```
require "omniauth-facebook"
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE if Rails.env.development? 
config.omniauth :facebook, "APP_ID", "APP_SECRET"
```
A deeper discussion of this error can be found here: https://github.com/intridea/omniauth/issues/260

**Comment by spike01** [comment]
You should always be able to develop on localhost, having to constantly deploy to Heroku is pretty hellish

**Comment by AlexHandy1** [comment]
Now working on local host to - thanks!

**Comment by pskrz** [comment]
possible issue with rvm http://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html
