### ISSUE TITLE
Google Location Autocomplete Issue

### ISSUE THREAD

**Issue by MollieS** [makersacademy/slack-overflow#38]
We are trying to get a search field with autocomplete for an address.  We are getting an error `geolocate is not defined` in the console.

Here is a link to our github.  Sorry it is a bit messy, we haven't reached refactor stage yet.

https://github.com/bagolol/errand_runner/tree/autocomplete

We are working from this example: 

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

Thanks in advance.

Anna and Mollie

**Comment by sdorunga1** [comment]
@MollieS still a problem?

**Comment by MollieS** [comment]
@sdorunga1 all fixed.  We were trying to call the function with onclick rather than ng-click, so we changed it to ng-click and now it works.

**Comment by tansaku** [comment]
good show @MollieS shall we close this then?
