### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by MollieS** [makersacademy/slack-overflow#41]
Hello Everyone,

We are having some CORS issues, and we are struggling to solve them so if anyone can help, we'd be very grateful.

We are currently getting this error: 

`XMLHttpRequest cannot load http://evening-plains-3275.herokuapp.com/users. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 404.`

Previously we were getting the same error but with a different status code, but I can't remember what the status code was.  I think it was 500.  We added lots of headers to our API and it did not help, but we're having a git issue as well which we will try and sort on Monday, but for the mean time we cannot seem to merge our front end code with our back end, so I cannot post the back end code, but I will try to later so that you can see that code.

Anyway, we believe that our $http.post function is using the OPTIONS methods, and our API doesn't know how to deal with anything other than post for that route.  Would that be the cause of a 404 error?  If so, how can we get our $http.post to send a post request rather than use options?  Or allow our /users route to accept options.

Thanks everyone, here's our front end code (still pre refactor)

https://github.com/bagolol/errand_runner/tree/fixing/front-end

**Comment by tansaku** [comment]
@MollieS from a superficial look I'd say that the correct header is not set on the server on heroku ... this would be a good one to look through together step by step

**Comment by MollieS** [comment]
@tansaku I have got it to work using the rack-cors gem.  I'm not sure I quite understand why it works when it did not work before, but it is fixed now.  I am sure the security is not great, and it would be good to look at that.

Here's the rack-cors code I inserted:
https://github.com/bagolol/errand_runner/pull/29/files

**Comment by ptolemybarnes** [comment]
@MollieS Thanks for that solution.
