### ISSUE TITLE
database working in rspec tests but fails on sinatra!

### ISSUE THREAD

**Issue by Harxy** [makersacademy/slack-overflow#42]
So, I have a system where the peeps are made and then a user is attached, like so
```  
post '/peep/new' do
    @user = User.get(session[:user_id])
    peep = Peep.new(body: params[:peep])
    peep.user = @user
    peep.save
    redirect to '/peep'
  end
```

this seems to work and all my tests pass. I put the Peeps.all into the erb file like so:

```
<% @peeps.each do |peep| %>
	<li>
	<%= peep.user.username %>: <%= peep.body %>
	</li>
  <% end %>
```

and, like I say, this means that this test passes: 

```
feature 'creating a peep' do
  scenario 'when signed in, I can make a peep' do
    sign_in
    visit '/peep/new'
    fill_in :peep, with: "this is my first peep"
    click_on 'Send'
    expect(page).to have_content "foobar_user: this is my first peep"
   end
end
```

BUT, when I rackup., naviagate to peeps/new and add a peep, I get this error:
```
NoMethodError at /peep
undefined method `username' for nil:NilClass
file: peeps.erb location: block (2 levels) in singleton class line: 5
```

This makes no sense! My Capybara is telling me that it works!

Having looked at the two databases (_test and _development) it does seem that the peep_users in _test is populated with 1, 1 but in _development that connection has not been made..

Does anyone have any idea what might be going on? Thank you!

**Comment by ptolemybarnes** [comment]
I got in there with byebug:
```ruby
[65, 74] in /Users/admin/Documents/Deck/makers-academy/june/paul_chitter/lib/Chitter.rb
   65:     require 'byebug'
   66:     byebug
   67:     @user = User.get(session[:user_id])
   68:     peep = Peep.new(body: params[:peep])
   69:     peep.user = @user
=> 70:     peep.save
   71:     redirect to '/peep'
   72:   end
   73:
   74:   get '/peep' do
(byebug) @user
nil
(byebug) session
{"session_id"=>"9f29ab8361e59e29d9263c931fe1963ddf8c538f6ab2d36e94a818d9c39a7ed9", "csrf"=>"80d3f24e25462f120bdda0a362a4eb2e", "tracking"=>{"HTTP_USER_AGENT"=>"89075fca79fb68f8f513d98f87c80d84072042a3", "HTTP_ACCEPT_LANGUAGE"=>"3aa97f922c68a5b102bef508bd609cf5725890cf"}, "flash"=>{}, "username"=>"ptol"}
```
Seems like the problem is not to do with the database but the way the currently logged in user is being retrieved.

**Comment by Harxy** [comment]
Thanks for looking at it...

Not sure what you mean though. I've byebugged in there and @user is populated and peep.user.username is there...?

**Comment by Harxy** [comment]
So I figured out that the problem was that the only place in my code where the sessions were set was when someone signed in - they weren't set when someone signed *up*. Obviously when I tested, I didn't sign in then sign up - I just signed up.

As a side note, you can byebug into rackup! I had no idea and it totally solved the problem for me.
