### ISSUE TITLE
Chartkick gem and geo_charts

### ISSUE THREAD

**Issue by timoxman** [makersacademy/slack-overflow#43]
I am using the chartkick gem to produce pretty graphs in a Rails app.
I am following the documentation here: https://github.com/ankane/chartkick
I have succeeded in creating pie/bar and line graphs but wish to create a geo_chart.

In my controller I have the following line: (populated with test data, just to try and get it working)
`@location_table_data = [['Chad',400],['France',600]]`

And in my View I have the following lines:
At the top of my page I have included the JS:
`<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>`
And then where I want the map to display I have the following line:
`<%= geo_chart @location_table_data %>`

It does not work, the map displays but contains no data is presented..
<img width="1440" alt="screen shot 2015-07-06 at 8 41 42 pm" src="https://cloud.githubusercontent.com/assets/11789455/8531462/76f10464-241f-11e5-907c-69a08a392511.png">
I think the countries should go different colours.

I can't find a good example of what the input data array should look like and my investigation so far has been around trying to amend the input dataset to different formats using array's, hashes, adding and removing titles, but to no avail. Help much appreciated?

**Comment by tansaku** [comment]
hi @timoxman thanks - can you post a link to your repo - ideally to the specific commit or branch that this is on?

**Comment by timoxman** [comment]
Code is here:
https://github.com/timoxman/Movie-Snaps/tree/9-visits

The actual offending lines are in the dashboard controller: https://github.com/timoxman/Movie-Snaps/blob/9-visits/app/controllers/dashboards_controller.rb 
and the corresponding view: https://github.com/timoxman/Movie-Snaps/blob/9-visits/app/views/dashboards/index.html.erb

**Comment by timoxman** [comment]
The issue was caused by @location_table_data = [['Chad',400],['France',600]] being defined in the incorrect route and hence it was not available to geo_chart
