### ISSUE TITLE
Can't get thumbnail replacement of YouTube videos to work

### ISSUE THREAD

**Issue by DanielJohnston** [makersacademy/slack-overflow#45]
Using example code in an article at http://www.labnol.org/internet/light-youtube-embeds/27941/ I've been trying to improve our site's responsiveness by replacing YouTube video iframes with static thumbnails until they're clicked. However, I've been unable to get the code to work, despite it clearly working on the article itself. I've gradually stripped everything back until I've got a single HTML page containing the styles, scripts and HTML itself. I've hosted the page at https://nameless-fortress-8894.herokuapp.com/test.html as a way of checking it wasn't local hosting causing the problem. Any suggestions on what I should be looking at are welcome. The entirety of the HTML page follows, for reading pleasure:
```
<!DOCTYPE html>
<html>

<head>

	<style>
		.youtube-container {
			display: block;
			margin: 20px auto;
			width: 100%;
			max-width: 600px;
		}

		.youtube-player {
			display: block;
			width: 100%;
			/* assuming that the video has a 16:9 ratio */
			padding-bottom: 56.25%;
			overflow: hidden;
			position: relative;
			width: 100%;
			height: 100%;
			cursor: hand;
			cursor: pointer;
			display: block;
		}

		img.youtube-thumb {
			bottom: 0;
			display: block;
			left: 0;
			margin: auto;
			max-width: 100%;
			width: 100%;
			position: absolute;
			right: 0;
			top: 0;
			height: auto
		}

		div.play-button {
			height: 72px;
			width: 72px;
			left: 50%;
			top: 50%;
			margin-left: -36px;
			margin-top: -36px;
			position: absolute;
			background: url("http://i.imgur.com/TxzC70f.png") no-repeat;
		}

		#youtube-iframe {
			width: 100%;
			height: 100%;
			position: absolute;
			top: 0;
			left: 0;
		}
	</style>
</head>

<body>
	<script>
		(function() {
			var v = document.getElementsByClassName("youtube-player");
			for (var n = 0; n < v.length; n++) {
				var p = document.createElement("div");
				p.innerHTML = labnolThumb(v[n].dataset.id);
				p.onclick = labnolIframe;
				v[n].appendChild(p);
			}
		})();

		function labnolThumb(id) {
			return '<img class="youtube-thumb" src="//i.ytimg.com/vi/' + id + '/hqdefault.jpg"><div class="play-button"></div>';
		}

		function labnolIframe() {
			var iframe = document.createElement("iframe");
			iframe.setAttribute("src", "//www.youtube.com/embed/" + this.parentNode.dataset.id + "?autoplay=1&autohide=2&border=0&wmode=opaque&enablejsapi=1&controls=0&showinfo=0");
			iframe.setAttribute("frameborder", "0");
			iframe.setAttribute("id", "youtube-iframe");
			this.parentNode.replaceChild(iframe, this);
		}
	</script>
	<div class="youtube-container" id="ytplayer">
		<div class="youtube-player" data-id="uPMHzPBrZeI"></div>
	</div>
</body>

</html>
```

**Comment by DanielJohnston** [comment]
Hmm. I'll beautify that and re-upload I think.

**Comment by DanielJohnston** [comment]
I'm working with Charlie on the issue. Got it to run in the browser by manually running the code in the unnamed function. From sticking `console.log()` commands in, it looks like the setup function runs, but the `for` loop in it does not. Trying to figure out why.

**Comment by DanielJohnston** [comment]
Fixed some issues by moving the script until after the HTML, which appears to give the DOM time to instantiate the `<div class="youtube-player">` before the JS code checks it. Live site at https://nameless-fortress-8894.herokuapp.com/test.html now appears to be working on the current code base, which is available at https://github.com/snapchidu/thumbnail-test/blob/master/test.html. Local site is *not* working as it cannot find the YouTube thumbnail or video - appears to be looking for them locally. Trying to figure out what would cause that.

**Comment by DanielJohnston** [comment]
Now displays both online and offline. Tracked offline failure to find files to the code using relative links rather than specifying http or https. The browser was attempting to find links in file:// instead, which wasn't working. Have inserted `http` into the thumbnail and video links to fix. Marking this closed, although it will still take substantial work to integrate this approach into our web application.

**Comment by abhsheksahani** [comment]
http://i.imgur.com/TxzC70f.png is not working what to do

**Comment by abhsheksahani** [comment]
> http://i.imgur.com/TxzC70f.png is not working what to do

I fix this issue use //i.imgur.com/yq7peaM.png on that URL
