### ISSUE TITLE
After git merge thermostat powerSave mode stopped working? Seems to be working in the console, but not when the user interacts with it.

### ISSUE THREAD

**Issue by jackhalltipping** [makersacademy/slack-overflow#46]
Hey guys! 
So this afternoon I merged my branch which had the location services working correctly into my master, which had a more basic version, but with more css. Somewhere along the way I ran into trouble, and now in my current master version everything is working how I want it to be, EXCEPT the powerSave mode. I keep pulling my hair out because I have no idea why it isn't. I was wondering if anyone saw the problem before I jump back to a prior commit and try working from there instead.

Here's a link to my repository https://github.com/jackhalltipping/thermostat (it's the master branch). You have to run it by installing node and then using http-server . from your terminal (this is kind of a pain, so I'll put in some pictures of whats happening below).

Here is evidence of the problem happening:
<img width="714" alt="screen shot 2015-07-09 at 3 15 12 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597624/7943cdc4-264e-11e5-8d38-f173d42b8a8e.png">

This is my main thermostat function that has powerSave defined in it:
<img width="339" alt="screen shot 2015-07-09 at 3 19 25 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597627/79445e10-264e-11e5-9442-e612dfd3923b.png">

This is my function in my thermostat.js file that does successfully change the mode in the console:
<img width="445" alt="screen shot 2015-07-09 at 3 19 20 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597622/79427db6-264e-11e5-8574-3fa2816fb655.png">

This is in my app.js file which does select the checkbox, and the function inside does work:
<img width="333" alt="screen shot 2015-07-09 at 3 19 10 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597626/7943e71e-264e-11e5-9e3d-077b153a7b08.png">

This is from my index.html file which is the checkbox for powerSave:
<img width="568" alt="screen shot 2015-07-09 at 3 19 34 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597623/794345e8-264e-11e5-9163-42762b288f24.png">

And this is the css associated with the powerSave:
<img width="213" alt="screen shot 2015-07-09 at 3 19 44 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597625/7943bf14-264e-11e5-92e9-caebb99ec824.png">

Thanks for the help! I'm sure it's something minor that I've overlooked, but I've been going crazy on this for the past 45 minutes and for some reason can't get it.

**Comment by silvabox** [comment]
Have you checked in the console that the `powerSave` property is changing?  It should be - bought are you updating your UI to remove the `checked` attribute from the checkbox?

**Comment by jackhalltipping** [comment]
This is what is happening in the console to change the property. Do you mean when I run changeMode does my checkbox actually update? 
<img width="439" alt="screen shot 2015-07-09 at 3 36 06 pm" src="https://cloud.githubusercontent.com/assets/12188284/8597981/45d33c52-2650-11e5-886a-cff82df144f7.png">

**Comment by silvabox** [comment]
in:
```
  Thermostat.prototype.increase = function() {
    if (this.powerSave && this.temp < 25) {
      this.temp += 1;
    }
    if (!this.powerSave && this.temp < 32) {
      this.temp += 1;
    }
    this.setColour();
  };
```
you are testing `powerSave` but elsewhere you are referring to it as `powerSaveMode`

**Comment by jackhalltipping** [comment]
Aah I'll give that a shot

**Comment by jackhalltipping** [comment]
Argh I knew it was something simple like that, thank you, sorry!!
