### ISSUE TITLE
Reduce not returning value back to function

### ISSUE THREAD

**Issue by gerard-morera** [makersacademy/slack-overflow#47]
HeyHey!

This is a pice of my code. A some point the `makeFrameSume` calls reduceFrame with some arguments to get them sum. 
This works since if I write `console.log(a+b)` before the return the result is the expected one. The problem is that `makeFrameSume` function does not receive the return. 
```
BowlingCounter.prototype.reduceFrame = function (frame) {
  frame.reduce(function (a,b) {
    return(a + b);
  });
};

BowlingCounter.prototype.makeFrameSum = function (value) {
  this.increaseBallCounterByTwo();
  
  if(value.length === 2) {
    frameSum = this.reduceFrame(value);

    // Here is expected frameSum to equal the return of makeFrameSum

    console.log(this.frameSum)
  }
  else{
   // (...)
  }
 return frameSum;
};

```

**Comment by spike01** [comment]
The inner function in reduceFrame returns a value, but reduceFrame itself has no return.

**Comment by gerard-morera** [comment]
Solved! Thank you very much, was the return.
