### ISSUE TITLE
jQuery button-click failing to cause an array to be displayed in static html page.

### ISSUE THREAD

**Issue by katsuraku** [makersacademy/slack-overflow#48]
Hello,
I'm trying to connect up my bowling challenge business logic (which is in JavaScript) to a static html file. I'm using jQuery in an interface file. 

I have a range of buttons (0-10) for different numbers of pins to be knocked down. When one is clicked I want it to trigger my 'roll' function, and then display the number of pins knocked down. Right now when I click the button, nothing happens - no number displays at all.

The JavaScript business logic needs refactoring, but it all works in the console. When you 'roll' and pass a number of pins in as the argument, that number registers in the 'rollArray', which is where the individual roll scores are housed. I have already tried displaying just one element of the array in case a whole array can't be displayed, and that did not help.

Can anyone advise where I might have gone wrong here? 
thank you :)
K

I'm linking to the repo.
https://github.com/katsuraku/bowling_static

This is an excerpt of the interface file that contains the jQuery:
```var b = new Bowling();
$( document ).ready(function() {

  var showRollScores = function() {
    $("#rolls").html(b.rollArray);
  };

  $("#0").click(function() {
   b.roll(0);
   showRollScores();
  });```

**Comment by spike01** [comment]
Have you opened your console lately? Your code works find, except for one typo.

**Comment by gerard-morera** [comment]
What you mean?

**Comment by katsuraku** [comment]
Hi @spike01 
How do you mean about the console? I was using it the whole time to test all of the JavaScript business logic was working. I also looked at it to try to inspect how the page was working too, although must admit I'm not as confident about how to use it for that or how to use it with jQuery elements. I haven't spotted the typo. I promise I've gone over it so many times. Maybe I'm blind to it now?!

**Comment by spike01** [comment]
Sure, so open bowling.html in a browser (in my case I use Chrome) and press Cmd-option-I (or right click on the page, click inspect element, then click console. At the time that I cloned your repo, your code at that point had a typo that the console immediately flagged up, even providing the line number. If there's a syntax error in a JS file, none of the code in that file will run.

**Comment by katsuraku** [comment]
THANK YOU!

**Comment by katsuraku** [comment]
So, I had inadvertently deleted the last ) at the very bottom of the interface.js file, so the entire 
$( document ).ready(function() { 
was not closed off.
Closing the issue now.
