### ISSUE TITLE
Why different behaviours in the configuration / convention for generation of spec files?

### ISSUE THREAD

**Issue by ptolemybarnes** [makersacademy/slack-overflow#54]
I was helping @TheoLeanse and @5555482 debug an issue they were having:

They were indulging in a bit of "parallel programming" and found that when Natalia ran the following command:
`bin/rails g controller restaurants` it would automagically generate spec files for the controller. When Theo ran it, however, the spec files were not generated. The solution, which we found [here](http://stackoverflow.com/questions/5296560/how-to-rspec-generate-in-rails), was to put the following in `config/application.rb`:
```ruby
config.generators do |g|
  g.test_framework :rspec
end
```

What we weren't able to solve however is why there was a difference in behaviours between Natalia and Theo's codebases. They seemed identical in all respects. I know @DataMinerUK also had this problem.

@silvabox ?

**Comment by DataMinerUK** [comment]
I do not think it automatically generates Rspec files. I think some people on Makers laptops have a global spec_helper file with it configured but it is just a guess.

**Comment by silvabox** [comment]
Is `rspec_rails` in the Gemfile?

**Comment by ptolemybarnes** [comment]
@silvabox Maybe not...
