### ISSUE TITLE
ActiveRecord multiple options with dependent: or validate: validation_method , on:

### ISSUE THREAD

**Issue by DataMinerUK** [makersacademy/slack-overflow#55]
In ActiveRecord models all the documentation has one option for `dependent:` e.g. `dependent: :destroy`.

But what if I want multiple options? Like `dependent: :destroy` and `dependent: :restrict_with_exception`?

I've written a `dependent: :restrict_with_exception, dependent: :destroy` but I'm worried the second on is overriding the first. `dependent: [:destroy, :restrict_with_exception]` does not work.

There seems to be very little available online to enlighten me. I also wanted to do this for validating `on: [:destroy, :update]`

**Comment by ptolemybarnes** [comment]
@DataMinerUK link to github repo?

**Comment by DataMinerUK** [comment]
Turns out multiple options with `dependent:` makes no sense and multiple options with `on:` in reference to `validate` is not possible even thought it would be useful, such as using the same validation method for `:update` and `:destroy` (although it appears as if you cannot validate on destroy anyway). Looks like multiple options is not a thing.

@ptolemybarnes I don't have any code that refers to the above as this is just a general wonderment. Seeing as I have not committed broken code you won't find my trials and tribulations on github

**Comment by ptolemybarnes** [comment]
Okay, I guess what I wanted was some kind of context as to why you needed multiple options. I would expect there to be a failing test in your codebase that was driving you to implement multiple options.
