### ISSUE TITLE
Rails & database issue

### ISSUE THREAD

**Issue by MassimilianoMura** [makersacademy/slack-overflow#56]
Hi there,

I'm doing the instagram-challenge and I having a problem; I want to add in my photos' table  a column  with the user id that posted that photo, so I will be able to add the feature that only that user can delete the photo.

This is what I did in the console:

![screen shot 2015-07-25 at 18 02 17](https://cloud.githubusercontent.com/assets/11021928/8890513/666d0f44-32fb-11e5-9b1c-b4015d3f17a3.png)

This did add the user_id column in my photo table but the column is empty or NULL if a look inside PSequel app (obviously I created a new user AFTER add the column)

after that I added ` belongs_to :user ` in my photo controller and `has_many :photos ` in my user controller (shold not be already created by rails migrations??) but it's still not working

my repo: https://github.com/MassimilianoMura/instagram-challenge

could you help me?

**Comment by DataMinerUK** [comment]
Massi, you needed to add the associations to your models *before* you did your migration. Your migration file will not build a belongs_to association correctly without a corresponding has_many. So you models need to be created and your associations in place before you generate the migration. 

To rectify things I would delete your last migration file (doing your association incorrectly). I would drop your databases. Create them again. Rake db:migrate and then do your migration for the belongs_to association

**Comment by DataMinerUK** [comment]
Actually there's no need to drop the database. Just do rake db:migrate VERSION=[the version before your issue]

**Comment by sdorunga1** [comment]
@MassimilianoMura works fine for me from your application. Try a migration rever like nicola said, and if not do a `rake db:drob`. Also is the user saved?(just troubleshooting)

**Comment by MassimilianoMura** [comment]
Thanks, I tried your solutions but they wasn't working, very weird (I think because I had my database running in the server, I recognised it later), so I did this:

1) I deleted from my projects all the migrations file I did not like ( yesterday I tried a lot of different way to fix my problem, so I had a lot of wrong migrations )


2) ``` DROP DATABASE "instagram-challenge_development"; ``` inside psql console (without double quotes it doesn't work, because the - inside the name)

3) ``` bin/rake db:create  ```

4) ``` bin/rake db:migrate ```

now, with my 'new' database with the right migrations, I'm going to try to add my column as Nicola said, adding the associations to my models before  I do the new migration

**Comment by MassimilianoMura** [comment]
1) I'm adding ```belongs_to :user ```inside my photo controller

2) I'm adding ``` has_many :photos ``` inside my user controller

3) ```bin/rails g migration AddUserIdToPhoto user:belongs_to ```

4) ``` bin/rake db:migrate ```

restart server, add a new user, add a photo but is still not working, the column user_id inside photo is empty

**Comment by MassimilianoMura** [comment]
PROBLEM SOLVED:

I had a mistake inside my photo_params helper method, I wasn't passing accurately the id photo

now, this works fine:

```ruby
 def photo_params
    params[:photo][:user_id] = current_user.id
    params.require(:photo).permit(:title, :image, :user_id)
  end 
```

**Comment by sdorunga1** [comment]
:+1:
