### ISSUE TITLE
Rails - which path to specify for link_to 'Likes'

### ISSUE THREAD

**Issue by katsuraku** [makersacademy/slack-overflow#57]
Hi there,
I'm currently adding the 'likes' feature to my instagram-challenge. I have a 'Like' link in my pictures index view. But I'm having some trouble figuring out what the path for this link should be. I'm trying to match it to the create method in the likes controller, so currently I have this (see last line of snippet):

` - if @pictures.any?`
`  # - @pictures.each do |picture|`
   `##  =image_tag picture.image.url(:thumb)`
   `## %h2= picture.caption`
  `##  %h2= picture.user`
  `##  %p= pluralize picture.likes.count, 'like'`
  `##  - picture.comments.each do |comment|`
     `###   %h3= comment.my_comment`
   `##  %h2= link_to "Comment", new_picture_comment_path(picture.id)`
   `##  %h2= link_to "Like", pictures_likes_path(picture.id) `
This is giving me this error:
` Failure/Error: click_link 'Like'`
` AbstractController::ActionNotFound: The action 'index' could not be found for LikesController`

I'm sure I have to specify one of the create or new route for likes, which are:
`                         POST     /pictures/:picture_id/likes(.:format)             likes#create`
`new_picture_like GET      /pictures/:picture_id/likes/new(.:format)         likes#new`

I've also tried `new_picture_like_path(picture)` without success.

I don't want there to be an index view for likes - I want the create method to increment them and to display the number of likes in the main pictures index view. 
Can anyone advise how I can achieve this?

this is a link to my repo as well
https://github.com/katsuraku/instagram-challenge.git

many thanks
Kirsten

**Comment by ptolemybarnes** [comment]
Hey Kirsten! On my phone so can't test this myself, but I think that you need to have your link be a form with a submit button, rather than a link. A link will always make a get request.

**Comment by DataMinerUK** [comment]
I haven’t got to that yet, adding comments first. But I would just add a column to my pictures for number of likes and have a link that updates the picture model by adding 1 to that column. And that property is what you display on the page i.e. I wouldn’t make another model/controller at all (edited)

So the path would be something like `picture_path(picture), method: :put` or `picture_path(picture), method: :patch`. I’m not sure what the difference is between put and patch. Best google it. And in the picture controller you would update that image

**Comment by katsuraku** [comment]
just replied to nicola on slack!
thanks ptolemy, i'll try that out.

**Comment by sdorunga1** [comment]
@katsuraku you might also want to give this a look https://github.com/makersacademy/course/blob/master/rails/yelpv3.md#using-ajax-to-update-endorsements-in-real-time which is a way of doing it without page refresh

**Comment by katsuraku** [comment]
Issue is now resolved. I used a button instead as found out they default to posts.

**Comment by katsuraku** [comment]
thanks stefan, will try to move on to that part!
