### ISSUE TITLE
Rails Rspec testing a row in the database has been updated

### ISSUE THREAD

**Issue by DataMinerUK** [makersacademy/slack-overflow#59]
I've been looking online and there is not much information on using Rspec to test if a record in a has been updated.

I've tried `expect{ find("p a").click }.to change{ image }` where `image` is a FactoryGirl image but I get the following error:

```bash
expected result to have changed, but is still #<Image id: 73, description: "Fatty", created_at: "2015-07-26 00:10:03", updated_at: "2015-07-26 00:10:03", picture_file_name: "fatty.jpg", picture_content_type: "image/jpeg", picture_file_size: 308520, picture_updated_at: "2015-07-26 00:10:00", user_id: 121, likes: 0>
```

Although `find("p a").click` called the update method in the controller which changes `image` it looks like the change block is executed before the expectation block so I'm not looking at the new updated image.

**Comment by DataMinerUK** [comment]
Actually the order of execution I may have gotten incorrect. I've used byebug to step through an my `image` and `image.likes ` does not change. In the browser and database I have checked it does change and `expect(page).to have_content '1'` passes the test. And checking `image.likes` directly does not work

```bash
Failure/Error: expect{ find("p a").click }.to change{ likes }.by(1)
       expected result to have changed by 1, but was changed by 0
```

**Comment by sdorunga1** [comment]
Not quire sure why it's not working, but again, you should generally be testing what changes happen for the end-user as that's what that feature test is for
