### ISSUE TITLE
Rails - issue with image uploads: 'no route matches for images/thumb/missing.png'

### ISSUE THREAD

**Issue by katsuraku** [makersacademy/slack-overflow#60]
Hi there
In the instagram-challenge, I've just modified my likes feature so that the button click will update the like count using jquery. But since I did this (and started using poltergeist and data_cleaner) I'm getting this error which I can't shift:
`Failure/Error: Unable to find matching line from backtrace`
 ` ActionController::RoutingError: No route matches [GET] "/images/thumb/missing.png"`

What I've tried so far:
1. I looked online and followed some advice which said you need to create an image file at app/assets/thumb called missing.png. Doing that didn't change the error. 
2. Thought about whether it has something to do with the default url here in the pictures model (snippet below) but can't find an answer on how I might be able to change that to help it.

`class Picture < ActiveRecord::Base`
 ` has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"`
  `validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/`

Also tried this:
I thought I might get around it temporarily by getting rid of any entries that don't have a picture attached:
I tried destroying any entries in the DB which had no image attached - didn't help.
Also in my test I have an entry being created without an attached image:
 ` before do`
    `user = User.create email: 'kirsten@jones.com', password: 'kjkjkjkj', password_confirmation: 'kjkjkjkj'`
    `user.pictures.create(caption: 'Amazing friggin caption')`
 ` end`
I tried to find out how to create it with an image attached but haven't found an answer yet. And I'm not sure if this is a proper fix anyway.

This is link to my repo
https://github.com/katsuraku/instagram-challenge.git
Any advice much appreciated!
Kirsten

**Comment by dwatson62** [comment]
Hey Kirsten I keep getting that one as well. It is to do with that :default_url in the Photo model. It is looking for a default image at that route for when nothing is uploaded, and that particular route doesn't exist which is why the error comes up. So far I have just been changing my default path for an image I do have in my public/images folder (bond.png), which for me is :default_url => "/images/bond.png" I'm not sure of the proper way to do it with missing.png though, so I'll still be keen to find out.

**Comment by sdorunga1** [comment]
@katsuraku what you tried should mostly work. Maybe adding it to the bucket, if you are using S3, would help? If not Daryl's solution is perfectly fine.

**Comment by katsuraku** [comment]
@sdorunga1 hey, i havent moved to S3 yet. @dwatson62 's solution seems to have worked.
@dwatson62 I should probably close the issue, or do you want me to leave it open in case someone knows how to do it with the missing.png?

**Comment by dwatson62** [comment]
Yeah you can close this one
