### ISSUE TITLE
Rails Capybara not finding the right element using CSS selectors

### ISSUE THREAD

**Issue by DataMinerUK** [makersacademy/slack-overflow#62]
Test is failing on this line with `Capybara::ElementNotFound: Unable to find css '.comments li:first a:last':`

```
find('.comments li:first a:last').click
```

The above worked in JQuery in the browser to pull out the correct element. The part of the view I am looking to find is:

```HTML
  <div class="comments">
    <ul>
      <% @image.show_comments.each do |comment| %>
      <li><%= link_to comment[1], user_path(comment[0].user_id) %><%= link_to '&#x2421;'.html_safe, image_comment_path(@image, comment[0]), method: :delete %></li>
    <% end %>
  </ul>
 </div>
```

Here is the [repo](https://github.com/DataMinerUK/instagram-challenge) for @ptolemy's sake. I have been finding it difficult to get Capybara to select the correct elements on the page throughout this challenge.

**Comment by ptolemybarnes** [comment]
@DataMinerUK Can you repost the view as the HTML that it compiles to? I'm trying to test this out but can't get your code to run because of the issue with encoding (see my comment on your PR).

**Comment by ptolemybarnes** [comment]
In general avoid targeting elements like `find('.comments li:first a:last').click` as this is highly likely to break in future versions of your app. It would be cleaner to tag that link with an id so you might get something like `find('.comments li:first a#whatever').click

On your actual issue, it's hard to debug as I don't have access to the code that was failing. In future, it might be better to branch out with the failing code, commit and post a link to that branch.

**Comment by ptolemybarnes** [comment]
@DataMinerUK did you figure this out?
