### ISSUE TITLE
Angular: understanding beforeEach statements with module and inject

### ISSUE THREAD

**Issue by katsuraku** [makersacademy/slack-overflow#63]
Hi all
We are working on the github profile project in Angular. We are writing a test for a factory and trying to understand how some lines of code in the below snippet work:
1. The first beforeEach statement seems to either create or refer back to a module - which one is right?
2. The second beforeEach statement we think injects the Search factory into something. We are wondering how the code knows where that should be injected, and where it is in fact injected.

``` javaScript
describe('factory: Search', function() {
  var search;
  beforeEach(module('GitUserSearch'));
  beforeEach(inject(function(Search) {
    search = Search;
}));
```

Can anyone help with this?
This is a link to the repo:
https://github.com/katsuraku/github_profiles_angular

thanks 
Kirsten

**Comment by sdorunga1** [comment]
So the first before each with the `module` just loads your application as it doesn't get set up by default. (When you do `module` with 2 arguments it creates a new one, with 1 argument it just loads an existing one) 

We use `inject` to get access to our service, in this case `Search`, you can read more about how the injector works [here](https://docs.angularjs.org/api/auto/service/$injector) The reason behind using it is explained [here](https://docs.angularjs.org/guide/unit-testing) under `Testing a controller`

**Comment by katsuraku** [comment]
thank you @sdorunga1 :)
