### ISSUE TITLE
Instagram Challenge: test passing once and failing another time?

### ISSUE THREAD

**Issue by jackhalltipping** [makersacademy/slack-overflow#64]
I just had my AH 1 to 1 about instagram challenge, to try and fix an issue I've been having, with no success. First, here is a link to my repo.

https://github.com/jackhalltipping/instagram-challenge

Basically I have a feature test where the user uploads a picture, which passes.

<img width="590" alt="screen shot 2015-07-29 at 2 52 18 pm" src="https://cloud.githubusercontent.com/assets/12188284/8959285/da7758aa-3601-11e5-9289-3314cb6d0445.png">

I then have another feature test to check if a picture can be liked. 

<img width="635" alt="screen shot 2015-07-29 at 2 52 25 pm" src="https://cloud.githubusercontent.com/assets/12188284/8959286/da77b052-3601-11e5-8d9a-1417209c06ab.png">

The feature test is the exact same as the uploading test until the last line or two. After running byebug I've found that the likes test is failing when I try and post a photo (NOT AT THE LIKING BIT), but the prior test where I simply test if I can upload a photo is passing. Up until the likes line the tests are exactly the same.

<img width="766" alt="screen shot 2015-07-29 at 2 50 59 pm" src="https://cloud.githubusercontent.com/assets/12188284/8959284/da5d7a20-3601-11e5-8ce5-cc53e48cb182.png">

Here is the error I am getting:
<img width="611" alt="screen shot 2015-07-29 at 2 55 52 pm" src="https://cloud.githubusercontent.com/assets/12188284/8959307/f617039e-3601-11e5-8aac-6747c5b81f26.png">

I've tried commented out the upload test while running the like test to make sure it was not an error with a picture already being uploaded, and I've tried doing things like rebuilding my database in between rspec calls.

Any help would be appreciated, cannot figure out why uploading works in one test and not in the next.

**Comment by jackhalltipping** [comment]
Ptolemy came to my aid and cloned my repo, and did not see the same errors I was getting when he ran rspec. The test that was failing for me, passed for him. 

The biggest thing we noticed was that disabling javascript for the failing test caused the params to be populated with the ActionDispatch::Http::UploadedFile object. Whereas when js was enabled, the params were empty. What's strange is that the process of uploading doesn't use javascript.

We haven't found a solution after going through the code for about a half an hour or so.

**Comment by dwatson62** [comment]
I noticed that the javascript driver does not like uploading images either, the params are always blank when js: true is on. I tried adding an extra string field to the form, and it will collect that but not the image. If you put byebug on and manually intervene by uploading an image it will work, so I tried increasing the default wait time but no luck either.

I guess as a temporary work around you can upload an image in a before block and then test just the likes on its own with js: true

**Comment by ptolemybarnes** [comment]
We didn't fully get to the bottom of this. Feel free to reopen if you encounter the issue again.
