### ISSUE TITLE
Unable to host Sinatra app on Heroku

### ISSUE THREAD

**Issue by natstar93** [makersacademy/slack-overflow#65]
I am trying to host a Sinatra angular app on heroku but am getting a lot of npm ERR! errors when I try and push it up.

```
2015-07-30T14:37:36.489702+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-07-30T14:37:36.490565+00:00 app[web.1]: npm ERR! npm  v2.11.3
2015-07-30T14:37:36.489098+00:00 app[web.1]: npm ERR! Linux 3.13.0-49-generic
2015-07-30T14:37:36.491009+00:00 app[web.1]: npm ERR! missing script: start
```
I think the problem is to do with a missing npm start script. The scripts part of my package.json file looks like this:

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "config" : { "port" : "3000" }
  },
```
My repo is: https://github.com/natstar93/github-profile

Thanks,
Nat

**Comment by spike01** [comment]
https://github.com/makersacademy/course/blob/4061b6d396fa6d77956fc48e5c1f2590e2dc1efe/pills/deploying_angular_sinatra.md

**Comment by natstar93** [comment]
@spike01 I did all this setup earlier before my first attempt to push

**Comment by natstar93** [comment]
@spike01 I have now managed to host this. I had some issues with the rack setup. I will post a full solution shortly

**Comment by spike01** [comment]
Glad to have been of no help!

**Comment by ptolemybarnes** [comment]
I guess [here](http://natstar93.github.io/week7/2015/07/20/day-31.html) is the full solution
