### ISSUE TITLE
Bower_components and node_models directories not building

### ISSUE THREAD

**Issue by DataMinerUK** [makersacademy/slack-overflow#66]
I've cloned a Gitprofile to my local machine. I've run `bower install` and `npm install`. This has installed the dependencies but I do not have `bower_components` or `node_module` directories.

Not sure how to get them to build.

**Comment by ptolemybarnes** [comment]
@DataMinerUK Link to repo?

**Comment by DataMinerUK** [comment]
Just a atom .gitignore issue. Did not appear in the sidebar
