### ISSUE TITLE
CI failing for instagram challenge: Selenium::WebDriver::Error::WebDriverError:

### ISSUE THREAD

**Issue by katsuraku** [makersacademy/slack-overflow#67]
Hi
My instagram challenge CI is failing. It looks like there's a problem with using Selenium but I'm not sure how to fix it.
thanks
Kirsten

**Comment by dwatson62** [comment]
Easily fixed. Add this to your .travis.yml
```before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start```

This setups travis to run selenium tests using a firefox browser, from their documentation http://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by ptolemybarnes** [comment]
@dwatson62 nice :+1: I was going to suggest switching to Chromedriver, but that looks much easier.

**Comment by dwatson62** [comment]
I haven't tried Chromedriver actually, how does that work?

**Comment by katsuraku** [comment]
@dwatson62 cool thanks :) CI has now passed
