### ISSUE TITLE
service instantation

### ISSUE THREAD

**Issue by gerard-morera** [makersacademy/slack-overflow#69]
hi!
I create this service:
```
toDoModule.service('toDoService', function () { 
  var currentState = false

  this.state = function (newState) {
    if(typeof newState !== "undefined"){
      currentState = newState;
    };
    return currentState;
  };
  this.message = function(newMessage) {
    if(typeof newMessage !== "undefined"){
        this.thought = newMessage
    };
    return this.thought;
  }
})
```
then, in the controller:

```
toDoModule.controller('toDoController', ['toDoService', function(toDo) {
  var self = this
  var index;
  self.toDos = [];

  self.insertToDo = function() {
    toDo.message(self.newMessage)
    
    self.toDos.push(toDo)
  };
```
I was expecting that every toDo would be a new instance of the service but it turns out it returns same object. Do I miss anything?
Thanks!!

**Comment by sdorunga1** [comment]
No you did not miss anything. But it's working the way it's intended to. https://docs.angularjs.org/guide/services This returns singletons, so every time you use it it will return the same service object

**Comment by gerard-morera** [comment]
Thanks Stefan. So shall I just use it as a normal function and instantiated every time I need it? If have to be done this way, where I put it?

**Comment by sdorunga1** [comment]
In this case you'd use the service with your storing array so that you can share the tasks, as well as code that formats it the right way. But don't worry too much about it, if it gets too confusing just build it out in the controller and extract out some stuff once you've figured out what you're doing.

**Comment by gerard-morera** [comment]
thanks Sf
