### ISSUE TITLE
Setting up postgres on Heroku

### ISSUE THREAD

**Issue by RichardCharman** [makersacademy/slack-overflow#70]
Hey

I've deployed the first stage of my bookmark_manager app to Heroku (it racks up fine btw). I then added the Heroku Postgres datatbase add-on in the app page...
![heorku postgres](https://cloud.githubusercontent.com/assets/12716756/9220577/72651e52-40db-11e5-903e-9d1fd1f8a253.JPG)

...but I still get an application error when trying to run it. I'm sure there are probably some additional steps I need to take to connect the app to the database but after hours of googling I just can't find it. Has anyone faced this issue? And could you give me a nudge in the right direction please.

Thanks

**Comment by sjmog** [comment]
Wooo slackoverflow!

A couple of comments:

- Nice screenshot! You've told me what you've done :+1: 
- You say 'I get an application error when trying to run it': thanks for telling me when it happens, but:
  - What is the error? I need a stack trace here! You can use triple-backticks (`` `) to paste a code block.
  - What does 'trying to run it' mean? `rackup`? `shotgun`? `ruby server.rb`? Visiting the heroku app online?

**Comment by katylouise** [comment]
Hey, have you changed your datamapper setup file to have this line: 
```DataMapper.setup(:default, ENV['DATABASE_URL'] || "postgres://localhost/bookmark_manager_#{env}")```

**Comment by sjmog** [comment]
Great title, too :+1:

**Comment by RichardCharman** [comment]
Thank you both. I will check and get on it. Woohoo!

**Comment by sjmog** [comment]
As an addition to @katylouise 's suggestion:

When DataMapper sets itself up, it needs a URL for a database (usually one starting with `postgres://`, like `http://` for web connections).

At the moment, Katy has guessed your Database is looking for a database at `postgres://localhost/databasename`. But you're on Heroku, not localhost!

She suggests using `ENV['DATABASE_URL']` preferentially to the `localhost` URL. But what is `ENV`? And where is `DATABASE_URL` from? These are things to find out now ;)

**Comment by RichardCharman** [comment]
They are indeed. And I will @sjmog .
But it works!!! Thank you @katylouise

**Comment by sjmog** [comment]
Woo! Don't forget to close the issue once you're done with it - you can still retrieve closed issues from the 'issues' sidebar, removing the filter `is:open`.

**Comment by RichardCharman** [comment]
I'll do it now. Thanks again.
