### ISSUE TITLE
Trouble using layout.erb file. Does it need to be required somewhere?

### ISSUE THREAD

**Issue by ojlamb** [makersacademy/slack-overflow#71]
I've created a layout.erb file for the bookmark manager app. 

All documentation says Sinatra looks at the views/layout.erb by default..

My layout page is straight out of the book mark manager tutorial:

    <!DOCTYPE html>
    <html>
       <head>
        <title>Bookmark Manager</title>
      </head>

      <body>
        <% if current_user %>
          Welcome, <%= current_user.email %>
        <% end %>
        <%= yield %>
      </body>
    </html>

**Comment by Aftermaths** [comment]
Did you use rspec-sinatra gem?

**Comment by ljones140** [comment]
How exactly is it not working?

**Comment by reteshbajaj** [comment]
I think I know the problem... its not rendering right??

Assuming you've done the helper method?

dude in your app.rb (or whatever your controller is called) make sure that your post '/users' method looks like this:

  post '/users' do
    user=User.create(email: params[:email],
                    password: params[:password])
    session[:user_id] = user.id
    current_user = User.get(session[:user_id])
    redirect to('/')
  end

That last redirect to MUST be after current_user does its thing other wise your helper is not setting the current_user!

**Comment by ojlamb** [comment]
Thank you reteshbajaj. that was it!

**Comment by silvabox** [comment]
Gents, I'm concerned there's a red herring:
`current_user = User.get(session[:user_id])` is redundant - can you check this?
