### ISSUE TITLE
Factory Girl factories with Many to Many relationships

### ISSUE THREAD

**Issue by ljones140** [makersacademy/slack-overflow#72]
We are trying to use Factory Girl to make factories of models which have many to many relationships.

We are working on bookmark manager project. We are trying to create tag and link factories so that when called in our tests the link gets inserted/created on the database and the related table with the tag also gets populated.

here is the code from the factory:
```  
  factory :tag do
    name "education"
  end

  factory :link do
      url 'http://www.makersacademy.com'
      title 'Makers Academy'
      tags {[FactoryGirl.create(:tag)]} #unsure of this syntax?
  end
```
Tag model
```
class Tag

  include DataMapper::Resource

  property :id, Serial
  property :name, String

  has n, :links, through: Resource

end
```

link model
```
class Link

  include DataMapper::Resource

  property :id,     Serial
  property :title,  String
  property :url,    String

  has n, :tags, through: Resource

end
```

We are trying to call in the test _spec.rb file with 
```let(:tag) { create(:tag) }```
also tried
```FactoryGirl.create(:link, :tags => [:tag])```

neither work.

The error we have is from the rspec test saying the contents of the link 'makers academy. etc are not showing on the page.

Thanks

Lewis

**Comment by ptolemybarnes** [comment]
Hey @ljones140 thanks for the issue: it's nice and clear what the problem is. The easiest solution to this might be to do:

```ruby
# /test_spec.rb
link = create(:link)
link.tags << create(:tag)
link.save
```

**Comment by ljones140** [comment]
Hi @ptolemybarnes  thanks for responding. Your solution does work in tests where I only use one factory however I have issues when using in a test where I have to use two factories to insert 2 records in the database. I have this test below

```
  scenario 'I can filter links by tag' do

    link = create(:link_bubble)
    link.tags << create(:tag_bubble)
    link.save
    link_1 = create(:link_zombo)
    link_1.tags << create(:tag_bubble)
    link_1.save

    visit '/tags/bubbles'
    within 'ul#links' do
      expect(page).not_to have_content('Makers Academy')
      expect(page).not_to have_content('Code.org')
      expect(page).to have_content('This is Zombocom')
      expect(page).to have_content('Bubble Bobble')
    end
  end
```

Here I am using factories that inherit from *:link* and *:tag* . My test is failing as "This is Zombocom" is not found in the text. If I run the test with onlt one of the factories (either :link_bubble or :link_zombo) with only their respective expect to have content test the tests will pass. My factoy code is below

```
............
  factory :link do
    url 'http://www.makersacademy.com'
    title 'Makers Academy'

    factory :link_bubble do
      url 'http://www.bubble-bobble.com'
      title 'Bubble Bobble'
    end

    factory :link_zombo do
      url 'http://www.zombo.com'
      title 'This is Zombocom'
    end
  end


  factory :tag do
      name "education"

    factory :tag_bubble do
      name "bubbles"
    end
  end
end
..........
```

**Comment by ptolemybarnes** [comment]
@ljones140 there could be a lot of reasons for that. Could you post a link to your repo with the failing test? (You can checkout and push a new branch, call it 'bug-fix' if you like, if don't want to commit to master with a failing test).

**Comment by ljones140** [comment]
Hi @ptolemybarnes the repo is here:

https://github.com/ljones140/bookmark_manager-1/tree/factorygirlissue

I made a branch called factory girl issue. 

thanks for you help

**Comment by ptolemybarnes** [comment]
@ljones140 It's because here:
```ruby
#/test_spec.rb
  scenario 'I can filter links by tag' do

    link = create(:link_bubble)
    link.tags << create(:tag_bubble) # first tag
    link.save
    link_1 = create(:link_zombo)
    link_1.tags << create(:tag_bubble) # second tag
    link_1.save
# etc
```
2 tags are being created. Then the controller is only pulling out the Links associated with the first tag. If you do something like: 
```ruby
link_1 = create(:link_zombo)
link_1.tags << tag = create(:tag_bubble)
link_1.save
link = create(:link_bubble)
link.tags << tag
link.save
```
It works. Or if you want to be fancy:
```ruby
scenario 'I can filter links by tag' do
    tag = create(:tag_bubble)

    links = [:link_zombo, :link_bubble].map do |link_name|
      link = create(link_name)
      link.tags << tag
      link.save
      link
    end

    visit '/tags/bubbles'

    within 'ul#links' do
      links.each { |link| expect(page).to have_content link.title }
    end
  end
end
```
Got a bit carried away there ^^^ not sure if it's good.

**Comment by ljones140** [comment]
thanks for help @ptolemybarnes your code works and I understand whty my issue was now. As you have explained I was creating 2 instances of the tag.
