### ISSUE TITLE
`<class:Peep>': uninitialized constant Peep::DataMapper (NameError)

### ISSUE THREAD

**Issue by christopheralcock** [makersacademy/slack-overflow#75]
hiya

trying to work on the weekend challenge and very early on in proceedings i've fallen into a world of shit.
anyway, this is clearly something very, very simple, but when I try to run rspec it won't run, giving this error:
`<class:Peep>': uninitialized constant Peep::DataMapper (NameError)

Here's what my peep class looks like:

class Peep

  include DataMapper::Resource

  property :id,         Serial
  property :user,       String
  property :content,    String
  property :created_at, DateTime

end

doesn't seem very controversial  to me.  Have tried it without the DateTime too, in case that's a problem.

Is there some datamapper setup i need to do beyond having it installed and having my databases made?
i think i've required everything in all the relevant places?

**Comment by benhawker** [comment]
Off the top of my head....have you required your model in your data_mapper_setup file? required data_mapper_setup in the your server/app file?

**Comment by christopheralcock** [comment]
thanks @benhawker 
i think i have both of those, but maybe i've cocked up?

my file tree is 
.
├── CONTRIBUTING.md
├── Gemfile
├── Gemfile.lock
├── README.md
├── Rakefile
├── app
│   ├── app.rb
│   └── models
│       └── peep.rb
├── config.ru
├── coverage
├── data_mapper_setup.rb
├── models
│   └── peep.rb
└── spec
    ├── features
    │   └── viewing_links_spec.rb
    └── spec_helper.rb

data_mapper_setup.rb has "require_relative '../app/models/peep.rb'"
and app.rb has "require_relative 'data_mapper_setup'" - they look alright?

**Comment by leon-wee** [comment]
Could it be that you're not requiring the correct files? The spec_helper should require the server file. The server file requires the data mapper file. And the data mapper file requires all the models files. That's how I understood them and got it to work.

**Comment by christopheralcock** [comment]
@leon-wee thanks a lot for spelling it out like that - i've got somewhere now. i at the very least needed to get rid of the '../' in the data_mapper_setup require for the peep model!
