### ISSUE TITLE
Chitter Challenge - NameError / uninitialized constant at users/new

### ISSUE THREAD

**Issue by dregules** [makersacademy/slack-overflow#76]
I am not sure why I'm getting this error on the challenge for Chitter. I also tried to switch off to my latest (running as of yesterday) Bookmark Manager version and it also gives me the exact same problem on the below line:
```
#./app/controllers/user.rb
@user = User.new
```

* I've started off with Modular style - Most recent code has been posted and pushed to my repo for further reference *
https://github.com/dregules/chitter-challenge

 See below the screens when I rackup on both :

![image](https://cloud.githubusercontent.com/assets/1048262/9290533/4691997a-438f-11e5-83fb-08b9ee3fb55e.png)

![image](https://cloud.githubusercontent.com/assets/1048262/9290547/80792586-438f-11e5-8ce8-bf6d672c7029.png)

My current tree looks like this:
![image](https://cloud.githubusercontent.com/assets/1048262/9290585/38063f0e-4390-11e5-8a16-7e6c5e57e816.png)

**Comment by spike01** [comment]
That's... weird. I cloned your repo and ran rackup...

![image](https://cloud.githubusercontent.com/assets/7307631/9290656/d187b84a-4392-11e5-880f-69a4825f752c.png)

**Comment by dregules** [comment]
@spike01 sorry - hadn't pushed. Now's up.  
I added 
`require './app/data_mapper_setup'` to my ./app/chitter.rb and seems to have fixed the problem.. will have a closer look again.
Thanks very much!
