### ISSUE TITLE
Chitter Challenge - Hit a wall with " undefined local variable or method `user' "

### ISSUE THREAD

**Issue by RichardCharman** [makersacademy/slack-overflow#77]
Hey

This has me stumped, and yet I feel as if it should be a simple fix but it's just not happening for me.

I'm trying to implement the sign up for Chitter part.

Here's a link to my current code which is returning the error
https://github.com/RichardCharman/chitter-challenge

Rspec gives me this...

  1) User sign up I can sign up as a new user
     Failure/Error: click_button 'Sign up'
     NameError:
       undefined local variable or method `user' for #<Chitter:0x007f01cf2ad028>
     # ./app/chitter.rb:46:in `block in <class:Chitter>'

etc, which leads me to believe it's something to do with the session ? As on line 46 of app/chitter.rb I have...
    session[:user_id] = user.id

If I hash that out and run the test I get...
 
  1) User sign up I can sign up as a new user
     Failure/Error: expect { sign_up }.to change(User, :count).by(1)
       expected #count to have changed by 1, but was changed by 0
     # ./spec/features/user_management_spec.rb:17:in `block (2 levels) in <top (required)>'

I've been going around in circles and just can't see it, and I believe I've got all the important parts identical to the Bookmark Manager code (at that stage), so if anyone can offer some advice I'd really appreciate it.

Thanks

**Comment by spike01** [comment]
Look at line 43, then at line 46 again, then at line 43.

**Comment by RichardCharman** [comment]
Hey. Thanks.
You mean the @user on line 43 ? If I just change it to user I get the other error result of...
  1) User sign up I can sign up as a new user
     Failure/Error: expect { sign_up }.to change(User, :count).by(1)
       expected #count to have changed by 1, but was changed by 0
..which was my original error, and the one that led me down this rabbit hole!

**Comment by RichardCharman** [comment]
I've updated it all to this....
  post '/users' do
    @user = User.create(email: params[:email],
                password: params[:password],
                name: params[:name],
                username: params[:username])
    @user.save
    session[:user_id] = @user.id
    redirect to('/peeps')
  end
...but I still get the...
  1) User sign up I can sign up as a new user
     Failure/Error: expect { sign_up }.to change(User, :count).by(1)
       expected #count to have changed by 1, but was changed by 0
?

**Comment by spike01** [comment]
A few things to look at:

* your layout is never being used. Why?
* Once you are getting the layout to load, try changing the e-mail you sign up with in your test. You test will pass once, then fail. Why?

**Comment by RichardCharman** [comment]
Thanks. I will look into those issues now.
