### ISSUE TITLE
Password confirmation in user model not working

### ISSUE THREAD

**Issue by dregules** [makersacademy/slack-overflow#78]
I've followed every step from the Bookmark Manager, I've installed and required `dm-validations` where necessary, yet my integration test for password not matching fails unexpectedly. 

My github repo is up-to date with this issue as the last commit
https://github.com/dregules/chitter-challenge

Below's my test in question
``` ruby
scenario 'passwords do not match' do
      user = build(:user, password_confirmation: 'wrong')
      sign_up(user)
      #expect(current_path).to eq 'users/new'
      #expect(page).to have_content 'Passwords do not match, please reenter'
      expect(User.count).to eq 0
end 
```

Below's the code for my user model
```ruby
require 'bcrypt'


class User
  include DataMapper::Resource

  attr_reader :name, :password
  attr_accessor :password_confirmation
  validates_confirmation_of :password
  validates_presence_of :email, :name, :username

  property :id, Serial
  property :name, String
  property :email, String
  property :username, String
  property :password_digest, Text
  #has n, :post

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

```

Below's the code for data_mapper_setup
``` ruby

require 'data_mapper'
require 'dm-validations'

require './app/models/user'

env = ENV['RACK_ENV'] || 'development'


DataMapper.setup(:default, ENV['DATABASE_URL'] || "postgres://localhost/application_chitter_#{env}")


# After declaring your models, you should finalise them
DataMapper.finalize

# However, the database tables don't exist yet. Let's tell datamapper to create them
DataMapper.auto_upgrade!

```

Below's the test result:
![image](https://cloud.githubusercontent.com/assets/1048262/9293819/2ea2609a-4431-11e5-91ed-9d83c8feeb19.png)

**Comment by ljones140** [comment]
Hi Deigo not sure whats wrong. I build my factories in a different way to you and make up a class then inherit the differences down 

```
FactoryGirl.define do
  factory :user do
    email 'test@example.com'
    password '12345678'
    password_confirmation '12345678'
    name 'test user'
    user_name 'test_user_name'

    factory :user_wrong_confirmation do
      password_confirmation 'wrong'
    end
end
```

I then pass :user_wrong_confirmation into the test

**Comment by dregules** [comment]
@ljones140 - Thanks for that!! although factories shouldn't really be the problem here.... See below my point on how to pass through different arguments on the same factory:
```ruby
scenario 'passwords do not match' do
      user = build(:user, password_confirmation: 'wrong')
      sign_up(user)
      #expect(current_path).to eq 'users/new'
      #expect(page).to have_content 'Passwords do not match, please reenter'
      expect(User.count).to eq 0
end 

```
![image](https://cloud.githubusercontent.com/assets/1048262/9293915/012d131e-4434-11e5-82ee-0a5a7e1c996b.png)
 
ANOTHER EXAMPLE, which passes the test:

```ruby
 scenario 'when name is missing' do
      user = build(:user, name: '')
      sign_up(user)
      expect(current_path).to eq '/users/new'
      expect(User.count).to eq 0
end

```

![image](https://cloud.githubusercontent.com/assets/1048262/9293930/73a44eda-4434-11e5-9a99-7b8d636ad260.png)

**Comment by dregules** [comment]
Update: 
It actually works when I rack up, just found out....  So there must be something wrong with that test logic in particular.

![image](https://cloud.githubusercontent.com/assets/1048262/9294622/fd0c6836-444a-11e5-8179-797b47990045.png)

![image](https://cloud.githubusercontent.com/assets/1048262/9294628/19f3a61c-444b-11e5-868a-053876347cf7.png)

**Comment by dregules** [comment]
SOLVED thanks to Sarah! 
fixed my Sign up helper method in the below line
` fill_in :password_confirmation, with: user.password `
to 

 ```ruby
 def sign_up user
    visit '/users/new'
    fill_in :email, with: user.email
    fill_in :name, with: user.name
    fill_in :username, with: user.username
    fill_in :password, with: user.password
    fill_in :password_confirmation, with: user.password_confirmation
    click_button 'Sign Up'
  end

```
