### ISSUE TITLE
Spaghetti code 

### ISSUE THREAD

**Issue by lroliphant** [makersacademy/slack-overflow#79]
We have a serious case of spaghetti code emerging and we still have a lot more camp amenities/facilities to add - can anyone think of a nice way in which we can refactor our current code to remove all the if/else statements, below is an example of one (but there around 30 amenities/facilities so far that need to be added to our view, so you can imagine how messy this is going to get):

```
<% if site.shared_toilets == true %>
  <span class="has-facility">
    Shared toilets
  </span>
<% else %>
  <span class="no-facility">
     Shared toilets
  </span>
<% end %>
``` 

Does anyone have any suggestions of how we can add these amenities/facilities to our campsite view without using multiple if/else statements or in a cleaner way? Ideally something that won’t mean a change to our current site model.

Our github link is as follows:

https://github.com/Triffanys101/camping-app

The code snippet above can be found in our views/vendors/index.html.erb. Ideally we want to address this issue before the spaghetti gets any more messy.

Many thanks in advance.

Lucy

**Comment by ptolemybarnes** [comment]
Hey @lroliphant I have some ideas about how to refactor this: 
- Create a partial to serve as a generic template for campsite's amenities.
- Declare an array of symbols cataloguing campsites' amenities.
- Iterate over that array within the index.erb, yielding to the generic amenity partial on each iteration.

Let's have a look at how to refactor this tomorrow and I can point you in the right direction.

**Comment by lroliphant** [comment]
That would be great thanks - let us know what time works best for you. We have a slight issue in that we want to be able to rename some of the column names of the amenities in the database in the view and also to potentially separate them out into amenities, themes and facilities (if possible, but it isn't essential - just better from a UX perspective).
