### ISSUE TITLE
Autocomplete: Load "login" field from github API response

### ISSUE THREAD

**Issue by rodcul** [makersacademy/slack-overflow#8]
I'm using the example on: http://jqueryui.com/autocomplete/#remote-jsonp

Which loads a datasource like: http://gd.geobytes.com/AutoCompleteCity?q=paris

When trying to get something similar working for github usernames:

https://api.github.com/search/users?q=rodc

I'm unsure how to "preprocess" the data to only return usernames.

```js
$(function() {

    $( "#autocomplete" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "http://api.github.com/search/users",
          dataType: "jsonp",
          data: {
            q: request.term
          },
          success: function( data ) {
            response( data.first );
          }
        });
      },
      minLength: 3,
      select: function( event, ui ) {
        log( ui.item ?
          "Selected: " + ui.item.label :
          "Nothing selected, input was " + this.value);
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
    });
  });

```

**Comment by MollieS** [comment]
Hi Rodney,

We got it working with a loop and two arrays.  Not sure if you had a problem with it returning usernames that did not start with the first letter of the input, but we did, so the fix to that is included in our loop, like this:

```
$('input.username').autocomplete({
   source: function( request, response){

     $.ajax({
       url: "https://api.github.com/search/users",
       data: { q: request.term },
       dataType: "jsonp",
       success: function( data ){
         var arr2 = []
         var arr = data.data.items;

         for(var i=0; i < arr.length; i++){
           var letter = ($('input.username').val())[0];
           var first_letter = arr[i].login[0]
           if(first_letter === letter){
             arr2.push(arr[i].login)
           }
         }
         response(arr2);
       }
     });
   }
});
```

Maybe something similar would work for you?

**Comment by rodcul** [comment]
Thanks @MollieS  - if I copy the code it works but I don't fully understand it, maybe we can go through it tomorrow?

Also would be good to get one of the coaches approach to this problem

**Comment by tansaku** [comment]
@rodcul is this resolved now?  did you get some feedback from coaches in your standup today?

**Comment by rodcul** [comment]
yes @tansaku thx, pending implementation but will post here when it's done
