### ISSUE TITLE
PSQL DATAMAPPER data association issues

### ISSUE THREAD

**Issue by reteshbajaj** [makersacademy/slack-overflow#80]
https://github.com/reteshbajaj/chitter-challenge.git - - - my repo

Since I tried to define the association between user and peeps I can't seem to get them to save on the database and appear in the browser - not sure if it is a database issue or a front end issue. Suspect its the former - any thoughts?? Any help appreciated!

**Comment by sjmog** [comment]
Did you manage to fix this in the end?

A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.
