### ISSUE TITLE
Formatting the date in a PSQL database

### ISSUE THREAD

**Issue by Triffanys101** [makersacademy/slack-overflow#81]
Hello,

I am creating a website were users are asked to enter dates into a form. I am using Ruby on Rails and PSQL for my database and client-server interaction. Currently the date is being formatted in the American style as shown here:

![screen shot 2015-08-17 at 10 41 39](https://cloud.githubusercontent.com/assets/12293015/9302323/a520265c-44cd-11e5-8ee1-121c31a9c356.png)

I have tried the following to change the date but it didn't work:

http://stackoverflow.com/questions/6123484/how-do-i-alter-the-date-format-in-postgres

I was wondering if I need to alter the input or can I just change the output?? At a minimum I need the date to put outputted in the UK style for my vendors, but ideally I want to change the format in the database.

**Comment by dwatson62** [comment]
How does your Rails form look like? You can adjust the format people enter the date in. I used this in our final project so that it was entered into the database in UK style
```
<%= f.fields_for ... do |v| %>
...
<%= v.date_select :date_visited, order: [:day, :month, :year] %>
```

**Comment by Triffanys101** [comment]
Thanks @dwatson62 that worked!
