### ISSUE TITLE
JS Jasmine Testing using spies on getJSON calls

### ISSUE THREAD

**Issue by ljones140** [makersacademy/slack-overflow#82]
Hi 

I am trying to write a feature test using jasmine and jquery to confirm a getJSON request has been made. I know that my getJSON is working as I can see from my website the call is being made in the console network log and I am getting the result of the call to display on my webpage.

I'm making a call to open weather API. This gets JSON which the cod parses to pull out information for the website. My test is checking that the call to the getJSON method is being called however my test is failing with *Expected spy getJSON to have been called*

my test is:

```
#spec/FeatureSpec.js

    it('calls weather API', function() {
      spyOn($, "getJSON");
      expect($.getJSON).toHaveBeenCalled();
    });
```

I think it is failing because the test is running before the API call has been made. Is there a way to get the test to wait for the call to be made before

I am making the API weather call in my appJquery.js file. 

```
#src/appJquery.js

   var weatherCall = function(){
     $.getJSON("http://api.openweathermap.org/data/2.5/weather?q=london&units=metric&APPID=b5d17c3afa857ebbab97b63ae2330336",function(result){
    showWeather(result);
    });
  };

  weatherCall();

   var showWeather = function(result){
   $("#weather").html(("City: "+result.name + " Weather: "+result.main.temp
      +result.weather[0].description ));
   var weatherImage = (result.weather[0].icon)
   $("#weatherImage").html("<img src='http://openweathermap.org/img/w/"+weatherImage+".png' />")
  };
```

repo is here: https://github.com/ljones140/Thermostat-1

**Comment by ljones140** [comment]
I have created a separate branch with this issue so I can continue to work on other features

https://github.com/ljones140/Thermostat-1/tree/spyissue

**Comment by sjmog** [comment]
Did you manage to fix this in the end?

**Comment by ljones140** [comment]
unfortunately not. However I changed the approach of the thermostat so that you had to enter the city and click a button to make the API call and get the weather, That I could test
