### ISSUE TITLE
jQuery testing thermostat - Error: Expected '.temperature' to contain text 20.

### ISSUE THREAD

**Issue by raphlevy** [makersacademy/slack-overflow#86]
![2015-08-21 04 34 01 pm](https://cloud.githubusercontent.com/assets/12574604/9412226/7ed303e0-4822-11e5-8e80-b3cb6f38ec4c.png)

**Comment by sanjsanj** [comment]
What does the .temperature DOM element contain?

**Comment by nikeshashar** [comment]
Have you got a link to your code?

**Comment by sjmog** [comment]
I'm going to close this issue now @raphlevy but the two responses are appropriate - you can't just give a screenshot! A good post says:

1. What you are trying to do
2. The code to do it
3. What the error was

A screenshot doesn't help at all.
