### ISSUE TITLE
Iterating through hash in Javascript - matching keys

### ISSUE THREAD

**Issue by benhawker** [makersacademy/slack-overflow#87]
I am have an issue with a function I have written to iterate through a js hash. I have 2 hashes:

```this.currentOrder = {"item": quantity};```
```this.menu.items = {"Pizza": 1,"Pasta": 2, "Water": 3 };```

I seek to iterate through the currentOrder hash using the for in loop I have written. If a key === to a key in the menu.items hash then it should return the result of multiplying the values from each hash.

Note: I am using the underscore.js library which allows me to access the keys and values with _.keys

`Order.prototype.sumOrder = function() {

	for (var key in this.currentOrder) {
		if (_.keys(this.menu.items) === _.keys(this.currentOrder)) {
			return this.orderTotal = (_values(this.menu.items)) * (_.values(this.currentOrder));
		}
        };
};
`

I have played around with all of this in the console and it seems to be correct syntactically. However it is not returning a result and so I cannot get my test passing. :(

Thanks for any help!

**Comment by dwatson62** [comment]
Not sure if you can iterate through a hash, as they are unordered. How about using an array of hashes?

**Comment by benhawker** [comment]
Thanks @dwatson62 for the input.

Realise the if statement was not required as I had validated the conditional this was asking in a previous method. 

Ended up with the following:

`
Order.prototype.sumOrder = function() {
	console.log(this.currentOrder);
	for (var key in this.currentOrder) {
			this.orderTotal += (this.menu.items[key] * this.currentOrder[key]);
	};
};
`

**Comment by silvabox** [comment]
There is no such thing as a hash in JavaScript.
```
items = {"Pizza": 1,"Pasta": 2, "Water": 3 }
```
is object literal notation.  This creates a new JS object with the properties `Pizza`, `Pasta` and `Water`.

**Comment by benhawker** [comment]
Thanks @silvabox - I had read many SO posts referencing js hashes so assumed they must call it that! Have read http://www.dyn-web.com/tutorials/object-literal/ and understand that. Got it completed with passing tests - https://github.com/benhawker/takeaway_js

**Comment by silvabox** [comment]
It's more likely you want an array of objects as your menu:
```
items = [{name: "Pizza", price: 1}, {name: "Pasta", price: 2}, {name: "Water", price: 3}]
```
