### ISSUE TITLE
Password Reseting 

### ISSUE THREAD

**Issue by GabyML** [makersacademy/slack-overflow#88]
We are trying to reset the password of a user of our site. We are using cucumber for the feature test and this is the error:
  Scenario: resetting password                                          # features/password_reset_spec.feature:19
    Given there is already a user with email "sally@email.com"          # features/step_definitions/web_steps.rb:21
    And that I visit the reset password page with token "OOHRAGTNCKSAK" # features/step_definitions/web_steps.rb:13
    When I fill in "new_password" with "winning"                        # features/step_definitions/web_steps.rb:67
    And I fill in "new_password_confirmation" with "winning"            # features/step_definitions/web_steps.rb:67
    And I click the "Reset Password" button                             # features/step_definitions/web_steps.rb:63
    And I fill in "return_username" with "Sally"                        # features/step_definitions/web_steps.rb:67
    And I fill in "return_password" with "winning"                      # features/step_definitions/web_steps.rb:67
    And I click the "Log In" button                                     # features/step_definitions/web_steps.rb:63
    Then I should see "Welcome, Sally"                                  # features/step_definitions/web_steps.rb:78
      expected to find text "Welcome, Sally" in "The username or password is incorrect!!!!!!! Rola: Genres:" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/web_steps.rb:79:in `/^I should see "([^"]*)"$/'
      ./features/support/database_cleaner.rb:11:in `block in <top (required)>'
      features/password_reset_spec.feature:28:in `Then I should see "Welcome, Sally"'

After debuging with byebug we see that we've changed the password, but the site doesn't allow the user to log in.
This is our compleate code so far: 
https://github.com/GabyML/labweek

Please help :) Thanks!

**Comment by sjmog** [comment]
If you're still interested in an answer to this, I can help - but checkout the [GitHub Markdown guide](https://help.github.com/articles/github-flavored-markdown/) to format this request properly. It's too tricky to read right now!
