### ISSUE TITLE
EJS Template conditional in Express

### ISSUE THREAD

**Issue by benhawker** [makersacademy/slack-overflow#89]
Having a weird issue which we can't figure out from the docs.

We are running Express, with EJS. it was set up with express-generator. We have a simple routing.

```
router.get('/', function(req, res) {
  res.render('index', { title: 'Express' });
});

router.post('/', function(req, res) {
		var name = (req.body.fname + " " + req.body.lname);
		res.render('index', { title: 'Express', username: name });
});
```

Our form is able to post but we have issues with conditional logic when a get request is made on '/', which renders index.ejs.

```
  	<% if(username != nil) { %>
    	<h2><%= username %></h2>
		<% } %>

    <h1><%= title %></h1>
    <p>Welcome to <%= title %></p>
    <form method="post" action="/">
    	First name: <input type="text" name="fname"><br>
  		Last name: <input type="text" name="lname"><br>
  		<input type="submit" value="Submit">
    </form>
  </body>
</html>
```

The error message in the browser is that username is undefined.

We are able to get this working with: 
```<h1><%= typeof username!='undefined' ? username : '' %></h1>```
...however this is super hacky as the h1 element remains on the page whether username is displayed or not.

We have read the EJS docs on Github and read a number of posts about this but have come up with nothing.

Any pointers welcomed!

**Comment by Yorkshireman** [comment]
Just to second my Pair Partner, @benhawker esq. , this is really weird and especially confusing since long-hand ways to do this don't work, such as:  
`<% if(username) { %> <%= username %> <% } %>`  
and neither does this:  
`<%= user.name ? user.name : '' %>`

**Comment by dwatson62** [comment]
You can check that the data is coming through correctly after you submit the form, try a console.log(name) and check the terminal. But I think in this case you might be mixing up your GET and POST requests. The username variable is available on the post route, but you said you're making a get request to '/'.

Also:
```
if(username != nil) 
```
It's Javascript, wouldn't it be null instead of nil?

**Comment by dwatson62** [comment]
Actually disregard that ^^ I just tried your code and got it working. I had to reset the server once though

**Comment by tkeriduN** [comment]
Im trying to do this very same thing with an if-else statement. I've tried 
` <% if (user) { %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="/profile"><span class="dropdown-toggle glyphicon glyphicon-user"></span> <%= user.local.email %> </a>
        </li>
        <li class="dropdown">
          <a href="/logout"><span class="dropdown-toggle glyphicon glyphicon-off"></span> Log out</a>
        </li>
      </ul>
    <% } else { %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="/login"><span class="dropdown-toggle glyphicon glyphicon-user"></span> Sign in! </a>
        </li>
      </ul>
    <% } %>`

But with no luck... Throws user is not defined.

**Comment by box3x4** [comment]
if i'm not mistaken, you have to do something like

`<% if (this.user) %>`

because user is the name of the property of the object. works for me

**Comment by barrard** [comment]
I wanted a simple way to conditionally render my footer, and i ran into this same undefined error.  I got it working simply by checking typeof == "undefined"

      <% if (typeof no_footer == 'undefined'){ %> 
        <% include includes/footer %>
      <% } %>
