### ISSUE TITLE
TypeError can't dup NilClass

### ISSUE THREAD

**Issue by Yorkshireman** [makersacademy/slack-overflow#91]
Rails 4. This is a very strange error that I've been getting with a simple little Rails app that makes a http request to a dictionary api. Controller code:

```
class PagesController < ApplicationController
  def home
    @wordlists = Wordlist.all
  end

  def get_definition
    word = params["word"]
    client = MWDictionaryAPI::Client.new('2a4dee74-e16f-4805-be47-0e41d7e8d840', api_type: "learners")
    result = client.search(word)
    puts result.to_hash.keys
    puts result.to_hash[:entries]
    redirect_to root_path
  end
end
```
The error occurs on the line `result = client.search(word)`. By the way, I'm using a gem that makes method call possible.

The rest of the code is here if you need it: https://github.com/Yorkshireman/mywordlist2/tree/2b44f434050063ca931d14301956f0c3fd86aeb2

Now, after lots of searching, I found no answers. It's not even clear what this error means, except that I think it means that methods can't be duplicated?

In the end, I tried making the api call using a word I haven't used before, and there was no error!

Question is, WHY was I getting this error?

It was very strange, because yesterday I was getting no errors, even when using the same word over and over. Today, I opened up the app *with no change to my code whatsoever* and the error started happening. Very strange! Can you shed some light on this?

**Comment by Yorkshireman** [comment]
I'm using this gem: https://github.com/gniquil/mw_dictionary_api

Looking further down the docs, it's probably something to do with caching. I will try disabling it. If someone could explain the error further in this context it would be much appreciated.

**Comment by Yorkshireman** [comment]
Failing to 1. clear the cache, and 2. disable the cache. I tried the following:

```
class PagesController < ApplicationController
  def home
    @wordlists = Wordlist.all
  end

  def get_definition
    word = params["word"]
    MWDictionaryAPI::Client.cache.clear
    MWDictionaryAPI::Client.cache = nil
    client = MWDictionaryAPI::Client.new('2a4dee74-e16f-4805-be47-0e41d7e8d840', api_type: "learners")
    result = client.search(word)
    puts result.to_hash.keys
    puts result.to_hash[:entries]
    redirect_to root_path
  end
end
```

**Comment by sjmog** [comment]
My suspicion is that it comes from somewhere around [this module](https://github.com/gniquil/mw_dictionary_api/blob/4fc18dc11b8c6e9ded43951fffa537da378ed9d0/lib/mw_dictionary_api/parsers/definition_parser.rb) as it's the only place in the `MWDictionaryAPI` that uses `dup`.

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
mechacoach!

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

      1. What you're trying to do
      2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
      3. The error you're getting

      That will help a casual browser to quickly point you in the right direction.
