### ISSUE TITLE
Here's an issue!

### ISSUE THREAD

**Issue by sjmog** [makersacademy/slack-overflow#96]
Attempting a test issue.

**Comment by mechacoach** [comment]
A word to the wise - format overflow questions like this:

1. What you're trying to do
2. The code to do it in a [GitHub-flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/) code block
3. The error you're getting

That will help a casual browser to quickly point you in the right direction.

**Comment by sjmog** [comment]
Awesome, thanks @mechacoach !
